# Generated by Django 4.2.16 on 2025-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razao_social", models.CharField(max_length=255)),
                (
                    "produto_servico",
                    models.CharField(
                        choices=[
                            ("Fita de Aço/Inox", "Fita de Aço/Inox"),
                            ("Aço Inox", "Aço Inox"),
                            ("Arame de inox", "Arame de inox"),
                            ("Calibração", "Calibração"),
                            ("Trat. Superficial", "Trat. Superficial"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_homologacao", models.DateField()),
                (
                    "tipo_certificacao",
                    models.CharField(
                        choices=[
                            ("ISO 9001", "ISO 9001"),
                            ("IATF16949", "IATF16949"),
                            ("NBR-ISO 17025 RBC", "NBR-ISO 17025 RBC"),
                            ("AUDITORIA", "AUDITORIA"),
                        ],
                        max_length=50,
                    ),
                ),
                ("validade_certificacao", models.DateField()),
                (
                    "risco",
                    models.CharField(
                        choices=[("Baixo", "Baixo"), ("Alto", "Alto"), ("N/A", "N/A")],
                        max_length=10,
                    ),
                ),
                ("auditoria_realizada_em", models.DateField()),
                (
                    "tipo_formulario",
                    models.CharField(
                        choices=[
                            ("Processo (F154)", "Processo (F154)"),
                            ("CQI-11", "CQI-11"),
                            ("CQI-12", "CQI-12"),
                            ("CQI-9", "CQI-9"),
                            ("N/A", "N/A"),
                        ],
                        max_length=30,
                    ),
                ),
                ("proxima_auditoria", models.DateField(blank=True, null=True)),
                (
                    "nota_percentual",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("classe_frequencia", models.CharField(blank=True, max_length=1)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("responsavel_avaliacao", models.CharField(max_length=255)),
                ("contato", models.CharField(max_length=255)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "iqs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("solicita_certificado", models.BooleanField(default=False)),
                (
                    "email_envio_certificado",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "anexo_certificado",
                    models.FileField(
                        blank=True, null=True, upload_to="certificados_fornecedores/"
                    ),
                ),
            ],
        ),
    ]
