# Generated by Django 4.2.16 on 2025-04-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0002_analiseriscopreliminar_avaliacaofornecedormp_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedorqualificado",
            name="email_envio_certificado",
        ),
        migrations.RemoveField(
            model_name="fornecedorqualificado",
            name="solicita_certificado_fisico",
        ),
    ]
