# Generated by Django 4.2.16 on 2025-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0003_remove_fornecedorqualificado_email_envio_certificado_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="proxima_auditoria",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="proxima_avaliacao_risco",
            field=models.DateField(blank=True, null=True),
        ),
    ]
