# Generated by Django 4.2.16 on 2025-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0004_alter_fornecedorqualificado_proxima_auditoria_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedorqualificado",
            name="iqs",
            field=models.FloatField(blank=True, null=True, verbose_name="IQS"),
        ),
    ]
