# Generated by Django 4.2.16 on 2025-04-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0005_fornecedorqualificado_iqs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedorqualificado",
            name="iqs",
        ),
    ]
