# Generated by Django 4.2.16 on 2025-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0006_remove_fornecedorqualificado_iqs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="data_auditoria",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="data_avaliacao_risco",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="nota_auditoria",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="risco",
            field=models.CharField(
                blank=True,
                choices=[("Baixo", "Baixo"), ("Alto", "Alto"), ("N/A", "N/A")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="tipo_formulario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Processo (F154)", "Processo (F154)"),
                    ("CQI-11", "CQI-11"),
                    ("CQI-12", "CQI-12"),
                    ("CQI-9", "CQI-9"),
                    ("N/A", "N/A"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="vencimento_certificacao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
