# Generated by Django 4.2.16 on 2025-04-03 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0007_alter_fornecedorqualificado_data_auditoria_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analiseriscopreliminar",
            name="fornecedor",
        ),
        migrations.RemoveField(
            model_name="avaliacaofornecedormp",
            name="fornecedor",
        ),
        migrations.RemoveField(
            model_name="avaliacaofornecedorservico",
            name="fornecedor",
        ),
        migrations.DeleteModel(
            name="ComposicaoQuimica",
        ),
        migrations.DeleteModel(
            name="ServicoExterno",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="anexo_certificado",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="classe",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="data_entrega_renegociada",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="ip",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="num_certificado",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="num_relatorio",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="num_rolo",
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="certificado_anexo",
            field=models.FileField(blank=True, null=True, upload_to="certificados/mp/"),
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="classe_especificacao",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Classe / Especificação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="data_entrega_renegociacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Entrega / Renegociação"
            ),
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="demerito_ip",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Demerito (IP)"
            ),
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="numero_certificado",
            field=models.CharField(
                default=1, max_length=50, verbose_name="N° do Certificado"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="numero_relatorio",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="N° do Relatório"
            ),
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="numero_rolo",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="N° do Rolo"
            ),
        ),
        migrations.AlterField(
            model_name="materiaprima",
            name="atraso_dias",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Atraso em Dias"
            ),
        ),
        migrations.AlterField(
            model_name="materiaprima",
            name="data_entrada",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data de Entrada"
            ),
        ),
        migrations.AlterField(
            model_name="materiaprima",
            name="data_prevista_entrega",
            field=models.DateField(verbose_name="Data Prevista de Entrega"),
        ),
        migrations.AlterField(
            model_name="materiaprima",
            name="nota_fiscal",
            field=models.CharField(max_length=50, verbose_name="N. Fiscal"),
        ),
        migrations.AlterField(
            model_name="materiaprima",
            name="status",
            field=models.CharField(
                choices=[("aprovado", "Aprovado"), ("reprovado", "Reprovado")],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="AnaliseRiscoPreliminar",
        ),
        migrations.DeleteModel(
            name="AvaliacaoFornecedorMP",
        ),
        migrations.DeleteModel(
            name="AvaliacaoFornecedorServico",
        ),
    ]
