# Generated by Django 4.2.16 on 2025-04-03 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0008_remove_analiseriscopreliminar_fornecedor_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RelacaoMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nro_relatorio",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "nro_rolo",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("data_entrada", models.DateField(verbose_name="Data de Entrada")),
                (
                    "nota_fiscal",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N. Fiscal"
                    ),
                ),
                (
                    "numero_certificado",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="N° do Certificado",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Código da MP"),
                ),
                (
                    "classe_especificacao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Classe/Especificação",
                    ),
                ),
                (
                    "bitola",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Bitola"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=20,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_prevista_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Prevista de Entrega"
                    ),
                ),
                (
                    "data_renegociada_entrega",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Entrega / Renegociação",
                    ),
                ),
                (
                    "atraso_em_dias",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Atraso em dias"
                    ),
                ),
                (
                    "demerito_ip",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Demérito (IP)"
                    ),
                ),
                (
                    "anexo_certificado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificados/materia_prima/",
                        verbose_name="Anexo do Certificado",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="qualidade_fornecimento.fornecedorqualificado",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MateriaPrima",
        ),
    ]
