# Generated by Django 4.2.16 on 2025-04-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0009_relacaomateriaprima_delete_materiaprima"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relacaomateriaprima",
            name="nro_rolo",
        ),
    ]
