# Generated by Django 4.2.16 on 2025-04-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0010_remove_relacaomateriaprima_nro_rolo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MateriaPrimaCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código da MP"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "localizacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Localização",
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Classe"
                    ),
                ),
                (
                    "norma",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Norma"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Materia-Prima", "Matéria-Prima"),
                            ("Tratamento", "Tratamento"),
                        ],
                        default="Materia-Prima",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "bitola",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Bitola"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="relacaomateriaprima",
            name="bitola",
        ),
        migrations.RemoveField(
            model_name="relacaomateriaprima",
            name="classe_especificacao",
        ),
        migrations.RemoveField(
            model_name="relacaomateriaprima",
            name="codigo",
        ),
        migrations.CreateModel(
            name="RoloMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nro_rolo",
                    models.CharField(max_length=50, verbose_name="N° do Rolo"),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Peso",
                    ),
                ),
                (
                    "tb050",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rolos",
                        to="qualidade_fornecimento.relacaomateriaprima",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relacaomateriaprima",
            name="materia_prima",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="qualidade_fornecimento.materiaprimacatalogo",
                verbose_name="Matéria-Prima",
            ),
            preserve_default=False,
        ),
    ]
