# Generated by Django 4.2.16 on 2025-04-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0011_materiaprimacatalogo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiaprimacatalogo",
            name="bitola",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="materiaprimacatalogo",
            name="classe",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="materiaprimacatalogo",
            name="codigo",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="materiaprimacatalogo",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="materiaprimacatalogo",
            name="localizacao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="materiaprimacatalogo",
            name="norma",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="materiaprimacatalogo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Materia-Prima", "Matéria-Prima"),
                    ("Tratamento", "Tratamento"),
                ],
                default="Materia-Prima",
                max_length=50,
            ),
        ),
    ]
