# Generated by Django 4.2.16 on 2025-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0012_alter_materiaprimacatalogo_bitola_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="nro_rolo",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N° do Rolo"
            ),
        ),
    ]
