# Generated by Django 4.2.16 on 2025-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0013_alter_rolomateriaprima_nro_rolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="relacaomateriaprima",
            name="item_seguranca",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Item Segurança",
            ),
        ),
        migrations.AddField(
            model_name="relacaomateriaprima",
            name="material_cliente",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Material do Cliente",
            ),
        ),
    ]
