# Generated by Django 4.2.16 on 2025-04-10 11:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0015_materiaprimacatalogo_tipo_abnt"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormaComposicaoQuimica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_norma", models.CharField(max_length=100, verbose_name="Norma")),
                (
                    "tipo_abnt",
                    models.CharField(max_length=100, verbose_name="Tipo ABNT"),
                ),
                (
                    "arquivo_norma",
                    models.FileField(blank=True, null=True, upload_to="normas/"),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qualidade_fornecimento.materiaprimacatalogo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResistenciaTracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bitola_minima", models.DecimalField(decimal_places=2, max_digits=5)),
                ("bitola_maxima", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "resistencia_min",
                    models.PositiveIntegerField(
                        verbose_name="Resistência Mínima (Kgf/mm²)"
                    ),
                ),
                (
                    "resistencia_max",
                    models.PositiveIntegerField(
                        verbose_name="Resistência Máxima (Kgf/mm²)"
                    ),
                ),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracoes",
                        to="qualidade_fornecimento.normacomposicaoquimica",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElementoQuimico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "elemento",
                    models.CharField(
                        choices=[
                            ("Carbono", "Carbono"),
                            ("Manganês", "Manganês"),
                            ("Silício", "Silício"),
                            ("Fósforo", "Fósforo"),
                            ("Enxofre", "Enxofre"),
                            ("Cromo", "Cromo"),
                            ("Níquel", "Níquel"),
                            ("Cobre", "Cobre"),
                            ("Alumínio", "Alumínio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "minimo",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "maximo",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementos",
                        to="qualidade_fornecimento.normacomposicaoquimica",
                    ),
                ),
            ],
        ),
    ]
