# Generated by Django 4.2.16 on 2025-04-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0016_normacomposicaoquimica_resistenciatracao_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="normacomposicaoquimica",
            name="materia_prima",
        ),
    ]
