# Generated by Django 4.2.16 on 2025-04-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0018_normacomposicaoquimica_vinculo_norma"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormaComposicaoElemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elemento", models.CharField(max_length=50)),
                ("minimo", models.DecimalField(decimal_places=2, max_digits=5)),
                ("maximo", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="NormaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_norma", models.CharField(max_length=100)),
                ("arquivo_norma", models.FileField(upload_to="normas/")),
                (
                    "vinculo_norma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relacionadas",
                        to="qualidade_fornecimento.normatecnica",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormaTracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bitola_minima", models.DecimalField(decimal_places=2, max_digits=5)),
                ("bitola_maxima", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "resistencia_min",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "resistencia_max",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracoes",
                        to="qualidade_fornecimento.normatecnica",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="normacomposicaoquimica",
            name="vinculo_norma",
        ),
        migrations.RemoveField(
            model_name="resistenciatracao",
            name="norma",
        ),
        migrations.DeleteModel(
            name="ElementoQuimico",
        ),
        migrations.DeleteModel(
            name="NormaComposicaoQuimica",
        ),
        migrations.DeleteModel(
            name="ResistenciaTracao",
        ),
        migrations.AddField(
            model_name="normacomposicaoelemento",
            name="norma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elementos",
                to="qualidade_fornecimento.normatecnica",
            ),
        ),
    ]
