# Generated by Django 4.2.16 on 2025-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0019_normacomposicaoelemento_normatecnica_normatracao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="normacomposicaoelemento",
            name="elemento",
            field=models.CharField(
                choices=[
                    ("C", "Carbono"),
                    ("Mn", "Manganês"),
                    ("Si", "Silício"),
                    ("P", "Fósforo"),
                    ("S", "Enxofre"),
                    ("Cr", "Cromo"),
                    ("Ni", "Níquel"),
                    ("Cu", "Cobre"),
                    ("Al", "Alumínio"),
                ],
                max_length=3,
            ),
        ),
    ]
