# Generated by Django 4.2.16 on 2025-04-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0020_alter_normacomposicaoelemento_elemento"),
    ]

    operations = [
        migrations.AddField(
            model_name="normatecnica",
            name="tipo_abnt",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo ABNT"
            ),
        ),
    ]
