# Generated by Django 4.2.16 on 2025-04-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0022_alter_normacomposicaoelemento_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="normatecnica",
            name="vinculo_norma",
        ),
    ]
