# Generated by Django 4.2.16 on 2025-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0023_remove_normatecnica_vinculo_norma"),
    ]

    operations = [
        migrations.AddField(
            model_name="normatecnica",
            name="vinculo_norma",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Nome da Norma"
            ),
            preserve_default=False,
        ),
    ]
