# Generated by Django 4.2.16 on 2025-04-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0024_normatecnica_vinculo_norma"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioF045",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_relatorio", models.PositiveIntegerField(editable=False)),
                ("fornecedor", models.CharField(editable=False, max_length=120)),
                ("nota_fiscal", models.CharField(editable=False, max_length=50)),
                ("numero_certificado", models.CharField(editable=False, max_length=50)),
                ("material", models.CharField(editable=False, max_length=200)),
                ("bitola", models.CharField(editable=False, max_length=30)),
                ("qtd_rolos", models.PositiveIntegerField(editable=False)),
                (
                    "massa_liquida",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("qtd_carreteis", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pedido_compra",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "c_user",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="C (%)",
                    ),
                ),
                (
                    "mn_user",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Mn (%)",
                    ),
                ),
                ("laudo_composicao", models.CharField(editable=False, max_length=12)),
                ("dureza", models.CharField(blank=True, max_length=50, null=True)),
                ("enrolamento", models.CharField(blank=True, max_length=50, null=True)),
                ("dobramento", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "torcao_residual",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "aspecto_visual",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("laudo_final", models.CharField(editable=False, max_length=12)),
                ("assinado_por", models.CharField(editable=False, max_length=120)),
                ("assinado_email", models.EmailField(editable=False, max_length=254)),
                ("assinado_em", models.DateTimeField(auto_now_add=True)),
                ("pdf", models.FileField(blank=True, null=True, upload_to="f045/")),
                (
                    "relacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="f045",
                        to="qualidade_fornecimento.relacaomateriaprima",
                    ),
                ),
            ],
        ),
    ]
