# Generated by Django 4.2.16 on 2025-04-11 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qualidade_fornecimento", "0025_relatoriof045"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatoriof045",
            options={
                "verbose_name": "Relatório F‑045",
                "verbose_name_plural": "Relatórios F‑045",
            },
        ),
        migrations.RemoveField(
            model_name="relatoriof045",
            name="assinado_email",
        ),
        migrations.RemoveField(
            model_name="relatoriof045",
            name="assinado_por",
        ),
        migrations.RemoveField(
            model_name="relatoriof045",
            name="laudo_final",
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="al_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Al\u202f(%)",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="cr_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Cr\u202f(%)",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="cu_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Cu\u202f(%)",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="laudo_interno",
            field=models.CharField(
                blank=True,
                choices=[("Ap", "Aprovado"), ("Re", "Reprovado")],
                editable=False,
                max_length=2,
                verbose_name="Laudo – características internas",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="ni_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Ni\u202f(%)",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="p_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="P\u202f(%)",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="s_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="S\u202f(%)",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="si_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Si\u202f(%)",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="c_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="C\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="dureza",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Dureza\u202f(HB)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="laudo_composicao",
            field=models.CharField(
                blank=True,
                choices=[("Ap", "Aprovado"), ("Re", "Reprovado")],
                editable=False,
                max_length=2,
                verbose_name="Laudo – composição",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="mn_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Mn\u202f(%)",
            ),
        ),
    ]
