# Generated by Django 4.2.16 on 2025-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0026_alter_relatoriof045_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriof045",
            name="observacoes",
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
    ]
