# Generated by Django 4.2.16 on 2025-04-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0027_relatoriof045_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiaprimacatalogo",
            name="tolerancia",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Tolerância"
            ),
        ),
    ]
