# Generated by Django 4.2.16 on 2025-04-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0029_relatoriof045_alongamento_relatoriof045_escoamento_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="normatracao",
            name="dureza",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Dureza (HR)"
            ),
        ),
    ]
