# Generated by Django 4.2.16 on 2025-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0030_normatracao_dureza"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriof045",
            name="dureza_certificado",
            field=models.CharField(
                blank=True,
                default="N/A",
                max_length=50,
                null=True,
                verbose_name="Dureza (certificado)",
            ),
        ),
    ]
