# Generated by Django 4.2.16 on 2025-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0031_relatoriof045_dureza_certificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriof045",
            name="status_geral",
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
