# Generated by Django 4.2.16 on 2025-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0032_relatoriof045_status_geral"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolomateriaprima",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="aspecto_visual",
            field=models.CharField(
                choices=[("OK", "OK"), ("NOK", "NOK")], default="OK", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="bitola_inspecionada",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="dobramento",
            field=models.CharField(
                choices=[("OK", "OK"), ("NOK", "NOK")], default="OK", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="dureza",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="enrolamento",
            field=models.CharField(
                choices=[("OK", "OK"), ("NOK", "NOK")], default="OK", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="torcao_residual",
            field=models.CharField(
                choices=[("OK", "OK"), ("NOK", "NOK")], default="OK", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="tracao",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
