# Generated by Django 4.2.16 on 2025-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0033_rolomateriaprima_aprovado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="aspecto_visual",
            field=models.CharField(
                blank=True, choices=[("OK", "OK"), ("NOK", "NOK")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="bitola_inspecionada",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Bitola",
            ),
        ),
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="dobramento",
            field=models.CharField(
                blank=True, choices=[("OK", "OK"), ("NOK", "NOK")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="dureza",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Dureza",
            ),
        ),
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="enrolamento",
            field=models.CharField(
                blank=True, choices=[("OK", "OK"), ("NOK", "NOK")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="torcao_residual",
            field=models.CharField(
                blank=True, choices=[("OK", "OK"), ("NOK", "NOK")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="tracao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Resistência à Tração",
            ),
        ),
    ]
