# Generated by Django 4.2.16 on 2025-04-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0034_alter_rolomateriaprima_aspecto_visual_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatoriof045",
            name="aspecto_visual",
        ),
        migrations.RemoveField(
            model_name="relatoriof045",
            name="dobramento",
        ),
        migrations.RemoveField(
            model_name="relatoriof045",
            name="dureza",
        ),
        migrations.RemoveField(
            model_name="relatoriof045",
            name="enrolamento",
        ),
        migrations.RemoveField(
            model_name="relatoriof045",
            name="torcao_residual",
        ),
    ]
