# Generated by Django 4.2.16 on 2025-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0036_alter_normatracao_dureza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normatracao",
            name="dureza",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=6,
                null=True,
                verbose_name="Dureza (HR)",
            ),
        ),
    ]
