# Generated by Django 4.2.16 on 2025-04-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0038_alter_normatracao_dureza"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolomateriaprima",
            name="aprovado",
        ),
    ]
