# Generated by Django 4.2.16 on 2025-04-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0039_remove_rolomateriaprima_aprovado"),
    ]

    operations = [
        migrations.AddField(
            model_name="relacaomateriaprima",
            name="anexo_f045",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="relatorios/f045/",
                verbose_name="Relatório F045 Gerado",
            ),
        ),
    ]
