# Generated by Django 4.2.16 on 2025-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0040_relacaomateriaprima_anexo_f045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relacaomateriaprima",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aguardando F045", "Aguardando F045"),
                    ("Aprovado", "Aprovado"),
                    ("Aprovado Condicionalmente", "Aprovado Condicionalmente"),
                    ("Reprovado", "Reprovado"),
                ],
                max_length=30,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
