# Generated by Django 4.2.16 on 2025-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0041_alter_relacaomateriaprima_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiaprimacatalogo",
            name="tolerancia_largura",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Tolerância Largura"
            ),
        ),
    ]
