# Generated by Django 4.2.16 on 2025-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0042_materiaprimacatalogo_tolerancia_largura"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiaprimacatalogo",
            name="largura",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Largura Nominal",
            ),
        ),
    ]
