# Generated by Django 4.2.16 on 2025-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0044_alter_materiaprimacatalogo_largura"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolomateriaprima",
            name="bitola_espessura",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Espessura",
            ),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="bitola_largura",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Largura",
            ),
        ),
    ]
