# Generated by Django 4.2.16 on 2025-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0045_rolomateriaprima_bitola_espessura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolomateriaprima",
            name="laudo",
            field=models.CharField(default="Aguardando", max_length=20),
        ),
    ]
