# Generated by Django 4.2.16 on 2025-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0046_rolomateriaprima_laudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolomateriaprima",
            name="alongamento",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOK", "NOK")],
                max_length=10,
                verbose_name="Alongamento",
            ),
        ),
        migrations.AddField(
            model_name="rolomateriaprima",
            name="flechamento",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOK", "NOK")],
                max_length=10,
                verbose_name="Flechamento",
            ),
        ),
    ]
