# Generated by Django 4.2.16 on 2025-04-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0048_remove_rolomateriaprima_bitola_inspecionada"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleServicoExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pedido", models.CharField(max_length=100)),
                ("codigo_bm", models.CharField(max_length=50)),
                ("fornecedor", models.CharField(max_length=100)),
                ("lead_time", models.IntegerField()),
                (
                    "quantidade_enviada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("data_envio", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOK", "NOK")], max_length=3
                    ),
                ),
                ("data_retorno", models.DateField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("status2", models.CharField(blank=True, max_length=50)),
                (
                    "iqf",
                    models.CharField(
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=10,
                    ),
                ),
                ("atraso_em_dias", models.IntegerField(blank=True, null=True)),
                ("ip", models.IntegerField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "dia_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_7",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_8",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_9",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_10",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_11",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_12",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_13",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_14",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_15",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_16",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_17",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_18",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_19",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_20",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_21",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_22",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_23",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_24",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_25",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_26",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_27",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_28",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_29",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_30",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dia_31",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
