# Generated by Django 4.2.16 on 2025-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0050_remove_controleservicoexterno_dia_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedorqualificado",
            name="lead_time",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Lead Time (dias)"
            ),
        ),
    ]
