# Generated by Django 4.2.16 on 2025-04-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0051_fornecedorqualificado_lead_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controleservicoexterno",
            name="status",
        ),
        migrations.AddField(
            model_name="controleservicoexterno",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="controleservicoexterno",
            name="codigo_bm",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "Tratamento"},
                on_delete=django.db.models.deletion.PROTECT,
                to="qualidade_fornecimento.materiaprimacatalogo",
            ),
        ),
        migrations.AlterField(
            model_name="controleservicoexterno",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="servicos_externos",
                to="qualidade_fornecimento.fornecedorqualificado",
            ),
        ),
        migrations.AlterField(
            model_name="controleservicoexterno",
            name="iqf",
            field=models.CharField(
                blank=True,
                choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="controleservicoexterno",
            name="lead_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
