# Generated by Django 4.2.16 on 2025-04-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0052_remove_controleservicoexterno_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="controleservicoexterno",
            name="op",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Ordem de Produção"
            ),
            preserve_default=False,
        ),
    ]
