# Generated by Django 4.2.16 on 2025-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0053_controleservicoexterno_op"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleservicoexterno",
            name="nota_fiscal",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Nota Fiscal"
            ),
            preserve_default=False,
        ),
    ]
