# Generated by Django 4.2.16 on 2025-04-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0054_controleservicoexterno_nota_fiscal"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspecaoServicoExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_certificado", models.CharField(max_length=100)),
                (
                    "certificado_pdf",
                    models.FileField(upload_to="certificados_servico_externo/"),
                ),
                (
                    "visual",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOK", "NOK")], max_length=10
                    ),
                ),
                (
                    "espessura",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOK", "NOK")], max_length=10
                    ),
                ),
                (
                    "salt_spray",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOK", "NOK")], max_length=10
                    ),
                ),
                ("aprovacao_manual", models.BooleanField(default=False)),
                (
                    "status_final",
                    models.CharField(default="Aguardando Inspeção", max_length=50),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "servico",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspecao",
                        to="qualidade_fornecimento.controleservicoexterno",
                    ),
                ),
            ],
        ),
    ]
