# Generated by Django 4.2.16 on 2025-04-22 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0055_inspecaoservicoexterno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inspecaoservicoexterno",
            old_name="aprovacao_manual",
            new_name="aprovado_condicionalmente",
        ),
        migrations.RenameField(
            model_name="inspecaoservicoexterno",
            old_name="nro_certificado",
            new_name="certificado_numero",
        ),
        migrations.RenameField(
            model_name="inspecaoservicoexterno",
            old_name="espessura",
            new_name="espessura_camada",
        ),
        migrations.RenameField(
            model_name="inspecaoservicoexterno",
            old_name="visual",
            new_name="inspecao_visual",
        ),
        migrations.RemoveField(
            model_name="inspecaoservicoexterno",
            name="certificado_pdf",
        ),
        migrations.RemoveField(
            model_name="inspecaoservicoexterno",
            name="status_final",
        ),
        migrations.AddField(
            model_name="inspecaoservicoexterno",
            name="certificado_anexo",
            field=models.FileField(
                blank=True, null=True, upload_to="certificados_servico_externo/"
            ),
        ),
        migrations.AddField(
            model_name="inspecaoservicoexterno",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
