# Generated by Django 4.2.16 on 2025-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0056_rename_aprovacao_manual_inspecaoservicoexterno_aprovado_condicionalmente_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inspecaoservicoexterno",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
