# Generated by Django 4.2.16 on 2025-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0057_inspecaoservicoexterno_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspecaoservicoexterno",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="inspecao_servico_externo_pdfs/"
            ),
        ),
    ]
