# Generated by Django 4.2.16 on 2025-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0058_inspecaoservicoexterno_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedorqualificado",
            name="especialista_cargo",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
