# Generated by Django 4.2.16 on 2025-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0059_fornecedorqualificado_especialista_cargo"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiaprimacatalogo",
            name="tipo_material",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo de Material"
            ),
        ),
    ]
