# Generated by Django 4.2.16 on 2025-04-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0060_materiaprimacatalogo_tipo_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normatecnica",
            name="arquivo_norma",
            field=models.FileField(
                blank=True, null=True, upload_to="normas/", verbose_name="Arquivo (PDF)"
            ),
        ),
    ]
