# Generated by Django 4.2.16 on 2025-04-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0061_alter_normatecnica_arquivo_norma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normatecnica",
            name="vinculo_norma",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Norma vinculada (tração)",
            ),
        ),
    ]
