# Generated by Django 4.2.16 on 2025-04-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0062_alter_normatecnica_vinculo_norma"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormaCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "norma",
                    models.CharField(max_length=100, verbose_name="Nome da Norma"),
                ),
                (
                    "tipo_abnt",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tipo ABNT"
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Classe"
                    ),
                ),
                (
                    "tipo_material",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Material",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Norma Catálogo",
                "verbose_name_plural": "Normas Catálogo",
                "unique_together": {("norma", "tipo_abnt")},
            },
        ),
    ]
