# Generated by Django 4.2.16 on 2025-04-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0063_normacatalogo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NormaCatalogo",
        ),
    ]
