# Generated by Django 4.2.16 on 2025-04-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0064_delete_normacatalogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiaprimacatalogo",
            name="norma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materias_primas",
                to="qualidade_fornecimento.normatecnica",
                verbose_name="Norma",
            ),
        ),
    ]
