# Generated by Django 4.2.16 on 2025-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0065_alter_materiaprimacatalogo_norma"),
    ]

    operations = [
        migrations.AddField(
            model_name="normatracao",
            name="tipo_abnt",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo ABNT"
            ),
        ),
    ]
