# Generated by Django 4.2.16 on 2025-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0066_normatracao_tipo_abnt"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleservicoexterno",
            name="previsao_entrega",
            field=models.DateField(blank=True, null=True),
        ),
    ]
