# Generated by Django 4.2.16 on 2025-05-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0067_controleservicoexterno_previsao_entrega"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controleservicoexterno",
            name="iqf",
        ),
    ]
