# Generated by Django 4.2.16 on 2025-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0068_remove_controleservicoexterno_iqf"),
    ]

    operations = [
        migrations.AddField(
            model_name="normatecnica",
            name="aprovada",
            field=models.BooleanField(
                default=False, verbose_name="Norma aprovada para uso?"
            ),
        ),
    ]
