# Generated by Django 4.2.16 on 2025-05-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0071_alter_alertausuario_titulo_alertaconfigurado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertausuario",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="AlertaConfigurado",
        ),
        migrations.DeleteModel(
            name="AlertaUsuario",
        ),
    ]
