# Generated by Django 4.2.16 on 2025-05-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0072_remove_alertausuario_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normatracao",
            name="bitola_maxima",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Bitola máx (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="normatracao",
            name="bitola_minima",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Bitola mín (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="normatracao",
            name="resistencia_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="R. tração máx (Kgf/mm²)",
            ),
        ),
        migrations.AlterField(
            model_name="normatracao",
            name="resistencia_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="R. tração mín (Kgf/mm²)",
            ),
        ),
    ]
