# Generated by Django 4.2.16 on 2025-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0073_alter_normatracao_bitola_maxima_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="produto_servico",
            field=models.CharField(
                choices=[
                    ("Fita de Aço/Inox", "Fita de Aço/Inox"),
                    ("Arame de Aço", "Arame de Aço"),
                    ("Arame de inox", "Arame de inox"),
                    ("Calibração", "Calibração"),
                    ("Trat. Superficial", "Trat. Superficial"),
                ],
                max_length=50,
            ),
        ),
    ]
