# Generated by Django 4.2.16 on 2025-05-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qualidade_fornecimento", "0074_alter_fornecedorqualificado_produto_servico"),
    ]

    operations = [
        migrations.AddField(
            model_name="normatecnica",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normas_aprovadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovado por",
            ),
        ),
    ]
