# Generated by Django 4.2.16 on 2025-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0075_normatecnica_aprovado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="normatecnica",
            name="aprovado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da aprovação"
            ),
        ),
    ]
