# Generated by Django 4.2.16 on 2025-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0076_normatecnica_aprovado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatoriof045",
            name="al_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="Al\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="c_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="C\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="cr_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="Cr\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="cu_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="Cu\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="mn_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="Mn\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="ni_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="Ni\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="p_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="P\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="s_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="S\u202f(%)",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriof045",
            name="si_user",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="Si\u202f(%)",
            ),
        ),
    ]
