# Generated by Django 4.2.16 on 2025-06-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0077_alter_relatoriof045_al_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriof045",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
    ]
