# Generated by Django 4.2.16 on 2025-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0078_relatoriof045_data_assinatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriof045",
            name="assinado_por",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Assinado por"
            ),
        ),
    ]
