# Generated by Django 4.2.16 on 2025-06-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0079_relatoriof045_assinado_por"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatoriof045",
            name="assinado_por",
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="relatoriof045",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
    ]
