# Generated by Django 4.2.16 on 2025-06-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0080_remove_relatoriof045_assinado_por_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatoriof045",
            name="pdf",
        ),
    ]
