# Generated by Django 4.2.16 on 2025-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0081_remove_relatoriof045_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolomateriaprima",
            name="id",
        ),
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="nro_rolo",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="N° do Rolo",
            ),
        ),
    ]
