# Generated by Django 4.2.16 on 2025-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0082_remove_rolomateriaprima_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="nro_rolo",
            field=models.CharField(
                blank=True,
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="N° do Rolo",
            ),
        ),
    ]
