# Generated by Django 4.2.16 on 2025-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0084_controleservicoexterno_data_negociada"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspecaoservicoexterno",
            name="assinatura_data",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspecaoservicoexterno",
            name="assinatura_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="inspecaoservicoexterno",
            name="assinatura_nome",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
