# Generated by Django 4.2.16 on 2025-06-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0085_inspecaoservicoexterno_assinatura_data_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspecao10",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da Inspeção")),
                (
                    "fornecedor",
                    models.CharField(max_length=255, verbose_name="Fornecedor"),
                ),
                (
                    "numero_nf",
                    models.CharField(max_length=50, verbose_name="Nº Nota Fiscal"),
                ),
                (
                    "quantidade_lote",
                    models.PositiveIntegerField(verbose_name="Quantidade do Lote"),
                ),
                (
                    "quantidade_amostrada",
                    models.PositiveIntegerField(verbose_name="Quantidade Amostrada"),
                ),
                (
                    "aprovado",
                    models.BooleanField(default=False, verbose_name="Aprovado?"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Inspeção 10",
                "verbose_name_plural": "Inspeções 10",
            },
        ),
    ]
