# Generated by Django 4.2.16 on 2025-06-24 11:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qualidade_fornecimento", "0086_inspecao10"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspecao10",
            name="aprovado",
        ),
        migrations.RemoveField(
            model_name="inspecao10",
            name="numero_nf",
        ),
        migrations.RemoveField(
            model_name="inspecao10",
            name="quantidade_amostrada",
        ),
        migrations.RemoveField(
            model_name="inspecao10",
            name="quantidade_lote",
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="codigo_brasmol",
            field=models.CharField(
                default="SEM_CODIGO", max_length=50, verbose_name="Código Bras-Mol"
            ),
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="hora_fim",
            field=models.TimeField(
                default=datetime.time(0, 0), verbose_name="Hora - Fim"
            ),
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="hora_inicio",
            field=models.TimeField(
                default=datetime.time(0, 0), verbose_name="Hora - Início"
            ),
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="numero_op",
            field=models.CharField(
                default="000000", max_length=20, verbose_name="Nº OP"
            ),
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="quantidade_nok",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade Não OK"
            ),
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="quantidade_total",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade Total"
            ),
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="status",
            field=models.CharField(blank=True, max_length=50, verbose_name="Tipo"),
        ),
        migrations.AddField(
            model_name="inspecao10",
            name="tempo_gasto",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Tempo Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="inspecao10",
            name="data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="inspecao10",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qualidade_fornecimento.fornecedorqualificado",
            ),
        ),
        migrations.AlterField(
            model_name="inspecao10",
            name="observacoes",
            field=models.TextField(
                default="Migrado automaticamente", verbose_name="Observações"
            ),
        ),
    ]
