# Generated by Django 4.2.16 on 2025-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0087_remove_inspecao10_aprovado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspecao10",
            name="status",
            field=models.CharField(
                blank=True, editable=False, max_length=30, verbose_name="Status"
            ),
        ),
    ]
