# Generated by Django 4.2.16 on 2025-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0089_alter_inspecao10_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedorqualificado",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Fornecedor Ativo"),
        ),
    ]
