# Generated by Django 4.2.16 on 2025-06-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0090_fornecedorqualificado_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="ativo",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=10,
                verbose_name="Status do Fornecedor",
            ),
        ),
    ]
