# Generated by Django 4.2.16 on 2025-06-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0091_alter_fornecedorqualificado_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspecao10",
            name="disposicao",
            field=models.CharField(
                choices=[("Sucatear", "Sucatear"), ("Devolver", "Devolver")],
                default="Sucatear",
                max_length=20,
                verbose_name="Disposição",
            ),
        ),
        migrations.AlterField(
            model_name="inspecao10",
            name="codigo_brasmol",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "Tratamento"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qualidade_fornecimento.materiaprimacatalogo",
                verbose_name="Código Bras-Mol",
            ),
        ),
    ]
