# Generated by Django 4.2.16 on 2025-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0093_devolucaoservicoexterno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleservicoexterno",
            name="data_envio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
