# Generated by Django 4.2.16 on 2025-06-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0094_alter_controleservicoexterno_data_envio"),
    ]

    operations = [
        migrations.AddField(
            model_name="devolucaoservicoexterno",
            name="baixado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
