# Generated by Django 4.2.16 on 2025-06-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0095_devolucaoservicoexterno_baixado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleservicoexterno",
            name="op",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ordem de Produção"
            ),
        ),
    ]
