# Generated by Django 4.2.16 on 2025-06-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0096_alter_controleservicoexterno_op"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleservicoexterno",
            name="nota_fiscal",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nota Fiscal"
            ),
        ),
    ]
