# Generated by Django 4.2.16 on 2025-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0097_alter_controleservicoexterno_nota_fiscal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="produto_servico",
            field=models.CharField(
                choices=[
                    ("Fita de Aço/Inox", "Fita de Aço/Inox"),
                    ("Arame de Aço", "Arame de Aço"),
                    ("Arame de inox", "Arame de inox"),
                    ("Calibração", "Calibração"),
                    ("Trat. Superficial", "Trat. Superficial"),
                    ("Material do Cliente", "Material do Cliente"),
                ],
                max_length=50,
            ),
        ),
    ]
