# Generated by Django 4.2.16 on 2025-07-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0098_alter_fornecedorqualificado_produto_servico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="data_homologacao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
