# Generated by Django 4.2.16 on 2025-08-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0164_avaliacaotreinamento_data_conclusao"),
        ("qualidade_fornecimento", "0099_alter_fornecedorqualificado_data_homologacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspecao10",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Funcionario.departamentos",
                verbose_name="Setor",
            ),
        ),
    ]
