# Generated by Django 4.2.16 on 2025-08-13 14:42

from django.db import migrations, models
import qualidade_fornecimento.models.fornecedor


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0100_inspecao10_setor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="certificado_anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=qualidade_fornecimento.models.fornecedor.renomear_certificado_fornecedor,
                validators=[
                    qualidade_fornecimento.models.fornecedor.MaxFileSizeValidator(5)
                ],
                verbose_name="Certificado Anexo",
            ),
        ),
    ]
