# Generated by Django 4.2.16 on 2025-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0101_alter_fornecedorqualificado_certificado_anexo",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedorqualificado",
            name="ativo",
            field=models.CharField(
                choices=[
                    ("Ativo", "Ativo"),
                    ("Em Homologação", "Em Homologação"),
                    ("Inativo", "Inativo"),
                ],
                default="Em Homologação",
                max_length=20,
                verbose_name="Status do Fornecedor",
            ),
        ),
    ]
