# Generated by Django 4.2.16 on 2025-08-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0102_alter_fornecedorqualificado_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="bitola_espessura",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Espessura",
            ),
        ),
        migrations.AlterField(
            model_name="rolomateriaprima",
            name="bitola_largura",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Largura",
            ),
        ),
    ]
