# Generated by Django 4.2.16 on 2025-09-10 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "qualidade_fornecimento",
            "0103_alter_rolomateriaprima_bitola_espessura_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("data_corte", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("EM_CONTAGEM_1", "Em 1ª Contagem"),
                            ("EM_CONTAGEM_2", "Em 2ª Contagem"),
                            ("EM_CONFERENCIA", "Em Confronto/Conferência"),
                            ("DIVERGENTE", "Divergente"),
                            ("CONSOLIDADO", "Consolidado"),
                            ("EXPORTADO", "Exportado"),
                        ],
                        default="ABERTO",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("consolidado_em", models.DateTimeField(blank=True, null=True)),
                ("hash_consolidacao", models.CharField(blank=True, max_length=64)),
                (
                    "consolidado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventarios_consolidados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventarios_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventarios_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("consolidar_inventario", "Pode consolidar inventário"),
                    ("exportar_inventario", "Pode exportar inventário"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventarioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_item", models.CharField(max_length=60)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("etiqueta", models.CharField(blank=True, max_length=100)),
                ("unidade", models.CharField(blank=True, max_length=10)),
                ("local", models.CharField(blank=True, max_length=60)),
                (
                    "estoque_erp",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "quantidade_consolidada",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="qualidade_fornecimento.inventario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventarioExportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("formato", models.CharField(default="CSV", max_length=20)),
                (
                    "arquivo",
                    models.FileField(blank=True, upload_to="inventarios/exportacoes/"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exportacoes",
                        to="qualidade_fornecimento.inventario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Divergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qtd_contagem1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "qtd_contagem2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "qtd_contagem3",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("houve_divergencia", models.BooleanField(default=False)),
                ("resolvido_por_ajuste", models.BooleanField(default=False)),
                ("justificativa_ajuste", models.TextField(blank=True)),
                ("resolvido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "inventario_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divergencia",
                        to="qualidade_fornecimento.inventarioitem",
                    ),
                ),
                (
                    "resolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="divergencias_resolvidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Primeira"), (2, "Segunda"), (3, "Terceira")]
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=4, max_digits=14)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("origem_qrcode", models.CharField(blank=True, max_length=120)),
                (
                    "inventario_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contagens",
                        to="qualidade_fornecimento.inventarioitem",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("inventario_item", "ordem")},
            },
        ),
    ]
