# Generated by Django 4.2.16 on 2025-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0104_inventario_inventarioitem_inventarioexportacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="tipo",
            field=models.CharField(
                choices=[("MP", "Matéria-prima"), ("PA", "Produto acabado")],
                default="MP",
                max_length=2,
            ),
        ),
    ]
