# Generated by Django 4.2.16 on 2025-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0105_inventario_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventarioitem",
            name="fornecedor",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
