# Generated by Django 4.2.16 on 2025-09-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0106_inventarioitem_fornecedor"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventarioitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("etiqueta", ""), _negated=True),
                fields=("inventario", "etiqueta"),
                name="uq_inventarioitem_inventario_etiqueta",
            ),
        ),
    ]
