# Generated by Django 4.2.16 on 2025-09-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0107_inventarioitem_uq_inventarioitem_inventario_etiqueta",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventarioitem",
            name="uq_inventarioitem_inventario_etiqueta",
        ),
        migrations.AddIndex(
            model_name="inventarioitem",
            index=models.Index(
                fields=["inventario", "etiqueta"], name="idx_invitem_inv_etq"
            ),
        ),
    ]
