# Generated by Django 4.2.16 on 2025-09-11 13:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tecnico", "0009_alter_insumoetapa_peso_bruto_and_more"),
        (
            "qualidade_fornecimento",
            "0108_remove_inventarioitem_uq_inventarioitem_inventario_etiqueta_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EstoqueIntermediario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "op",
                    models.CharField(db_index=True, max_length=30, verbose_name="OP"),
                ),
                (
                    "qtde_op_prevista",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Qtd MP prevista (kg)",
                    ),
                ),
                (
                    "pecas_planejadas_op",
                    models.PositiveIntegerField(verbose_name="Peças planejadas OP"),
                ),
                (
                    "enviado",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        verbose_name="Enviado à fábrica (kg)",
                    ),
                ),
                (
                    "retorno",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        verbose_name="Retorno (kg)",
                    ),
                ),
                (
                    "sucata",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        verbose_name="Sucata (kg)",
                    ),
                ),
                (
                    "refugo",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        verbose_name="Refugo (kg)",
                    ),
                ),
                (
                    "pecas_apontadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Peças apontadas"
                    ),
                ),
                (
                    "consumo_inferido_kg",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=12
                    ),
                ),
                (
                    "consumo_balanca_kg",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=12
                    ),
                ),
                (
                    "consumo_real_kg",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=12
                    ),
                ),
                (
                    "tolerancia_sucata_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        max_digits=5,
                        verbose_name="Tolerância de sucata (%)",
                    ),
                ),
                (
                    "custo_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo por kg (opcional)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_FABRICA", "Em Fábrica"),
                            ("RETORNADO", "Retornado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="EM_FABRICA",
                        max_length=12,
                    ),
                ),
                ("data_envio", models.DateTimeField(blank=True, null=True)),
                ("data_retorno", models.DateTimeField(blank=True, null=True)),
                ("setor", models.CharField(blank=True, max_length=60)),
                ("linha", models.CharField(blank=True, max_length=60)),
                (
                    "turno",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "anexo",
                    models.FileField(
                        blank=True, upload_to="estoque_intermediario/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "justificativa_excesso",
                    models.TextField(
                        blank=True, verbose_name="Justificativa p/ excesso de sucata"
                    ),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ei_aprovou_excesso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ei_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_estoque_intermediario",
                        to="qualidade_fornecimento.rolomateriaprima",
                        verbose_name="Lote / Rolo",
                    ),
                ),
                (
                    "maquina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tecnico.maquina",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estoques_intermediarios",
                        to="qualidade_fornecimento.materiaprimacatalogo",
                        verbose_name="Matéria-prima",
                    ),
                ),
                (
                    "responsavel_envio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ei_responsavel_envio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel_retorno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ei_responsavel_retorno",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tb050",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_estoque_intermediario",
                        to="qualidade_fornecimento.relacaomateriaprima",
                        verbose_name="TB050 (opcional)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ei_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "close_estoqueintermediario",
                        "Pode fechar item do Estoque Intermediário",
                    ),
                    (
                        "export_estoqueintermediario",
                        "Pode exportar Estoque Intermediário",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="estoqueintermediario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "EM_FABRICA")),
                fields=("op", "lote"),
                name="uniq_ei_op_lote_em_fabrica",
            ),
        ),
    ]
