# Generated by Django 4.2.16 on 2025-09-11 15:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0109_estoqueintermediario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstoqueIntermediarioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enviado",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        verbose_name="Enviado (kg)",
                    ),
                ),
                (
                    "retorno",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        verbose_name="Retorno (kg)",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="estoqueintermediario",
            name="uniq_ei_op_lote_em_fabrica",
        ),
        migrations.RemoveField(
            model_name="estoqueintermediario",
            name="lote",
        ),
        migrations.RemoveField(
            model_name="estoqueintermediario",
            name="tb050",
        ),
        migrations.AlterField(
            model_name="estoqueintermediario",
            name="data_envio",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="estoqueintermediario",
            name="enviado",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                verbose_name="Total enviado (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="estoqueintermediario",
            name="retorno",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                verbose_name="Total retorno (kg)",
            ),
        ),
        migrations.AddField(
            model_name="estoqueintermediarioitem",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ei_itens",
                to="qualidade_fornecimento.rolomateriaprima",
                verbose_name="Lote / Rolo",
            ),
        ),
        migrations.AddField(
            model_name="estoqueintermediarioitem",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="qualidade_fornecimento.estoqueintermediario",
                verbose_name="Envio",
            ),
        ),
        migrations.AddField(
            model_name="estoqueintermediarioitem",
            name="tb050",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ei_itens",
                to="qualidade_fornecimento.relacaomateriaprima",
                verbose_name="TB050 (opcional)",
            ),
        ),
        migrations.AddConstraint(
            model_name="estoqueintermediarioitem",
            constraint=models.UniqueConstraint(
                fields=("parent", "lote"), name="uniq_eiitem_parent_lote"
            ),
        ),
    ]
