# Generated by Django 4.2.16 on 2025-09-11 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0110_estoqueintermediarioitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estoqueintermediarioitem",
            name="refugo",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                verbose_name="Refugo (kg)",
            ),
        ),
        migrations.AddField(
            model_name="estoqueintermediarioitem",
            name="sucata",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                verbose_name="Sucata (kg)",
            ),
        ),
    ]
