# Generated by Django 4.2.16 on 2025-09-12 13:42

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0111_estoqueintermediarioitem_refugo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estoqueintermediario",
            name="linha",
        ),
        migrations.RemoveField(
            model_name="estoqueintermediario",
            name="setor",
        ),
        migrations.RemoveField(
            model_name="estoqueintermediario",
            name="turno",
        ),
        migrations.AddConstraint(
            model_name="estoqueintermediario",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("op"),
                condition=models.Q(("status__in", ("EM_FABRICA", "RETORNADO"))),
                name="uniq_ei_op_em_fabrica_ou_retornado_ci",
            ),
        ),
    ]
