# fly.toml app configuration file generated for rh-qualidade on 2024-10-30T10:16:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rh-qualidade'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[deploy]
    release_command = "sh -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput'"


[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
