# Generated by Django 5.1.2 on 2024-12-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Funcionario", "0089_alter_funcionario_formulario_f146"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("numero_serie", models.CharField(max_length=100, unique=True)),
                (
                    "tipo_instrumento",
                    models.CharField(
                        choices=[
                            ("durometro", "Durômetro"),
                            ("escala_graduada", "Escala Graduada"),
                            ("goniometro", "Goniômetro"),
                            ("maq_tridimensional", "Máquina Tridimensional"),
                            ("microdurometro", "Microdurômetro"),
                            ("micrometro", "Micrômetro"),
                            ("micrometro_digital", "Micrômetro Digital"),
                            ("paquimetro_analogico", "Paquímetro Analógico"),
                            ("paquimetro_digital", "Paquímetro Digital"),
                            ("projetor_perfil", "Projetor de Perfil"),
                            ("relogio_apalpador", "Relógio Apalpador"),
                            ("relogio_comparador", "Relógio Comparador"),
                            ("temporizador_analogico", "Temporizador Analógico"),
                            ("temporizador_digital", "Temporizador Digital"),
                            ("termohigrometro_digital", "Termohigrômetro Digital"),
                            ("tracador_altura", "Traçador de Altura"),
                            ("trena", "Trena"),
                        ],
                        max_length=50,
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("fabricante", models.CharField(max_length=100)),
                (
                    "capacidade_minima",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "capacidade_maxima",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("mm", "Milímetros"),
                            ("cm", "Centímetros"),
                            ("graus", "Graus"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "resolucao",
                    models.DecimalField(
                        decimal_places=3, help_text="Resolução em mm", max_digits=10
                    ),
                ),
                (
                    "foto_equipamento",
                    models.ImageField(blank=True, null=True, upload_to="equipamentos/"),
                ),
                (
                    "frequencia_calibracao",
                    models.PositiveIntegerField(
                        help_text="Frequência de calibração em meses"
                    ),
                ),
                ("proprietario", models.CharField(max_length=100)),
                ("localizacao", models.CharField(max_length=100)),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
