# Generated by Django 4.2.16 on 2025-07-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Funcionario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código do Dispositivo"
                    ),
                ),
                ("qtde", models.PositiveIntegerField(verbose_name="Quantidade")),
                ("cliente", models.CharField(max_length=100, verbose_name="Cliente")),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "estudo_realizado",
                    models.CharField(
                        choices=[
                            (
                                "POR ATRIBUTO (MÉTODO CURTO)",
                                "Por Atributo (Método Curto)",
                            ),
                            ("NÃO PASSA", "Não Passa"),
                            (
                                "CALIBRAÇÃO PELO CLIENTE",
                                "Calibração é realizada pelo cliente",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Estudo Realizado",
                    ),
                ),
                (
                    "data_ultima_calibracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Última Calibração"
                    ),
                ),
                (
                    "frequencia_calibracao",
                    models.PositiveIntegerField(
                        verbose_name="Frequência de Calibração (em meses)"
                    ),
                ),
                (
                    "local_armazenagem",
                    models.CharField(
                        max_length=100, verbose_name="Local de Armazenagem"
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("mm", "Milímetros"),
                            ("cm", "Centímetros"),
                            ("m", "Metros"),
                            ("kg", "Quilogramas"),
                            ("°C", "Graus Celsius"),
                            ("%", "Percentual"),
                            ("Ø", "Diâmetro"),
                            ("°", "Graus"),
                        ],
                        max_length=10,
                        verbose_name="Unidade de Medida",
                    ),
                ),
                (
                    "desenho_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dispositivos/desenhos/",
                        verbose_name="Desenho do Dispositivo",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alteracao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Última Alteração"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TabelaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código do Equipamento"
                    ),
                ),
                (
                    "nome_equipamento",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Equipamento"
                    ),
                ),
                (
                    "capacidade_minima",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Capacidade de Medição Mínima",
                    ),
                ),
                (
                    "capacidade_maxima",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Capacidade de Medição Máxima",
                    ),
                ),
                (
                    "tolerancia_em_percentual",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tolerância em (%)"
                    ),
                ),
                (
                    "resolucao",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Resolução"
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("mm", "Milímetros"),
                            ("kg.cm", "Kilograma-centímetro"),
                            ("kgf", "Kilograma-força"),
                            ("°C", "Graus Celsius"),
                            ("°", "Graus"),
                            ("UR", "Unidade Relativa"),
                            ("HRC", "HRC"),
                            ("HRB", "HRB"),
                            ("HV", "Dureza Vickers"),
                            ("mN", "MiliNewton"),
                            ("%", "Percentual"),
                            ("kg", "Kilograma"),
                            ("min", "Minutos"),
                            ("s", "Segundos"),
                            ("h", "Horas"),
                        ],
                        max_length=10,
                        verbose_name="Unidade de Medida",
                    ),
                ),
                (
                    "tolerancia_total_minima",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Tolerância Total Mínima da Medida a Ser Realizada",
                    ),
                ),
                (
                    "frequencia_calibracao",
                    models.PositiveIntegerField(
                        verbose_name="Frequência de Calibração (meses)"
                    ),
                ),
                (
                    "exatidao_requerida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Exatidão Requerida",
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Número de Série"
                    ),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "fabricante",
                    models.CharField(max_length=100, verbose_name="Fabricante"),
                ),
                (
                    "foto_equipamento",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipamentos/",
                        verbose_name="Foto do Equipamento",
                    ),
                ),
                (
                    "proprietario",
                    models.CharField(max_length=100, verbose_name="Proprietário"),
                ),
                (
                    "localizacao",
                    models.CharField(max_length=100, verbose_name="Localização"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_ultima_calibracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Última Calibração"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        default="nao",
                        max_length=3,
                        verbose_name="Equipamento por Faixa",
                    ),
                ),
                (
                    "faixa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Faixa (%)",
                    ),
                ),
                (
                    "tipo_avaliacao",
                    models.CharField(
                        choices=[
                            ("dureza", "Dureza"),
                            ("carga", "Carga"),
                            ("dimensional", "Dimensional"),
                            ("temperatura", "Temperatura"),
                            ("tempo", "Tempo"),
                            ("massa", "Massa"),
                        ],
                        default="deslocamento",
                        max_length=20,
                        verbose_name="Tipo de Avaliação",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alteracao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Última Alteração"
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Funcionario.funcionario",
                        verbose_name="Responsável",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número da Cota")),
                (
                    "valor_minimo",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Valor Mínimo"
                    ),
                ),
                (
                    "valor_maximo",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Valor Máximo"
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotas",
                        to="metrologia.dispositivo",
                        verbose_name="Dispositivo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControleEntradaSaida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimentacao",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=10,
                        verbose_name="Tipo de Movimentação",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "data_movimentacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Movimentação"
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Setor"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("OK", "Ok"), ("NOK", "Nok")],
                        max_length=3,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funcionario.funcionario",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controle_entrada_saida",
                        to="metrologia.dispositivo",
                        verbose_name="Código do Dispositivo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalibracaoDispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=10,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                ("data_afericao", models.DateField(verbose_name="Data da Aferição")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "codigo_dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibracoes",
                        to="metrologia.dispositivo",
                        verbose_name="Código do Dispositivo",
                    ),
                ),
                (
                    "instrumento_utilizado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibracoes_utilizadas",
                        to="metrologia.tabelatecnica",
                        verbose_name="Instrumento Utilizado",
                    ),
                ),
                (
                    "nome_responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibracoes_realizadas",
                        to="Funcionario.funcionario",
                        verbose_name="Nome do Responsável",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laboratorio",
                    models.CharField(
                        choices=[
                            ("Ceime", "Ceime"),
                            ("Instemaq", "Instemaq"),
                            ("Microoptica", "Microoptica"),
                            ("Trescal", "Trescal"),
                            ("Embracal", "Embracal"),
                            ("Kratos", "Kratos"),
                            ("Tecmetro", "Tecmetro"),
                        ],
                        max_length=100,
                        verbose_name="Laboratório",
                    ),
                ),
                (
                    "numero_certificado",
                    models.CharField(
                        max_length=100, verbose_name="Número do Certificado"
                    ),
                ),
                (
                    "erro_equipamento",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Erro do Equipamento (E)",
                    ),
                ),
                (
                    "incerteza",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Incerteza (I)"
                    ),
                ),
                (
                    "data_calibracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Calibração"
                    ),
                ),
                (
                    "certificado_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="calibracoes/",
                        verbose_name="Certificado de Calibração",
                    ),
                ),
                (
                    "l",
                    models.DecimalField(
                        decimal_places=3,
                        editable=False,
                        max_digits=10,
                        verbose_name="L",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "codigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrologia.tabelatecnica",
                        verbose_name="Código do Equipamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Afericao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor da Aferição",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "calibracao_dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afericoes",
                        to="metrologia.calibracaodispositivo",
                    ),
                ),
                (
                    "cota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afericoes",
                        to="metrologia.cota",
                    ),
                ),
            ],
        ),
    ]
