# Generated by Django 5.1.2 on 2024-12-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrologia",
            "0002_tabelatecnica_remove_equipamentos_capacidade_maxima_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelatecnica",
            name="exatidao_requerida",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Exatidão Requerida",
            ),
        ),
    ]
