# Generated by Django 5.1.2 on 2024-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0004_remove_tabelatecnica_observacoes_capacidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelatecnica",
            name="exatidao_requerida",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=10,
                null=True,
                verbose_name="Exatidão Requerida",
            ),
        ),
    ]
