# Generated by Django 5.1.2 on 2024-12-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0005_alter_tabelatecnica_exatidao_requerida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelatecnica",
            name="tolerancia_total_minima",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=10,
                verbose_name="Tolerância Total Mínima da Medida a Ser Realizada",
            ),
        ),
    ]
