# Generated by Django 5.1.2 on 2024-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0006_alter_tabelatecnica_tolerancia_total_minima"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelatecnica",
            name="capacidade_maxima",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=10,
                verbose_name="Capacidade de Medição Máxima",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="capacidade_minima",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=10,
                verbose_name="Capacidade de Medição Mínima",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="resolucao",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Resolução"
            ),
        ),
    ]
