# Generated by Django 5.1.2 on 2024-12-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0007_alter_tabelatecnica_capacidade_maxima_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelatecnica",
            name="capacidade_maxima",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                verbose_name="Capacidade de Medição Máxima",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="capacidade_minima",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                verbose_name="Capacidade de Medição Mínima",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="exatidao_requerida",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Exatidão Requerida",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="resolucao",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="Resolução"
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="tolerancia_total_minima",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                verbose_name="Tolerância Total Mínima da Medida a Ser Realizada",
            ),
        ),
    ]
