# Generated by Django 5.1.2 on 2024-12-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0089_alter_funcionario_formulario_f146"),
        ("metrologia", "0008_alter_tabelatecnica_capacidade_maxima_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelatecnica",
            name="fabricante",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Fabricante"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="foto_equipamento",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="equipamentos/",
                verbose_name="Foto do Equipamento",
            ),
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="localizacao",
            field=models.CharField(
                default="Desconhecido", max_length=100, verbose_name="Localização"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="modelo",
            field=models.CharField(default=1, max_length=100, verbose_name="Modelo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="numero_serie",
            field=models.CharField(
                default="Modelo Padrão",
                max_length=100,
                unique=True,
                verbose_name="Número de Série",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="proprietario",
            field=models.CharField(
                default="000000", max_length=100, verbose_name="Proprietário"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Funcionario.funcionario",
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="status",
            field=models.CharField(
                choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                default="ativo",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
