# Generated by Django 5.1.2 on 2024-12-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0009_tabelatecnica_fabricante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelatecnica",
            name="data_ultima_calibracao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Última Calibração"
            ),
        ),
    ]
