# Generated by Django 5.1.2 on 2024-12-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0010_tabelatecnica_data_ultima_calibracao"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Equipamentos",
        ),
    ]
