# Generated by Django 5.1.2 on 2024-12-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0011_delete_equipamentos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laboratorio",
                    models.CharField(max_length=100, verbose_name="Laboratório"),
                ),
                (
                    "numero_certificado",
                    models.CharField(
                        max_length=100, verbose_name="Número do Certificado"
                    ),
                ),
                (
                    "erro_equipamento",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Erro do Equipamento (E)",
                    ),
                ),
                (
                    "incerteza",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Incerteza (I)"
                    ),
                ),
                (
                    "data_calibracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Calibração"
                    ),
                ),
                (
                    "l",
                    models.DecimalField(
                        decimal_places=4,
                        editable=False,
                        max_digits=10,
                        verbose_name="L",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "codigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrologia.tabelatecnica",
                        verbose_name="Código do Equipamento",
                    ),
                ),
            ],
        ),
    ]
