# Generated by Django 5.1.2 on 2024-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0012_calibracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracao",
            name="certificado_anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="calibracoes/",
                verbose_name="Certificado de Calibração",
            ),
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="faixa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Faixa (%)",
            ),
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="tipo",
            field=models.CharField(
                choices=[("sim", "Sim"), ("nao", "Não")],
                default="nao",
                max_length=3,
                verbose_name="Equipamento por Faixa",
            ),
        ),
    ]
