# Generated by Django 5.1.2 on 2024-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0014_tabelatecnica_tipo_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="erro_equipamento",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="Erro do Equipamento (E)"
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="incerteza",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="Incerteza (I)"
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="l",
            field=models.DecimalField(
                decimal_places=3, editable=False, max_digits=10, verbose_name="L"
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="laboratorio",
            field=models.CharField(
                choices=[
                    ("Ceime", "Ceime"),
                    ("Instemaq", "Instemaq"),
                    ("Microoptica", "Microoptica"),
                    ("Trescal", "Trescal"),
                    ("Embracal", "Embracal"),
                    ("Kratos", "Kratos"),
                    ("Tecmetro", "Tecmetro"),
                ],
                max_length=100,
                verbose_name="Laboratório",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="capacidade_maxima",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                verbose_name="Capacidade de Medição Máxima",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="capacidade_minima",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                verbose_name="Capacidade de Medição Mínima",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="exatidao_requerida",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Exatidão Requerida",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="tipo_avaliacao",
            field=models.CharField(
                choices=[
                    ("dureza", "Dureza"),
                    ("carga", "Carga"),
                    ("dimensional", "Dimensional"),
                    ("temperatura", "Temperatura"),
                    ("tempo", "Tempo"),
                    ("massa", "Massa"),
                ],
                default="deslocamento",
                max_length=20,
                verbose_name="Tipo de Avaliação",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatecnica",
            name="unidade_medida",
            field=models.CharField(
                choices=[
                    ("mm", "Milímetros"),
                    ("kg.cm", "Kilograma-centímetro"),
                    ("kgf", "Kilograma-força"),
                    ("°C", "Graus Celsius"),
                    ("°", "Graus"),
                    ("UR", "Unidade Relativa"),
                    ("HRC", "HRC"),
                    ("HRB", "HRB"),
                    ("%", "Percentual"),
                    ("kg", "Kilograma"),
                ],
                max_length=10,
                verbose_name="Unidade de Medida",
            ),
        ),
    ]
