# Generated by Django 5.1.2 on 2024-12-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0097_funcionario_assinatura_eletronica"),
        ("metrologia", "0015_alter_calibracao_erro_equipamento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código do Dispositivo"
                    ),
                ),
                ("qtde", models.PositiveIntegerField(verbose_name="Quantidade")),
                ("cliente", models.CharField(max_length=100, verbose_name="Cliente")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "estudo_realizado",
                    models.CharField(
                        choices=[
                            (
                                "POR ATRIBUTO (MÉTODO CURTO)",
                                "Por Atributo (Método Curto)",
                            ),
                            ("NÃO PASSA", "Não Passa"),
                            (
                                "CALIBRAÇÃO PELO CLIENTE",
                                "Calibração é realizada pelo cliente",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Estudo Realizado",
                    ),
                ),
                (
                    "data_ultima_calibracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Última Calibração"
                    ),
                ),
                (
                    "frequencia_calibracao",
                    models.PositiveIntegerField(
                        verbose_name="Frequência de Calibração (em meses)"
                    ),
                ),
                (
                    "local_armazenagem",
                    models.CharField(
                        max_length=100, verbose_name="Local de Armazenagem"
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("mm", "Milímetros"),
                            ("cm", "Centímetros"),
                            ("m", "Metros"),
                            ("kg", "Quilogramas"),
                            ("°C", "Graus Celsius"),
                            ("%", "Percentual"),
                            ("Ø", "Diâmetro"),
                        ],
                        max_length=10,
                        verbose_name="Unidade de Medida",
                    ),
                ),
                (
                    "desenho_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dispositivos/desenhos/",
                        verbose_name="Desenho do Dispositivo",
                    ),
                ),
                (
                    "instrumento_medicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metrologia.tabelatecnica",
                        verbose_name="Instrumento de Medição",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número da Cota")),
                (
                    "valor_minimo",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Valor Mínimo"
                    ),
                ),
                (
                    "valor_maximo",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Valor Máximo"
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotas",
                        to="metrologia.dispositivo",
                        verbose_name="Dispositivo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControleEntradaSaida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_retirada", models.DateField(verbose_name="Data da Retirada")),
                (
                    "data_retorno",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Retorno"
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("FABRIL", "Fabril"),
                            ("MANUTENÇÃO", "Manutenção"),
                        ],
                        max_length=100,
                        verbose_name="Setor",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("OK", "Ok"), ("NOK", "Nok")],
                        max_length=3,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funcionario.funcionario",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controle_entrada_saida",
                        to="metrologia.dispositivo",
                        verbose_name="Código do Dispositivo",
                    ),
                ),
            ],
        ),
    ]
