# Generated by Django 5.1.2 on 2024-12-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0016_dispositivo_cota_controleentradasaida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispositivo",
            name="instrumento_medicao",
        ),
    ]
