# Generated by Django 5.1.2 on 2024-12-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0017_remove_dispositivo_instrumento_medicao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controleentradasaida",
            name="observacoes",
        ),
        migrations.AddField(
            model_name="controleentradasaida",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
        migrations.AddField(
            model_name="controleentradasaida",
            name="quantidade",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
        ),
        migrations.AddField(
            model_name="controleentradasaida",
            name="tipo_movimentacao",
            field=models.CharField(
                choices=[("entrada", "Entrada"), ("saida", "Saída")],
                default=1,
                max_length=10,
                verbose_name="Tipo de Movimentação",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dispositivo",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição"),
        ),
    ]
