# Generated by Django 5.1.2 on 2024-12-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0018_remove_controleentradasaida_observacoes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controleentradasaida",
            name="data_retirada",
        ),
        migrations.RemoveField(
            model_name="controleentradasaida",
            name="data_retorno",
        ),
        migrations.AddField(
            model_name="controleentradasaida",
            name="data_movimentacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Movimentação"
            ),
        ),
    ]
