# Generated by Django 5.1.2 on 2024-12-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0097_funcionario_assinatura_eletronica"),
        ("metrologia", "0019_remove_controleentradasaida_data_retirada_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibracaoDispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_peca",
                    models.CharField(
                        help_text="Referente ao campo código do modelo de dados Dispositivo sem os últimos 2 caracteres.",
                        max_length=50,
                        verbose_name="Código da Peça",
                    ),
                ),
                (
                    "instrumento_medicao",
                    models.CharField(
                        help_text="Referente ao campo nome_equipamento do modelo de dados TabelaTecnica.",
                        max_length=100,
                        verbose_name="Instrumento de Medição",
                    ),
                ),
                (
                    "afericao",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Aferição"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("data_afericao", models.DateField(verbose_name="Data da Aferição")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "codigo_dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibracoes",
                        to="metrologia.dispositivo",
                        verbose_name="Código do Dispositivo",
                    ),
                ),
                (
                    "instrumento_utilizado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibracoes_utilizadas",
                        to="metrologia.tabelatecnica",
                        verbose_name="Instrumento Utilizado",
                    ),
                ),
                (
                    "nome_responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibracoes_realizadas",
                        to="Funcionario.funcionario",
                        verbose_name="Nome do Responsável",
                    ),
                ),
            ],
        ),
    ]
