# Generated by Django 5.1.2 on 2024-12-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0020_calibracaodispositivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Afericao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=20,
                    ),
                ),
                (
                    "calibracao_dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afericoes",
                        to="metrologia.calibracaodispositivo",
                    ),
                ),
            ],
        ),
    ]
