# Generated by Django 5.1.2 on 2024-12-19 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0021_afericao"),
    ]

    operations = [
        migrations.AddField(
            model_name="afericao",
            name="cota",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="afericoes",
                to="metrologia.cota",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="afericao",
            name="status",
            field=models.CharField(
                choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="afericao",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor da Aferição"
            ),
        ),
    ]
