# Generated by Django 5.1.2 on 2024-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0022_afericao_cota_alter_afericao_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="afericao",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
