# Generated by Django 4.2.16 on 2025-01-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0025_alter_cota_valor_maximo_alter_cota_valor_minimo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibracaodispositivo",
            name="codigo_peca",
        ),
    ]
