# Generated by Django 4.2.16 on 2025-01-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0026_remove_calibracaodispositivo_codigo_peca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleentradasaida",
            name="setor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Setor"
            ),
        ),
    ]
