# Generated by Django 4.2.16 on 2025-01-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0027_alter_controleentradasaida_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
