# Generated by Django 4.2.16 on 2025-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0028_dispositivo_updated_at_tabelatecnica_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivo",
            name="alteracao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Última Alteração"
            ),
        ),
        migrations.AddField(
            model_name="tabelatecnica",
            name="alteracao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Última Alteração"
            ),
        ),
    ]
