# Generated by Django 4.2.16 on 2025-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0029_dispositivo_alteracao_tabelatecnica_alteracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelatecnica",
            name="unidade_medida",
            field=models.CharField(
                choices=[
                    ("mm", "Milímetros"),
                    ("kg.cm", "Kilograma-centímetro"),
                    ("kgf", "Kilograma-força"),
                    ("°C", "Graus Celsius"),
                    ("°", "Graus"),
                    ("UR", "Unidade Relativa"),
                    ("HRC", "HRC"),
                    ("HRB", "HRB"),
                    ("HV", "Dureza Vickers"),
                    ("mN", "MiliNewton"),
                    ("%", "Percentual"),
                    ("kg", "Kilograma"),
                    ("min", "Minutos"),
                    ("s", "Segundos"),
                    ("h", "Horas"),
                ],
                max_length=10,
                verbose_name="Unidade de Medida",
            ),
        ),
    ]
