# Generated by Django 4.2.19 on 2025-02-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0030_alter_tabelatecnica_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelatecnica',
            name='unidade_medida',
            field=models.CharField(choices=[('mm', 'Milímetros'), ('kg.cm', 'Kilograma-centímetro'), ('kgf', 'Kilograma-força'), ('°C', 'Graus Celsius'), ('°', 'Graus'), ('UR', 'Unidade Relativa'), ('HRC', 'HRC'), ('HRB', 'HRB'), ('HV', 'Dureza Vickers'), ('mN', 'MiliNewton'), ('%', 'Percentual'), ('kg', 'Kilograma'), ('min', 'Minutos'), ('s', 'Segundos'), ('h', 'Horas')], max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
