# Generated by Django 4.2.16 on 2025-08-01 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrologia", "0032_alter_dispositivo_unidade_medida"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnaliseCriticaMetrologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao_equipamento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Descrição do Equipamento",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=100, verbose_name="Modelo"),
                ),
                (
                    "capacidade_medicao",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Capacidade de Medição / Resolução",
                    ),
                ),
                (
                    "data_ultima_calibracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Última Calibração"
                    ),
                ),
                (
                    "nao_conformidade_detectada",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Não Conformidade Detectada"
                    ),
                ),
                (
                    "compromete_qualidade",
                    models.BooleanField(
                        default=False,
                        verbose_name="A não conformidade compromete a qualidade dos produtos?",
                    ),
                ),
                (
                    "observacoes_qualidade",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Observações (Qualidade)"
                    ),
                ),
                (
                    "verificar_pecas_processo",
                    models.BooleanField(
                        default=False,
                        verbose_name="Há necessidade de verificar as peças em processo e estoque?",
                    ),
                ),
                (
                    "observacoes_pecas",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        null=True,
                        verbose_name="Observações (Peças/Estoque)",
                    ),
                ),
                (
                    "comunicar_cliente",
                    models.BooleanField(
                        default=False,
                        verbose_name="Há necessidade de comunicar o cliente?",
                    ),
                ),
                (
                    "observacoes_cliente",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Observações (Cliente)"
                    ),
                ),
                ("assinado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da assinatura"
                    ),
                ),
                (
                    "assinatura_nome",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nome da assinatura",
                    ),
                ),
                (
                    "assinatura_cn",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="CN da assinatura (email)",
                    ),
                ),
                (
                    "equipamento_dispositivo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metrologia.dispositivo",
                        verbose_name="Equipamento (Dispositivo)",
                    ),
                ),
                (
                    "equipamento_instrumento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metrologia.tabelatecnica",
                        verbose_name="Equipamento (Instrumento)",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise Crítica da Metrologia",
                "verbose_name_plural": "Análises Críticas da Metrologia",
            },
        ),
    ]
