# Generated by Django 4.2.16 on 2025-08-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0033_analisecriticametrologia"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisecriticametrologia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("instrumento", "Instrumento"),
                    ("dispositivo", "Dispositivo"),
                ],
                default="instrumento",
                max_length=12,
                verbose_name="Tipo",
            ),
        ),
    ]
