# Generated by Django 4.2.16 on 2025-08-13 10:42

from django.db import migrations, models
import metrologia.models.models_calibracao_dispositivo


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0034_analisecriticametrologia_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracaodispositivo",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=metrologia.models.models_calibracao_dispositivo.renomear_anexo_calibracao,
                validators=[
                    metrologia.models.models_calibracao_dispositivo.MaxFileSizeValidator(
                        5
                    )
                ],
                verbose_name="Anexo",
            ),
        ),
    ]
