# Generated by Django 4.2.16 on 2025-08-13 10:59

from django.db import migrations, models
import metrologia.models.models_calibracao


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0035_calibracaodispositivo_anexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="certificado_anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=metrologia.models.models_calibracao.renomear_certificado_calibracao,
                validators=[
                    metrologia.models.models_calibracao.MaxFileSizeValidator(5)
                ],
                verbose_name="Certificado de Calibração",
            ),
        ),
    ]
