# Generated by Django 4.2.16 on 2025-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0036_alter_calibracao_certificado_anexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracaodispositivo",
            name="calibracao_cliente",
            field=models.BooleanField(
                default=False, verbose_name="Calibração feita pelo cliente"
            ),
        ),
    ]
