# Generated by Django 4.2.16 on 2025-08-18 12:32

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("metrologia", "0037_calibracaodispositivo_calibracao_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracaodispositivo",
            name="observacoes",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações gerais da calibração"
            ),
        ),
    ]
