# Funcionario/choices.py

DEPARTAMENTOS_EMPRESA = [
    ("RH", "Recursos Humanos"),
    ("QUALIDADE", "Gestão da Qualidade"),
    ("CONTROLE", "Controle de Qualidade"),
    ("PRODUCAO", "Produção"),
    ("COMPRAS", "Compras"),
    ("COMERCIAL", "Comercial"),
    ("DIRETORIA", "Diretoria"),
    ("PCP", "Logistica/PCP"),
    ("LIMPEZA", "Serviços Gerais"),
    ("TÉCNICO", "Técnico"),
    ("TI", "Técnologia da Informação"),
    ("ALMOXARIFADO", "Almoxarifado"),
    ("EXPEDICAO", "Expedição"),
    ("MANUTENÇÃO", "Manutenção"),
    ("COMPRESSAO", "Compressão"),
    ("RETIFICA", "Retífica"),
    ("TORSÃO", "Torção"),
    ("ESTAMPARIA_BIHLER", "Estamparia Bihler"),
    ("ACABAMENTO", "Acabamento"),
    ("PRENSA", "Prensa"),
    ("DOBRADEIRA_CNC", "Dobradeira CNC"),
    ("ALIVIO_TENSAO_TECNICO", "Alívio de Tensão Técnico"),
    ("FERRAMENTARIA", "Ferramentaria"),
    ("PORTARIA", "Portaria"),
    ("FINANCEIRO", "Financeiro"),
]
