# Generated by Django 4.2.16 on 2025-06-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razao_social", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=18)),
                ("ie", models.CharField(blank=True, max_length=50, null=True)),
                ("endereco", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=9)),
                ("uf", models.CharField(max_length=2)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "logotipo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos_clientes/"
                    ),
                ),
                ("transportadora_razao_social", models.CharField(max_length=255)),
                ("transportadora_cnpj", models.CharField(max_length=18)),
                (
                    "transportadora_ie",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("transportadora_endereco", models.CharField(max_length=255)),
                ("transportadora_numero", models.CharField(max_length=10)),
                (
                    "transportadora_complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("transportadora_bairro", models.CharField(max_length=100)),
                ("transportadora_cidade", models.CharField(max_length=100)),
                ("transportadora_cep", models.CharField(max_length=9)),
                ("transportadora_uf", models.CharField(max_length=2)),
                (
                    "transportadora_telefone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("coleta", models.BooleanField(default=False)),
                ("icms", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ipi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cfop", models.CharField(max_length=10)),
                ("cond_pagamento", models.CharField(max_length=100)),
                ("cod_bm", models.CharField(max_length=50)),
                ("observacao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
