# Generated by Django 4.2.16 on 2025-06-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0002_item_cliente_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Cartao IPI", "Cartão IPI"),
                            ("Alteracao de CNPJ", "Alteração de CNPJ"),
                            ("Outros", "Outros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos_clientes/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="comercial.cliente",
                    ),
                ),
            ],
        ),
    ]
