# Generated by Django 4.2.16 on 2025-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="coleta",
            field=models.BooleanField(default=False, verbose_name="Coleta"),
        ),
    ]
