# Generated by Django 4.2.16 on 2025-06-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0003_clientedocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="transportadora_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
