# Generated by Django 4.2.16 on 2025-08-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0003_alter_ordemdesenvolvimento_familia_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precalculoservicoexterno",
            name="peso_bruto_total",
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="peso_liquido_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=20,
                null=True,
                verbose_name="Peso Líquido Total (kg)",
            ),
        ),
    ]
