# Generated by Django 4.2.16 on 2025-08-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0100_inspecao10_setor"),
        ("comercial", "0004_remove_precalculoservicoexterno_peso_bruto_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="fontes_homologadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="itens_homologados",
                to="qualidade_fornecimento.fornecedorqualificado",
                verbose_name="Fontes Homologadas",
            ),
        ),
    ]
