# Generated by Django 4.2.16 on 2025-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0004_cliente_transportadora_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
