# Generated by Django 4.2.16 on 2025-06-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0005_cliente_atualizado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cargo_contato",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="email_contato",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="nome_contato",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone_contato",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Automotivo", "Automotivo"),
                    ("Não Automotivo", "Não Automotivo"),
                    ("Reposição", "Reposição"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
