# Generated by Django 4.2.16 on 2025-08-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0005_item_fontes_homologadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tipo_de_peca",
            field=models.CharField(
                choices=[
                    ("Mola", "Mola"),
                    ("Estampado", "Estampado"),
                    ("Aramado", "Aramado"),
                ],
                default="Mola",
                max_length=20,
                verbose_name="Tipo de Peça",
            ),
        ),
        migrations.AlterField(
            model_name="clientedocumento",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cartao CNPJ", "Cartão CNPJ"),
                    (
                        "Cartao de Inscrição Estadual/Municipal",
                        "Cartao de Inscrição Estadual/Municipal",
                    ),
                    ("Carta IPI", "Carta IPI"),
                    ("Ficha Cadastral", "Ficha Cadastral"),
                    ("Cartão Suframa", "Cartão Suframa"),
                    ("Outros", "Outros"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
