# Generated by Django 4.2.16 on 2025-06-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0006_cliente_cargo_contato_cliente_email_contato_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ferramenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "vida_util_em_pecas",
                    models.PositiveIntegerField(verbose_name="Vida útil (em peças)"),
                ),
                (
                    "desenho_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="ferramentas/desenhos/"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Nova", "Ferramenta Nova"),
                            ("Adpt", "Adaptação"),
                            ("Disp", "Dispositivo"),
                            ("Outro", "Outros"),
                        ],
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServicoFerramenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Eletroerosao", "Eletro erosão"),
                            ("Rolamento", "Rolamento"),
                            ("Rolete", "Rolete"),
                            ("Taxa", "Taxa Administrativa"),
                            ("Tratamento", "Tratamento térmico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ferramenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos",
                        to="comercial.ferramenta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialFerramenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_material", models.CharField(max_length=100)),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[("Kg", "Kg"), ("Pc", "Peça"), ("Un", "Unidade")],
                        max_length=2,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ferramenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="comercial.ferramenta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaoDeObraFerramenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Ferramentaria", "Ferramentaria"),
                            ("Projeto", "Projeto"),
                            ("Externa", "MO Externa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("horas", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_hora", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ferramenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mao_obra",
                        to="comercial.ferramenta",
                    ),
                ),
            ],
        ),
    ]
