# Generated by Django 4.2.16 on 2025-08-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0006_item_tipo_de_peca_alter_clientedocumento_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientedocumento",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cartao CNPJ", "Cartão CNPJ"),
                    (
                        "Cartao de Inscrição Estadual/Municipal",
                        "Cartao de Inscrição Estadual/Municipal",
                    ),
                    ("Carta IPI", "Carta IPI"),
                    ("Ficha Cadastral", "Ficha Cadastral"),
                    ("Cartão Suframa", "Cartão Suframa"),
                    ("Norma", "Normas"),
                    ("Outros", "Outros"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
