# Generated by Django 4.2.16 on 2025-08-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0007_alter_clientedocumento_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotacaoferramenta",
            name="valor_utilizado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor utilizado na cotação (R$)",
            ),
        ),
    ]
