# Generated by Django 4.2.16 on 2025-06-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0007_ferramenta_servicoferramenta_materialferramenta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferramenta",
            name="proprietario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ferramentas",
                to="comercial.cliente",
            ),
        ),
    ]
