# Generated by Django 4.2.16 on 2025-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0008_ferramenta_proprietario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maodeobraferramenta",
            name="valor_hora",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="materialferramenta",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicoferramenta",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
