# Generated by Django 4.2.16 on 2025-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0008_cotacaoferramenta_valor_utilizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculomaterial",
            name="compras_solicitado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="compras_solicitado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
