# Generated by Django 4.2.16 on 2025-08-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0009_precalculomaterial_compras_solicitado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="lote_minimo",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Lote Mínimo (kg ou R$)",
            ),
        ),
    ]
