# Generated by Django 4.2.16 on 2025-06-17 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0009_alter_maodeobraferramenta_valor_hora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferramenta",
            name="cotacao_enviada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="token_cotacao",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
