# Generated by Django 4.2.16 on 2025-08-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0010_alter_precalculoservicoexterno_lote_minimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="lote_minimo",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Lote Mínimo"
            ),
        ),
    ]
