# Generated by Django 4.2.16 on 2025-06-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0156_funcionario_tipo"),
        ("comercial", "0010_ferramenta_cotacao_enviada_em_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroDeCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custo_atual",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Custo do Setor"
                    ),
                ),
                ("vigencia", models.DateField(verbose_name="Início da Vigência")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "departamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centro_custo",
                        to="Funcionario.departamentos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["departamento"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoCustoCentroDeCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custo_anterior",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("novo_custo", models.DecimalField(decimal_places=2, max_digits=12)),
                ("alterado_em", models.DateTimeField()),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_custos",
                        to="comercial.centrodecusto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Custo",
                "verbose_name_plural": "Históricos de Custo",
                "ordering": ["-alterado_em"],
            },
        ),
    ]
