# Generated by Django 4.2.16 on 2025-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0011_alter_precalculoservicoexterno_lote_minimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculomaterial",
            name="lote_minimo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Lote Mínimo",
            ),
        ),
    ]
