# Generated by Django 4.2.16 on 2025-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0011_centrodecusto_historicocustocentrodecusto"),
    ]

    operations = [
        migrations.AddField(
            model_name="centrodecusto",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
    ]
