# Generated by Django 4.2.16 on 2025-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0012_alter_precalculomaterial_lote_minimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculomaterial",
            name="lote_minimo",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Lote Mínimo"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="lote_minimo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Lote Mínimo",
            ),
        ),
    ]
