# Generated by Django 4.2.16 on 2025-06-17 14:07

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0012_centrodecusto_observacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["cliente", "codigo"]},
        ),
        migrations.AddField(
            model_name="item",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="item",
            name="automotivo_oem",
            field=models.BooleanField(default=False, verbose_name="Automotivo OEM"),
        ),
        migrations.AddField(
            model_name="item",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="comercial.cliente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="codigo_cliente",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código no Cliente"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="data_revisao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Revisão"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="descricao_cliente",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Descrição no Cliente",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="desenho",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="itens/desenhos/",
                verbose_name="Desenho",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ferramenta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens",
                to="comercial.ferramenta",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_seguranca",
            field=models.BooleanField(
                default=False, verbose_name="É Item de Segurança?"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="lote_minimo",
            field=models.PositiveIntegerField(default=1, verbose_name="Lote Mínimo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="ncm",
            field=models.CharField(default=2, max_length=10, verbose_name="NCM"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="requisito_especifico",
            field=models.BooleanField(
                default=False, verbose_name="Requisito Específico Cliente?"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="revisao",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Revisão"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="codigo",
            field=models.CharField(max_length=50, verbose_name="Código Interno"),
        ),
        migrations.AlterField(
            model_name="item",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição"),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("cliente", "codigo")},
        ),
        migrations.RemoveField(
            model_name="item",
            name="preco_unitario",
        ),
        migrations.RemoveField(
            model_name="item",
            name="unidade",
        ),
    ]
