# Generated by Django 4.2.16 on 2025-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0013_alter_item_options_item_atualizado_em_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="ipi",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cfop",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cod_bm",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cond_pagamento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="icms",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.CharField(
                choices=[
                    ("Automotivo", "Automotivo"),
                    ("Não Automotivo", "Não Automotivo"),
                    ("Reposição", "Reposição"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="transportadora_bairro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="transportadora_cep",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="transportadora_cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="transportadora_cnpj",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="transportadora_endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="transportadora_numero",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="transportadora_razao_social",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="transportadora_uf",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="clientedocumento",
            name="arquivo",
            field=models.FileField(
                blank=True, null=True, upload_to="documentos_clientes/"
            ),
        ),
        migrations.AlterField(
            model_name="clientedocumento",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cartao IPI", "Cartão IPI"),
                    ("Alteracao de CNPJ", "Alteração de CNPJ"),
                    ("Outros", "Outros"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
