# Generated by Django 4.2.16 on 2025-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0013_alter_precalculomaterial_lote_minimo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaturamentoRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nfe",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="NF-e"
                    ),
                ),
                (
                    "ocorrencia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ocorrência"
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Cliente"
                    ),
                ),
                (
                    "valor_frete",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Frete",
                    ),
                ),
                (
                    "item_codigo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Código do Item",
                    ),
                ),
                (
                    "item_quantidade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "item_valor_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor Unitário",
                    ),
                ),
                (
                    "item_ipi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="IPI (%)",
                    ),
                ),
                (
                    "chave_unica",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Faturamento (Registro)",
                "verbose_name_plural": "Faturamento (Registros)",
                "ordering": ["-criado_em"],
            },
        ),
    ]
