# Generated by Django 4.2.16 on 2025-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0014_faturamentoregistro"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoregistro",
            name="congelado",
            field=models.BooleanField(
                default=False, verbose_name="Congelado (não atualizar via sync)"
            ),
        ),
    ]
