# Generated by Django 4.2.16 on 2025-06-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0014_remove_cliente_ipi_alter_cliente_cfop_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="coleta",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_bairro",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_cep",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_cidade",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_cnpj",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_complemento",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_email",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_endereco",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_ie",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_numero",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_razao_social",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_telefone",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="transportadora_uf",
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_cadastro",
            field=models.CharField(
                choices=[("Cliente", "Cliente"), ("Transportadora", "Transportadora")],
                default="Cliente",
                max_length=20,
            ),
        ),
    ]
