# Generated by Django 4.2.16 on 2025-08-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0015_faturamentoregistro_congelado"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoregistro",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor Total",
            ),
        ),
        migrations.AddField(
            model_name="faturamentoregistro",
            name="valor_total_com_ipi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor Total c/ IPI",
            ),
        ),
        migrations.AlterField(
            model_name="faturamentoregistro",
            name="chave_unica",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="Chave Única"
            ),
        ),
        migrations.AlterField(
            model_name="faturamentoregistro",
            name="item_quantidade",
            field=models.IntegerField(blank=True, null=True, verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="faturamentoregistro",
            name="ocorrencia",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Ocorrência (dd/mm/yyyy)",
            ),
        ),
    ]
