# Generated by Django 4.2.16 on 2025-06-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0015_remove_cliente_coleta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="transportadora",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "Transportadora"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_atendidos",
                to="comercial.cliente",
                verbose_name="Transportadora",
            ),
        ),
    ]
