# Generated by Django 4.2.16 on 2025-06-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0016_cliente_transportadora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="transportadora",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo_cadastro": "Transportadora"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_atendidos",
                to="comercial.cliente",
                verbose_name="Transportadora",
            ),
        ),
    ]
