# Generated by Django 4.2.16 on 2025-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0016_faturamentoregistro_valor_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoregistro",
            name="cliente_codigo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código do Cliente"
            ),
        ),
    ]
