# Generated by Django 4.2.16 on 2025-08-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0017_faturamentoregistro_cliente_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoregistro",
            name="tipo",
            field=models.CharField(
                choices=[("Venda", "Venda"), ("Devolução", "Devolução")],
                default="Venda",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
