# Generated by Django 4.2.16 on 2025-06-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0017_alter_cliente_transportadora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cnpj",
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
