# Generated by Django 4.2.16 on 2025-06-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0018_alter_cliente_cnpj"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="item",
            name="ipi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="IPI (%)",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="codigo",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Código Interno"
            ),
        ),
    ]
