# Generated by Django 4.2.16 on 2025-08-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0018_faturamentoregistro_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoregistro",
            name="cliente_vinculado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faturamentos",
                to="comercial.cliente",
                verbose_name="Cliente Vinculado",
            ),
        ),
    ]
