# Generated by Django 4.2.16 on 2025-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0019_faturamentoregistro_cliente_vinculado"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoregistro",
            name="perc_icms",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="ICMS (%) (NF)",
            ),
        ),
    ]
