# Generated by Django 4.2.16 on 2025-06-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0019_alter_item_unique_together_item_ipi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
