# Generated by Django 4.2.16 on 2025-06-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0020_cotacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="codigo_desenho",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código do Desenho"
            ),
        ),
    ]
