# Generated by Django 4.2.16 on 2025-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0020_faturamentoregistro_perc_icms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faturamentoregistro",
            name="ocorrencia",
            field=models.DateField(blank=True, null=True),
        ),
    ]
