# Generated by Django 4.2.16 on 2025-08-15 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0021_alter_faturamentoregistro_ocorrencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicadorcomercialregistromensal",
            name="indicador",
            field=models.CharField(
                choices=[
                    ("1.1", "Faturamento"),
                    ("4.1", "Atendimento do Prazo de Cotação"),
                    ("4.2", "Número de Itens Novos Vendidos"),
                    ("4.3", "Número de Cotações por Funcionário"),
                    ("4.4", "Taxa de Orçamentos Aprovados"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MetaFaturamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField()),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Jan"),
                            (2, "Fev"),
                            (3, "Mar"),
                            (4, "Abr"),
                            (5, "Mai"),
                            (6, "Jun"),
                            (7, "Jul"),
                            (8, "Ago"),
                            (9, "Set"),
                            (10, "Out"),
                            (11, "Nov"),
                            (12, "Dez"),
                        ]
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta de Faturamento",
                "verbose_name_plural": "Metas de Faturamento",
                "ordering": ["-ano", "mes"],
                "unique_together": {("ano", "mes")},
            },
        ),
    ]
