# Generated by Django 4.2.16 on 2025-06-20 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "comercial",
            "0022_alter_cotacao_options_remove_cotacao_data_criacao_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analisecomercial",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="analisecomercial",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="analisecomercial",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="analisecomercial",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="analisecomercial",
            name="assinado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisecomercial",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="analisecomercial",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="analisecomercial",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="analisecomercial",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="comercial.item",
                verbose_name="Selecione o item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analisecomercial",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
