# Generated by Django 4.2.16 on 2025-08-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0022_alter_indicadorcomercialregistromensal_indicador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaturamentoDuplicata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nfe",
                    models.CharField(db_index=True, max_length=50, verbose_name="NF-e"),
                ),
                (
                    "numero_parcela",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Parcela"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
                (
                    "valor_duplicata",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        verbose_name="Valor da Duplicata",
                    ),
                ),
                (
                    "cliente_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Cliente",
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Cliente (texto livre)",
                    ),
                ),
                (
                    "ocorrencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ocorrência (NF)"
                    ),
                ),
                (
                    "chave_unica",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Chave Única",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente_vinculado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicatas_faturamento",
                        to="comercial.cliente",
                        verbose_name="Cliente Vinculado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faturamento (Duplicata)",
                "verbose_name_plural": "Faturamento (Duplicatas)",
                "indexes": [
                    models.Index(
                        fields=["nfe", "data_vencimento"],
                        name="comercial_f_nfe_c15536_idx",
                    )
                ],
            },
        ),
    ]
