# Generated by Django 4.2.16 on 2025-08-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0023_faturamentoduplicata"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoduplicata",
            name="cfop",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="CFOP"
            ),
        ),
        migrations.AddField(
            model_name="faturamentoduplicata",
            name="natureza",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Natureza da Operação",
            ),
        ),
        migrations.AddField(
            model_name="faturamentoduplicata",
            name="valor_cofins",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor COFINS",
            ),
        ),
        migrations.AddField(
            model_name="faturamentoduplicata",
            name="valor_pis",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor PIS",
            ),
        ),
    ]
