# Generated by Django 4.2.16 on 2025-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0024_faturamentoduplicata_cfop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculomaterial",
            name="peso_bruto",
            field=models.DecimalField(
                decimal_places=10, max_digits=20, verbose_name="Peso Bruto (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculomaterial",
            name="peso_bruto_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Peso Bruto Total (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="precalculomaterial",
            name="peso_liquido",
            field=models.DecimalField(
                decimal_places=10, max_digits=20, verbose_name="Peso Líquido (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="peso_bruto",
            field=models.DecimalField(
                decimal_places=10, max_digits=20, verbose_name="Peso Bruto (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="peso_liquido",
            field=models.DecimalField(
                decimal_places=10, max_digits=20, verbose_name="Peso Líquido (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="peso_liquido_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Peso Líquido Total (kg)",
            ),
        ),
    ]
