# Generated by Django 4.2.16 on 2025-08-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0025_alter_precalculomaterial_peso_bruto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="desenvolvido_mm",
            field=models.DecimalField(
                decimal_places=7, max_digits=15, verbose_name="Desenvolvido (mm)"
            ),
        ),
    ]
