# Generated by Django 4.2.16 on 2025-06-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0025_remove_analisecomercial_cotacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculo",
            name="cotacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precalculos",
                to="comercial.cotacao",
            ),
        ),
    ]
