# Generated by Django 4.2.16 on 2025-08-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0026_alter_precalculoservicoexterno_desenvolvido_mm"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoduplicata",
            name="valor_ipi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
