# Generated by Django 4.2.16 on 2025-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0026_alter_precalculo_cotacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacaotecnica",
            name="campo1",
        ),
        migrations.RemoveField(
            model_name="avaliacaotecnica",
            name="detalhe1",
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="acabamento_obs",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Descreva o acabamento"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="acabamento_superficial",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui requisito de acabamento superficial?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="amostras_obs",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Detalhes sobre as amostras"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="caracteristicas_criticas",
            field=models.BooleanField(
                default=False,
                verbose_name="Existem características críticas definidas?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="conclusao",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Conclusão técnica"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="criticas_obs",
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name="Quais são essas características?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="dispositivo_obs",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Detalhes sobre o dispositivo"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metrologia_obs",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Detalhes sobre a validação"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="possui_projeto",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui projeto próprio ou desenho fornecido?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="precisa_amostras",
            field=models.BooleanField(
                default=False, verbose_name="Necessita de amostras para validação?"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="precisa_dispositivo",
            field=models.BooleanField(
                default=False,
                verbose_name="Necessita desenvolvimento de dispositivo de controle?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="projeto_obs",
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name="Detalhes sobre o projeto/desenho",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="rastreabilidade",
            field=models.BooleanField(
                default=False, verbose_name="Há exigência de rastreabilidade técnica?"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="rastreabilidade_obs",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Detalhes da rastreabilidade"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="restricao_dimensional",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui restrição dimensional ou geométrica?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="restricao_obs",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Descreva a restrição"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="validacao_metrologica",
            field=models.BooleanField(
                default=False, verbose_name="Haverá validação metrológica?"
            ),
        ),
    ]
