# Generated by Django 4.2.16 on 2025-06-20 15:03

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0027_remove_avaliacaotecnica_campo1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="consideracoes",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Considerações"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_a",
            field=models.BooleanField(
                default=False, verbose_name="9a. Metas de qualidade (exemplo PPM) ?"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_a_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_b",
            field=models.BooleanField(
                default=False, verbose_name="9b. Metas de produtividade ?"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_b_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_c",
            field=models.BooleanField(
                default=False,
                verbose_name="9c. Metas de desempenho (exemplo: Cp, Cpk, etc.) ?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_c_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_d",
            field=models.BooleanField(
                default=False, verbose_name="9d. Metas de funcionamento ?"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_d_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="requisito_especifico",
            field=models.BooleanField(
                default=False,
                verbose_name="11. O cliente forneceu requisito especifico ?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="requisito_especifico_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="seguranca",
            field=models.BooleanField(
                default=False,
                verbose_name="10. Os requisitos sobre o item de segurança foram considerados ?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="seguranca_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="conclusao",
            field=models.CharField(
                choices=[
                    (
                        "Viável",
                        "Viavel (O produto pode ser produzido conforme especificado,sem revisoes) ",
                    ),
                    (
                        "Viável c/ Recomendações",
                        "Viável (alterações recomendadas conforme considerações)",
                    ),
                    (
                        "Inviável",
                        "Inviável (necessidade de revisão do projeto para a manufatura do produto dentro dos requisitos especificados)",
                    ),
                ],
                max_length=30,
                verbose_name="Conclusão da Análise Crítica",
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="especificacao_embalagem",
            field=models.BooleanField(
                default=False, verbose_name="7. Existe especificação de Embalagem"
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="especificacao_identificacao",
            field=models.BooleanField(
                default=False, verbose_name="8. Existe especificação de Identificação"
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="material_fornecido",
            field=models.BooleanField(
                default=False, verbose_name="2. Material fornecido pelo cliente ?"
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="requisitos_comunicacao",
            field=models.BooleanField(
                default=False,
                verbose_name="5. Existe requisito de Comunicação Eletrônica com o cliente?",
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="requisitos_entrega",
            field=models.BooleanField(
                default=False,
                verbose_name="3. Existe Requisitos de Entrega (frequência)?",
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="requisitos_notificacao",
            field=models.BooleanField(
                default=False,
                verbose_name="6. Existe requisito de notificação de Embarque ?",
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="requisitos_pos_entrega",
            field=models.BooleanField(
                default=False, verbose_name="4. Existe Requisitos Pós-Entrega ?"
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="tipo_embalagem",
            field=models.BooleanField(
                default=False,
                verbose_name="9. Qual o tipo de embalagem a ser utilizada ?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="acabamento_superficial",
            field=models.BooleanField(
                default=False,
                verbose_name="6 .As normas/especificações/requisitos estão disponiveis?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="caracteristicas_criticas",
            field=models.BooleanField(
                default=False, verbose_name="3. O cliente forneceu FMEA de produto ?"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="conclusao",
            field=models.CharField(
                choices=[
                    (
                        "Viável",
                        "Viavel (O produto pode ser produzido conforme especificado,sem revisoes) ",
                    ),
                    (
                        "Viável c/ Recomendações",
                        "Viável (alterações recomendadas conforme considerações)",
                    ),
                    (
                        "Inviável",
                        "Inviável (necessidade de revisão do projeto para a manufatura do produto dentro dos requisitos especificados)",
                    ),
                ],
                max_length=30,
                verbose_name="Conclusão da Análise Crítica",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="possui_projeto",
            field=models.BooleanField(
                default=False,
                verbose_name="1. Existe característica especoal além das relacionadas nas especificações ?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="precisa_amostras",
            field=models.BooleanField(
                default=False,
                verbose_name="4. O cliente solicitou algum teste além dos relacionados nas especificações ?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="precisa_dispositivo",
            field=models.BooleanField(
                default=False, verbose_name="2. A peça é item de aparência ?"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="rastreabilidade",
            field=models.BooleanField(
                default=False,
                verbose_name="8. Existem requisitos adicionais e/ou não declarados pelo cliente ?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="restricao_dimensional",
            field=models.BooleanField(
                default=False,
                verbose_name="5. O cliente forneceu lista de fornecedores/materiais aprovados ?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="validacao_metrologica",
            field=models.BooleanField(
                default=False,
                verbose_name="7. São aplicaveis requisitos estatutários/regulamentares ?",
            ),
        ),
    ]
