# Generated by Django 4.2.16 on 2025-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0027_faturamentoduplicata_valor_ipi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicadorcomercialregistromensal",
            name="indicador",
            field=models.CharField(
                choices=[
                    ("1.1", "Índice de Faturamento (Semestral)"),
                    ("1.1.1", "Faturamento Mensal (R$)"),
                    ("4.1", "Atendimento do Prazo de Cotação"),
                    ("4.2", "Número de Itens Novos Vendidos"),
                    ("4.3", "Número de Cotações por Funcionário"),
                    ("4.4", "Taxa de Orçamentos Aprovados"),
                ],
                max_length=10,
            ),
        ),
    ]
