# Generated by Django 4.2.16 on 2025-06-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0028_avaliacaotecnica_consideracoes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="requisito_especifico",
            field=models.BooleanField(
                choices=[(None, "Não aplicável"), (True, "Sim"), (False, "Não")],
                null=True,
                verbose_name="11. O cliente forneceu requisito especifico ?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="seguranca",
            field=models.BooleanField(
                choices=[(None, "Não aplicável"), (True, "Sim"), (False, "Não")],
                null=True,
                verbose_name="10. Os requisitos sobre o item de segurança foram considerados ?",
            ),
        ),
    ]
