# Generated by Django 4.2.16 on 2025-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0028_alter_indicadorcomercialregistromensal_indicador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desenvolvimento",
            name="completo",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tudo preenchido corretamente?"
            ),
        ),
    ]
