# Generated by Django 4.2.16 on 2025-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0029_alter_desenvolvimento_completo"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisecomercial",
            name="necessita_ferramental",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Necessita de ferramental/dispositivo?",
            ),
        ),
    ]
