# Generated by Django 4.2.16 on 2025-06-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comercial", "0029_alter_avaliacaotecnica_requisito_especifico_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="assinado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cotacaoferramenta",
            name="assinado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cotacaoferramenta",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="cotacaoferramenta",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="cotacaoferramenta",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="cotacaoferramenta",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="desenvolvimento",
            name="assinado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="desenvolvimento",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="desenvolvimento",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="desenvolvimento",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="desenvolvimento",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="assinado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="assinado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="regrascalculo",
            name="assinado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regrascalculo",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="regrascalculo",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="regrascalculo",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="regrascalculo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roteirocotacao",
            name="assinado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roteirocotacao",
            name="assinatura_cn",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="CN da assinatura (email)",
            ),
        ),
        migrations.AddField(
            model_name="roteirocotacao",
            name="assinatura_nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="roteirocotacao",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da assinatura"
            ),
        ),
        migrations.AddField(
            model_name="roteirocotacao",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="analisecomercial",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
