# Generated by Django 4.2.16 on 2025-09-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0030_analisecomercial_necessita_ferramental"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferramenta",
            name="forma_calculo",
            field=models.CharField(
                choices=[("PADRAO", "Cálculo Padrão")],
                default="PADRAO",
                max_length=20,
                verbose_name="Forma de Cálculo",
            ),
        ),
        migrations.AlterField(
            model_name="itembloco",
            name="material",
            field=models.CharField(
                choices=[
                    ("SAE 1020", "SAE 1020"),
                    ("VND", "VND"),
                    ("SAE D2", "SAE D2"),
                ],
                max_length=50,
                verbose_name="Material",
            ),
        ),
    ]
