# Generated by Django 4.2.16 on 2025-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0030_avaliacaotecnica_assinado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="consideracoes",
            field=models.TextField(blank=True, null=True, verbose_name="Considerações"),
        ),
    ]
