# Generated by Django 4.2.16 on 2025-09-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0031_ferramenta_forma_calculo_alter_itembloco_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="nome_fantasia",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome Fantasia"
            ),
        ),
    ]
