# Generated by Django 4.2.16 on 2025-06-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0031_alter_avaliacaotecnica_consideracoes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avaliacaotecnica",
            old_name="consideracoes",
            new_name="consideracoes_tec",
        ),
    ]
