# Generated by Django 4.2.16 on 2025-06-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0032_rename_consideracoes_avaliacaotecnica_consideracoes_tec"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avaliacaotecnica",
            old_name="conclusao",
            new_name="conclusao_tec",
        ),
    ]
