# Generated by Django 4.2.16 on 2025-09-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0032_cliente_nome_fantasia"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoduplicata",
            name="valor_icms",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Valor ICMS",
            ),
        ),
    ]
