# Generated by Django 4.2.16 on 2025-09-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0033_faturamentoduplicata_valor_icms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="tipo_cadastro",
            field=models.CharField(
                choices=[
                    ("Cliente", "Cliente"),
                    ("Transportadora", "Transportadora"),
                    ("Fornecedor", "Fornecedor"),
                ],
                default="Cliente",
                max_length=20,
            ),
        ),
    ]
