# Generated by Django 4.2.16 on 2025-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0033_rename_conclusao_avaliacaotecnica_conclusao_tec"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculomaterial",
            name="status",
            field=models.CharField(
                choices=[("aguardando", "Aguardando Cotação"), ("ok", "OK")],
                default="aguardando",
                max_length=20,
                verbose_name="Status da Cotação",
            ),
        ),
    ]
