# Generated by Django 4.2.16 on 2025-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0034_alter_cliente_tipo_cadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metafaturamento",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Valor da Meta",
            ),
        ),
    ]
