# Generated by Django 4.2.16 on 2025-06-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade_fornecimento",
            "0085_inspecaoservicoexterno_assinatura_data_and_more",
        ),
        ("comercial", "0034_precalculomaterial_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculomaterial",
            name="entrega_dias",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Entrega (dias)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculomaterial",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="qualidade_fornecimento.fornecedorqualificado",
            ),
        ),
        migrations.AlterField(
            model_name="precalculomaterial",
            name="lote_minimo",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Lote Mínimo"
            ),
        ),
        migrations.AlterField(
            model_name="precalculomaterial",
            name="preco_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Preço /kg",
            ),
        ),
    ]
