# Generated by Django 4.2.16 on 2025-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0035_alter_precalculomaterial_entrega_dias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisecomercial",
            name="periodo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Único", "Único"),
                    ("Quinzenal", "Quinzenal"),
                    ("Mensal", "Mensal"),
                    ("Trimestral", "Trimestral"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                    ("Esporádico", "Esporádico"),
                ],
                max_length=20,
                null=True,
                verbose_name="Periodicidade de Fornecimento",
            ),
        ),
        migrations.AddField(
            model_name="analisecomercial",
            name="qtde_estimada",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade Estimada"
            ),
        ),
    ]
