# Generated by Django 4.2.16 on 2025-09-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0035_alter_metafaturamento_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="faturamentoregistro",
            name="situacao",
            field=models.CharField(
                choices=[("EMITIDA", "Emitida"), ("CANCELADA", "Cancelada")],
                db_index=True,
                default="EMITIDA",
                max_length=12,
                verbose_name="Situação",
            ),
        ),
    ]
