# Generated by Django 4.2.16 on 2025-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0036_analisecomercial_periodo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculomaterial",
            name="icms",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ICMS (%)",
            ),
        ),
    ]
