# Generated by Django 4.2.16 on 2025-06-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0037_precalculomaterial_icms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculomaterial",
            name="peso_bruto",
            field=models.DecimalField(
                decimal_places=7, max_digits=20, verbose_name="Peso Bruto (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculomaterial",
            name="peso_liquido",
            field=models.DecimalField(
                decimal_places=7, max_digits=20, verbose_name="Peso Líquido (kg)"
            ),
        ),
    ]
