# Generated by Django 4.2.16 on 2025-06-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0007_propriedadesetapa_ferramenta"),
        ("comercial", "0038_alter_precalculomaterial_peso_bruto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculomaterial",
            name="roteiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tecnico.roteiroproducao",
                verbose_name="Roteiro de Produção",
            ),
        ),
    ]
