# Generated by Django 4.2.16 on 2025-06-23 13:07

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0039_alter_precalculomaterial_roteiro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precalculomaterial",
            name="observacoes",
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="observacoes_materiais",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações Materiais"
            ),
        ),
    ]
