# Generated by Django 4.2.16 on 2025-07-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0041_remove_precalculomaterial_observacoes_materiais_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlocoFerramenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, verbose_name="Bloco")),
            ],
        ),
        migrations.CreateModel(
            name="ItemBloco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_item",
                    models.CharField(max_length=20, verbose_name="Nº Item"),
                ),
                (
                    "medidas",
                    models.CharField(
                        max_length=100, verbose_name="Medidas (ex: 25,4x94x165)"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[("SAE 1020", "SAE 1020"), ("VND", "VND")],
                        max_length=50,
                        verbose_name="Material",
                    ),
                ),
                (
                    "peso_aco",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.86,
                        max_digits=5,
                        verbose_name="Peso Aço",
                    ),
                ),
                (
                    "bloco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="comercial.blocoferramenta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="largura_tira",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Largura da Tira / Perímetro de Corte",
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="num_carros",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número de Carros"
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="num_formadores",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número de Formadores"
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="num_matrizes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número de Matrizes"
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="num_puncoes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número de Punções"
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="passo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Passo",
            ),
        ),
        migrations.DeleteModel(
            name="MaterialFerramenta",
        ),
        migrations.AddField(
            model_name="blocoferramenta",
            name="ferramenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocos",
                to="comercial.ferramenta",
            ),
        ),
    ]
