# Generated by Django 4.2.16 on 2025-07-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "comercial",
            "0042_blocoferramenta_itembloco_ferramenta_largura_tira_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocoferramenta",
            name="ferramenta",
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="bloco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ferramentas",
                to="comercial.blocoferramenta",
            ),
        ),
    ]
