# Generated by Django 4.2.16 on 2025-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0043_remove_blocoferramenta_ferramenta_ferramenta_bloco"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferramenta",
            name="valor_unitario_carros",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="valor_unitario_flange",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="valor_unitario_formadores",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="valor_unitario_matriz",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="valor_unitario_puncao",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
