# Generated by Django 4.2.16 on 2025-07-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0044_ferramenta_valor_unitario_carros_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itembloco",
            name="peso_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Peso Total",
            ),
        ),
        migrations.AddField(
            model_name="itembloco",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Volume",
            ),
        ),
    ]
