# Generated by Django 4.2.16 on 2025-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0045_itembloco_peso_total_itembloco_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferramenta",
            name="peso_sae_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Peso SAE 1020 (Kg)",
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="peso_vnd_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Peso VND (Kg)",
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="valor_unitario_sae",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Unitário SAE 1020 (R$/Kg)",
            ),
        ),
        migrations.AddField(
            model_name="ferramenta",
            name="valor_unitario_vnd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Unitário VND (R$/Kg)",
            ),
        ),
    ]
