# Generated by Django 4.2.16 on 2025-07-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0046_ferramenta_peso_sae_kg_ferramenta_peso_vnd_kg_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="centrodecusto",
            options={
                "ordering": ["nome"],
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
            },
        ),
        migrations.RemoveField(
            model_name="centrodecusto",
            name="departamento",
        ),
        migrations.AddField(
            model_name="centrodecusto",
            name="nome",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Centro de Custo"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="coleta",
            field=models.BooleanField(default=False, verbose_name="Coleta"),
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="selecionado",
            field=models.BooleanField(default=False),
        ),
    ]
