# Generated by Django 4.2.16 on 2025-07-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0047_alter_centrodecusto_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.CharField(
                choices=[
                    ("Automotivo", "Automotivo"),
                    ("Não Automotivo", "Não Automotivo"),
                    ("Reposição", "Reposição"),
                    ("Transportadora", "Transportadora"),
                ],
                max_length=20,
            ),
        ),
    ]
