# Generated by Django 4.2.16 on 2025-07-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0048_alter_cliente_tipo_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="simbolo_seguranca",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="itens/simbolos/",
                verbose_name="Simbol. Segurança",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
