# Generated by Django 4.2.16 on 2025-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0049_item_simbolo_seguranca_item_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tipo_item",
            field=models.CharField(
                choices=[("Cotacao", "Cotação"), ("Corrente", "Corrente")],
                default="Cotacao",
                max_length=20,
                verbose_name="Tipo de Item",
            ),
        ),
    ]
