# Generated by Django 4.2.16 on 2025-07-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0099_alter_fornecedorqualificado_data_homologacao"),
        ("tecnico", "0007_propriedadesetapa_ferramenta"),
        ("comercial", "0050_item_tipo_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precalculoservicoexterno",
            name="etapa",
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="insumo",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={
                    "etapa__setor__nome__icontains": "Tratamento Externo"
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="tecnico.insumoetapa",
                verbose_name="Insumo (Tratamento Externo)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="selecionado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="status",
            field=models.CharField(
                choices=[("aguardando", "Aguardando Cotação"), ("ok", "OK")],
                default="aguardando",
                max_length=20,
                verbose_name="Status da Cotação",
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="codigo",
            field=models.CharField(
                editable=False, max_length=50, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="entrega_dias",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Entrega (dias)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="qualidade_fornecimento.fornecedorqualificado",
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="lote_minimo",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Lote Mínimo"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="peso_bruto",
            field=models.DecimalField(
                decimal_places=7, max_digits=20, verbose_name="Peso Bruto (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="peso_liquido",
            field=models.DecimalField(
                decimal_places=7, max_digits=20, verbose_name="Peso Líquido (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="preco_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Preço /kg",
            ),
        ),
    ]
