# Generated by Django 4.2.16 on 2025-07-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0051_remove_precalculoservicoexterno_etapa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precalculoservicoexterno",
            name="codigo",
        ),
    ]
