# Generated by Django 4.2.16 on 2025-07-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0052_remove_precalculoservicoexterno_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculo",
            name="preco_manual",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Preço Final Manual (R$)",
            ),
        ),
        migrations.AddField(
            model_name="precalculo",
            name="preco_selecionado",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Preço Final Selecionado (R$)",
            ),
        ),
    ]
