# Generated by Django 4.2.16 on 2025-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0053_precalculo_preco_manual_precalculo_preco_selecionado"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisecomercial",
            name="motivo_reprovacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo da Reprovação"
            ),
        ),
        migrations.AddField(
            model_name="analisecomercial",
            name="status",
            field=models.CharField(
                choices=[
                    ("andamento", "Em Andamento"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                    ("amostras", "Solicitação de Amostras"),
                ],
                default="andamento",
                max_length=20,
                verbose_name="Status da Análise",
            ),
        ),
    ]
