# Generated by Django 4.2.16 on 2025-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0054_analisecomercial_motivo_reprovacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="ncm",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="NCM"
            ),
        ),
    ]
