# Generated by Django 4.2.16 on 2025-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0055_alter_item_descricao_alter_item_ncm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculomaterial",
            name="desenvolvido_mm",
            field=models.DecimalField(
                decimal_places=4, max_digits=8, verbose_name="Desenvolvido (mm)"
            ),
        ),
    ]
