# Generated by Django 4.2.16 on 2025-07-07 18:52

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0056_alter_precalculomaterial_desenvolvido_mm"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculo",
            name="observacoes_servicos",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações Serviços Externos"
            ),
        ),
    ]
