# Generated by Django 4.2.16 on 2025-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0057_precalculo_observacoes_servicos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculo",
            name="numero",
            field=models.PositiveIntegerField(
                editable=False, verbose_name="Número do Pré-Cálculo"
            ),
        ),
    ]
