# Generated by Django 4.2.16 on 2025-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0058_alter_precalculo_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="icms",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ICMS (%)",
            ),
        ),
    ]
