# Generated by Django 4.2.16 on 2025-07-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0060_alter_precalculo_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roteirocotacao",
            name="nome_acao",
        ),
    ]
