# Generated by Django 4.2.16 on 2025-07-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0007_propriedadesetapa_ferramenta"),
        ("comercial", "0061_remove_roteirocotacao_nome_acao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precalculoservicoexterno",
            name="insumo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tecnico.insumoetapa",
                verbose_name="Insumo (original do roteiro)",
            ),
        ),
    ]
