# Generated by Django 4.2.16 on 2025-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0062_alter_precalculoservicoexterno_insumo"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="codigo_materia_prima",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código MP"
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="descricao_materia_prima",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Descrição MP"
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="nome_insumo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome do Insumo"
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="unidade",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Unidade MP"
            ),
        ),
    ]
