# Generated by Django 4.2.16 on 2025-07-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0063_precalculoservicoexterno_codigo_materia_prima_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculomaterial",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="nome_materia_prima",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nome da Matéria-prima",
            ),
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="unidade",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Unidade"
            ),
        ),
    ]
