# Generated by Django 4.2.16 on 2025-07-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0064_precalculomaterial_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisecomercial",
            name="capacidade_produtiva",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Capacidade produtiva disponível?"
            ),
        ),
    ]
