# Generated by Django 4.2.16 on 2025-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0065_analisecomercial_capacidade_produtiva"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculomaterial",
            name="peso_bruto_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=20,
                null=True,
                verbose_name="Peso Bruto Total (kg)",
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="peso_bruto_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=20,
                null=True,
                verbose_name="Peso Bruto Total (kg)",
            ),
        ),
    ]
