# Generated by Django 4.2.16 on 2025-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0066_precalculomaterial_peso_bruto_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculomaterial",
            name="tipo_material",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo de Material"
            ),
        ),
    ]
