# Generated by Django 4.2.16 on 2025-07-15 11:19

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0067_precalculomaterial_tipo_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculo",
            name="observacoes_roteiro",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações do Roteiro"
            ),
        ),
        migrations.AddField(
            model_name="roteirocotacao",
            name="maquinas_roteiro",
            field=models.TextField(
                blank=True, null=True, verbose_name="Máquinas da Etapa"
            ),
        ),
    ]
