# Generated by Django 4.2.16 on 2025-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0068_precalculo_observacoes_roteiro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roteirocotacao",
            name="nome_acao",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome da Ação"
            ),
        ),
    ]
