# Generated by Django 4.2.16 on 2025-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0069_roteirocotacao_nome_acao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roteirocotacao",
            name="nome_acao",
            field=models.TextField(blank=True, null=True, verbose_name="Nome da Ação"),
        ),
    ]
