# Generated by Django 4.2.16 on 2025-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0070_alter_roteirocotacao_nome_acao"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="fmea",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="3. O cliente forneceu FMEA de produto?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="fmea_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="item_aparencia",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="2. A peça é item de aparência?"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="item_aparencia_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="lista_fornecedores",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="5. Lista de fornecedores/materiais aprovados?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="lista_fornecedores_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_confiabilidade",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="9d. Metas de confiabilidade?"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="metas_confiabilidade_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="normas_disponiveis",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="6. Normas/especificações estão disponíveis?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="normas_disponiveis_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="requisitos_adicionais",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="8. Requisitos adicionais ou não declarados?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="requisitos_adicionais_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="requisitos_regulamentares",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="7. Existem requisitos estatutários/regulamentares?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="requisitos_regulamentares_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="teste_solicitado",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="4. O cliente solicitou testes adicionais?",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotecnica",
            name="teste_solicitado_obs",
            field=models.CharField(blank=True, max_length=300, verbose_name="Detalhes"),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="acabamento_superficial",
            field=models.BooleanField(
                default=False,
                verbose_name="6. Normas/especificações estão disponíveis?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="caracteristicas_criticas",
            field=models.BooleanField(
                default=False, verbose_name="3. O cliente forneceu FMEA de produto?"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="conclusao_tec",
            field=models.CharField(
                choices=[
                    (
                        "Viável",
                        "Viável (O produto pode ser produzido conforme especificado, sem revisões)",
                    ),
                    (
                        "Viável c/ Recomendações",
                        "Viável (alterações recomendadas conforme considerações)",
                    ),
                    (
                        "Inviável",
                        "Inviável (necessidade de revisão do projeto para a manufatura do produto dentro dos requisitos especificados)",
                    ),
                ],
                max_length=30,
                verbose_name="Conclusão da Análise Crítica",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="metas_a",
            field=models.BooleanField(
                default=False, verbose_name="9a. Metas de qualidade (exemplo PPM)?"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="metas_b",
            field=models.BooleanField(
                default=False, verbose_name="9b. Metas de produtividade?"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="metas_c",
            field=models.BooleanField(
                default=False,
                verbose_name="9c. Metas de desempenho (exemplo: Cp, Cpk, etc.)?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="metas_d",
            field=models.BooleanField(
                default=False, verbose_name="9e. Metas de funcionamento?"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="possui_projeto",
            field=models.BooleanField(
                default=False,
                verbose_name="1. Existe característica especial além das relacionadas nas especificações?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="precisa_amostras",
            field=models.BooleanField(
                default=False, verbose_name="4. O cliente solicitou testes adicionais?"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="precisa_dispositivo",
            field=models.BooleanField(
                default=False, verbose_name="2. A peça é item de aparência?"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="rastreabilidade",
            field=models.BooleanField(
                default=False,
                verbose_name="8. Requisitos adicionais ou não declarados?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="requisito_especifico",
            field=models.BooleanField(
                choices=[(None, "Não aplicável"), (True, "Sim"), (False, "Não")],
                null=True,
                verbose_name="11. O cliente forneceu requisito específico?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="restricao_dimensional",
            field=models.BooleanField(
                default=False,
                verbose_name="5. Lista de fornecedores/materiais aprovados?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="seguranca",
            field=models.BooleanField(
                choices=[(None, "Não aplicável"), (True, "Sim"), (False, "Não")],
                null=True,
                verbose_name="10. Os requisitos sobre o item de segurança foram considerados?",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="validacao_metrologica",
            field=models.BooleanField(
                default=False,
                verbose_name="7. Existem requisitos estatutários/regulamentares?",
            ),
        ),
    ]
