# Generated by Django 4.2.16 on 2025-07-16 17:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0071_avaliacaotecnica_fmea_avaliacaotecnica_fmea_obs_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="precalculo",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="precalculo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="observacoes",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações da Matéria-Prima"
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="observacoes",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações do Serviço"
            ),
        ),
        migrations.AddField(
            model_name="roteirocotacao",
            name="observacoes",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações da Etapa"
            ),
        ),
        migrations.RemoveField(
            model_name="precalculo",
            name="observacoes_materiais",
        ),
        migrations.RemoveField(
            model_name="precalculo",
            name="observacoes_roteiro",
        ),
        migrations.RemoveField(
            model_name="precalculo",
            name="observacoes_servicos",
        ),
    ]
