# Generated by Django 4.2.16 on 2025-07-16 18:52

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0072_alter_precalculo_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roteirocotacao",
            old_name="observacoes",
            new_name="observacoes_roteiro",
        ),
        migrations.RemoveField(
            model_name="precalculomaterial",
            name="observacoes",
        ),
        migrations.RemoveField(
            model_name="precalculoservicoexterno",
            name="observacoes",
        ),
        migrations.AddField(
            model_name="precalculomaterial",
            name="observacoes_materiais",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações gerais de materiais"
            ),
        ),
        migrations.AddField(
            model_name="precalculoservicoexterno",
            name="observacoes_servicos",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações gerais de serviços"
            ),
        ),
    ]
