# Generated by Django 4.2.16 on 2025-07-16 19:23

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "comercial",
            "0073_rename_observacoes_roteirocotacao_observacoes_roteiro_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precalculomaterial",
            name="observacoes_materiais",
        ),
        migrations.RemoveField(
            model_name="precalculoservicoexterno",
            name="observacoes_servicos",
        ),
        migrations.RemoveField(
            model_name="roteirocotacao",
            name="observacoes_roteiro",
        ),
        migrations.AddField(
            model_name="precalculo",
            name="observacoes_materiais",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações gerais de materiais"
            ),
        ),
        migrations.AddField(
            model_name="precalculo",
            name="observacoes_roteiro",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações da Etapa"
            ),
        ),
        migrations.AddField(
            model_name="precalculo",
            name="observacoes_servicos",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações gerais de serviços"
            ),
        ),
    ]
