# Generated by Django 4.2.16 on 2025-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0074_remove_precalculomaterial_observacoes_materiais_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="departamento_contato",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
