# Generated by Django 4.2.16 on 2025-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0075_cliente_departamento_contato"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotacao",
            name="validade_proposta",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Número de dias de validade da proposta a partir da data de abertura.",
                verbose_name="Validade da proposta (dias)",
            ),
        ),
    ]
