# Generated by Django 4.2.16 on 2025-07-17 16:07

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0076_cotacao_validade_proposta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="observacao",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Particularidades do cliente"
            ),
        ),
    ]
