# Generated by Django 4.2.16 on 2025-07-18 14:11

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0078_alter_centrodecusto_observacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analisecomercial",
            name="motivo_reprovacao",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Motivo da Reprovação"
            ),
        ),
    ]
