# Generated by Django 4.2.16 on 2025-07-18 17:14

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0079_alter_analisecomercial_motivo_reprovacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaotecnica",
            name="consideracoes_tec",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Considerações Técnicas"
            ),
        ),
    ]
