# Generated by Django 4.2.16 on 2025-07-21 11:11

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0080_alter_avaliacaotecnica_consideracoes_tec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotacaoferramenta",
            name="observacoes",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações da Ferramenta"
            ),
        ),
    ]
