# Generated by Django 4.2.16 on 2025-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0081_alter_cotacaoferramenta_observacoes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="simbolo_seguranca",
        ),
        migrations.AddField(
            model_name="item",
            name="seguranca_l1",
            field=models.BooleanField(default=False, verbose_name="Possui L1"),
        ),
        migrations.AddField(
            model_name="item",
            name="seguranca_l2",
            field=models.BooleanField(default=False, verbose_name="Possui L2"),
        ),
        migrations.AddField(
            model_name="item",
            name="seguranca_m1",
            field=models.BooleanField(default=False, verbose_name="Possui M1"),
        ),
        migrations.AddField(
            model_name="item",
            name="seguranca_mp",
            field=models.BooleanField(default=False, verbose_name="Possui MP"),
        ),
        migrations.AddField(
            model_name="item",
            name="seguranca_ts",
            field=models.BooleanField(default=False, verbose_name="Possui TS"),
        ),
        migrations.AddField(
            model_name="item",
            name="simbolo_l1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="itens/simbolos/",
                verbose_name="Imagem L1",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="simbolo_l2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="itens/simbolos/",
                verbose_name="Imagem L2",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="simbolo_m1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="itens/simbolos/",
                verbose_name="Imagem M1",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="simbolo_mp",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="itens/simbolos/",
                verbose_name="Imagem MP",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="simbolo_ts",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="itens/simbolos/",
                verbose_name="Imagem TS",
            ),
        ),
    ]
