# Generated by Django 4.2.16 on 2025-07-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comercial", "0082_remove_item_simbolo_seguranca_item_seguranca_l1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemDesenvolvimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="Nº Ordem"
                    ),
                ),
                (
                    "email_ppap",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="E-mail para envio PPAP",
                    ),
                ),
                (
                    "codigo_brasmol",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Bras-Mol",
                    ),
                ),
                (
                    "prazo_solicitado",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo solicitado"
                    ),
                ),
                (
                    "qtde_amostra",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Quantidade de amostra"
                    ),
                ),
                (
                    "razao",
                    models.CharField(
                        choices=[
                            ("novo", "Novo item"),
                            ("discrepancia", "Correção de discrepância"),
                            ("transferencia", "Transferência para outro cliente"),
                            ("especificacao", "Alteração de especificação"),
                            ("fornecedor", "Alteração de fornecedor"),
                            ("revalidacao", "Atualização/Revalidação"),
                            ("ferramental", "Alteração de ferramental"),
                            ("processo", "Alteração de processo"),
                            ("amostras", "Amostras"),
                        ],
                        max_length=30,
                        verbose_name="Razão do desenvolvimento",
                    ),
                ),
                (
                    "automotivo_oem",
                    models.BooleanField(default=False, verbose_name="Automotivo OEM"),
                ),
                (
                    "comprador",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Comprador"
                    ),
                ),
                (
                    "requisito_especifico",
                    models.BooleanField(
                        default=False, verbose_name="Requisito Específico Cliente?"
                    ),
                ),
                (
                    "item_seguranca",
                    models.BooleanField(
                        default=False, verbose_name="É Item de Segurança?"
                    ),
                ),
                (
                    "codigo_desenho",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Desenho",
                    ),
                ),
                (
                    "revisao",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Revisão"
                    ),
                ),
                (
                    "data_revisao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Revisão"
                    ),
                ),
                (
                    "metodologia_aprovacao",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Metodologia de aprovação",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "familia_produto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MCGC", "MCGC"),
                            ("MTORGC", "MTORGC"),
                            ("HGD", "HGD"),
                            ("AGD", "AGD"),
                            ("MCGD", "MCGD"),
                            ("MTORGX", "MTORGX"),
                            ("HGM", "HGM"),
                            ("AGE", "AGE"),
                            ("MTRAGC", "MTRAGC"),
                            ("MTORGD", "MTORGD"),
                            ("HGE", "HGE"),
                            ("PGC", "PGC"),
                            ("MTRAGX", "MTRAGX"),
                            ("PEGE", "PEGE"),
                            ("HGC", "HGC"),
                            ("PGE", "PGE"),
                            ("MTRAGD", "MTRAGD"),
                            ("PEGP", "PEGP"),
                            ("AGC", "AGC"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Família de Produto",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[("usual", "Usual"), ("novo", "Novo")],
                        max_length=10,
                        null=True,
                        verbose_name="Material",
                    ),
                ),
                (
                    "revisar_pir",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        null=True,
                        verbose_name="Revisar PIR?",
                    ),
                ),
                (
                    "aprovado",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não"), ("na", "N/A")],
                        max_length=5,
                        null=True,
                        verbose_name="Aprovado?",
                    ),
                ),
                (
                    "prazo_material",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Material"
                    ),
                ),
                (
                    "rotinas_sistema",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("roteiro", "Roteiro de operações"),
                            ("bloqueio", "Bloqueio"),
                            ("na", "N/A"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Rotinas do Sistema",
                    ),
                ),
                (
                    "prazo_rotinas",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Rotinas"
                    ),
                ),
                (
                    "documentos_producao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Documentos de produção",
                    ),
                ),
                (
                    "prazo_docs",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Documentos"
                    ),
                ),
                (
                    "ferramenta",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        null=True,
                        verbose_name="Ferramenta",
                    ),
                ),
                (
                    "tipo_ferramenta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nova", "Nova"),
                            ("adaptacao", "Adaptação"),
                            ("outros", "Outros"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="Tipo Ferramenta",
                    ),
                ),
                (
                    "os_ferramenta",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nº OS Ferramenta"
                    ),
                ),
                (
                    "prazo_ferramental",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Ferramental"
                    ),
                ),
                (
                    "dispositivo",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        null=True,
                        verbose_name="Dispositivo",
                    ),
                ),
                (
                    "tipo_dispositivo",
                    models.CharField(
                        blank=True,
                        choices=[("medicao", "Medição"), ("auxiliar", "Auxiliar")],
                        max_length=15,
                        null=True,
                        verbose_name="Tipo Dispositivo",
                    ),
                ),
                (
                    "os_dispositivo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nº OS Dispositivo"
                    ),
                ),
                (
                    "prazo_dispositivo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Dispositivo"
                    ),
                ),
                (
                    "amostra",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        null=True,
                        verbose_name="Amostra",
                    ),
                ),
                (
                    "numero_op",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nº OP"
                    ),
                ),
                (
                    "prazo_amostra",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Amostra"
                    ),
                ),
                (
                    "tratamento_termico",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        null=True,
                        verbose_name="Trat. térmico externo",
                    ),
                ),
                (
                    "tipo_tte",
                    models.CharField(
                        blank=True,
                        choices=[("usual", "Usual"), ("novo", "Novo")],
                        max_length=10,
                        null=True,
                        verbose_name="Tipo TTE",
                    ),
                ),
                (
                    "status_tte",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não"), ("na", "N/A")],
                        max_length=10,
                        null=True,
                        verbose_name="Status TTE",
                    ),
                ),
                (
                    "prazo_tte",
                    models.DateField(blank=True, null=True, verbose_name="Prazo TTE"),
                ),
                (
                    "tratamento_superficial",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        null=True,
                        verbose_name="Trat. superficial externo",
                    ),
                ),
                (
                    "tipo_tse",
                    models.CharField(
                        blank=True,
                        choices=[("usual", "Usual"), ("novo", "Novo")],
                        max_length=10,
                        null=True,
                        verbose_name="Tipo TSE",
                    ),
                ),
                (
                    "status_tse",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não"), ("na", "N/A")],
                        max_length=10,
                        null=True,
                        verbose_name="Status TSE",
                    ),
                ),
                (
                    "prazo_tse",
                    models.DateField(blank=True, null=True, verbose_name="Prazo TSE"),
                ),
                (
                    "resistencia_corrosao",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        null=True,
                        verbose_name="Resistência à corrosão",
                    ),
                ),
                (
                    "requisito_resistencia",
                    models.TextField(
                        blank=True, null=True, verbose_name="Requisito resistência"
                    ),
                ),
                (
                    "prazo_resistencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo resistência"
                    ),
                ),
                (
                    "durabilidade",
                    models.CharField(
                        blank=True,
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        null=True,
                        verbose_name="Durabilidade/Ciclagem",
                    ),
                ),
                (
                    "requisito_durabilidade",
                    models.TextField(
                        blank=True, null=True, verbose_name="Requisito durabilidade"
                    ),
                ),
                (
                    "prazo_durabilidade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo durabilidade"
                    ),
                ),
                (
                    "observacao_geral",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observação Geral"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comercial.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comercial.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "precalculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comercial.precalculo",
                        verbose_name="Pré-Cálculo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
