# Generated by Django 4.2.16 on 2025-07-22 14:41

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0083_ordemdesenvolvimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemdesenvolvimento",
            name="observacao",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações"
            ),
        ),
        migrations.AlterField(
            model_name="ordemdesenvolvimento",
            name="observacao_geral",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações gerais"
            ),
        ),
    ]
