# Generated by Django 4.2.16 on 2025-07-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0084_alter_ordemdesenvolvimento_observacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemdesenvolvimento",
            name="requisito_durabilidade",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Requisito durabilidade",
            ),
        ),
        migrations.AlterField(
            model_name="ordemdesenvolvimento",
            name="requisito_resistencia",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Requisito resistência",
            ),
        ),
    ]
