# Generated by Django 4.2.16 on 2025-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comercial",
            "0085_alter_ordemdesenvolvimento_requisito_durabilidade_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="assinatura_comercial_data",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Assinatura Comercial – Data"
            ),
        ),
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="assinatura_comercial_email",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Assinatura Comercial – E-mail (CN)",
            ),
        ),
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="assinatura_comercial_nome",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Assinatura Comercial – Nome",
            ),
        ),
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="assinatura_tecnica_data",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Assinatura Técnica – Data"
            ),
        ),
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="assinatura_tecnica_email",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Assinatura Técnica – E-mail (CN)",
            ),
        ),
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="assinatura_tecnica_nome",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Assinatura Técnica – Nome",
            ),
        ),
    ]
