# Generated by Django 4.2.16 on 2025-07-23 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comercial", "0086_ordemdesenvolvimento_assinatura_comercial_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="usuario_comercial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="od_comercial",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="usuario_tecnico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="od_tecnico",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
