# Generated by Django 4.2.16 on 2025-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0087_ordemdesenvolvimento_usuario_comercial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculo",
            name="tipo_roteiro",
            field=models.CharField(
                choices=[
                    ("A", "Tipo A"),
                    ("B", "Tipo B"),
                    ("C", "Tipo C"),
                    ("D", "Tipo D"),
                ],
                default="A",
                max_length=1,
                verbose_name="Tipo de Roteiro",
            ),
        ),
    ]
