# Generated by Django 4.2.16 on 2025-07-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0088_precalculo_tipo_roteiro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precalculo",
            name="tipo_roteiro",
        ),
    ]
