# Generated by Django 4.2.16 on 2025-07-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0015_alter_roteiroproducao_item"),
        ("comercial", "0089_remove_precalculo_tipo_roteiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisecomercial",
            name="roteiro_selecionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tecnico.roteiroproducao",
                verbose_name="Roteiro Selecionado",
            ),
        ),
    ]
