# Generated by Django 4.2.16 on 2025-07-28 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comercial", "0090_analisecomercial_roteiro_selecionado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ativo", "Ativo"),
                    ("Inativo", "Inativo"),
                    ("Reativado", "Reativado"),
                ],
                default="Ativo",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ViabilidadeAnaliseRisco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="Nº Viabilidade"
                    ),
                ),
                (
                    "requisito_especifico",
                    models.BooleanField(
                        default=False, verbose_name="Requisito Específico Cliente?"
                    ),
                ),
                (
                    "automotivo_oem",
                    models.BooleanField(default=False, verbose_name="Automotivo OEM?"),
                ),
                (
                    "item_seguranca",
                    models.BooleanField(
                        default=False, verbose_name="É Item de Segurança?"
                    ),
                ),
                (
                    "codigo_desenho",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Código do Desenho",
                    ),
                ),
                (
                    "revisao",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Revisão"
                    ),
                ),
                (
                    "data_desenho",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Desenho"
                    ),
                ),
                (
                    "assinatura_comercial_nome",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Responsável Comercial – Nome",
                    ),
                ),
                (
                    "assinatura_comercial_departamento",
                    models.CharField(default="COMERCIAL", max_length=50),
                ),
                ("assinatura_comercial_data", models.DateField(blank=True, null=True)),
                (
                    "conclusao_comercial",
                    models.CharField(
                        choices=[
                            ("viavel", "Viável"),
                            ("alteracoes", "Viável com alterações"),
                            ("inviavel", "Inviável"),
                        ],
                        max_length=30,
                        verbose_name="Conclusão Comercial",
                    ),
                ),
                (
                    "consideracoes_comercial",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Considerações Comerciais"
                    ),
                ),
                (
                    "capacidade_fabricacao",
                    models.BooleanField(
                        default=False,
                        verbose_name="Existe capacidade adequada para fabricação?",
                    ),
                ),
                (
                    "custo_transformacao",
                    models.BooleanField(
                        default=False,
                        verbose_name="Custo com equipamentos de transformação?",
                    ),
                ),
                (
                    "custo_ferramental",
                    models.BooleanField(
                        default=False, verbose_name="Custo com ferramental?"
                    ),
                ),
                (
                    "metodo_alternativo",
                    models.BooleanField(
                        default=False, verbose_name="Método alternativo de manufatura?"
                    ),
                ),
                (
                    "risco_logistico",
                    models.BooleanField(
                        default=False, verbose_name="Risco logístico relevante?"
                    ),
                ),
                (
                    "conclusao_custos",
                    models.CharField(
                        choices=[
                            ("viavel", "Viável"),
                            ("alteracoes", "Viável com alterações"),
                            ("inviavel", "Inviável"),
                        ],
                        max_length=30,
                        verbose_name="Conclusão Custos",
                    ),
                ),
                (
                    "consideracoes_custos",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Considerações de Custos"
                    ),
                ),
                (
                    "responsavel_custos",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Responsável Custos",
                    ),
                ),
                (
                    "departamento_custos",
                    models.CharField(
                        default="CUSTOS", max_length=100, verbose_name="Departamento"
                    ),
                ),
                ("data_custos", models.DateField(blank=True, null=True)),
                (
                    "recursos_suficientes",
                    models.BooleanField(
                        default=False,
                        verbose_name="Recursos suficientes para manufatura?",
                    ),
                ),
                (
                    "atende_especificacoes",
                    models.BooleanField(
                        default=False,
                        verbose_name="Especificações de engenharia atendidas?",
                    ),
                ),
                (
                    "atende_tolerancias",
                    models.BooleanField(
                        default=False,
                        verbose_name="Pode ser fabricado conforme desenho?",
                    ),
                ),
                (
                    "capacidade_processo",
                    models.BooleanField(
                        default=False,
                        verbose_name="Capacidade do processo é suficiente?",
                    ),
                ),
                (
                    "permite_manuseio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Permite técnicas eficientes de manuseio?",
                    ),
                ),
                (
                    "precisa_cep",
                    models.BooleanField(
                        default=False,
                        verbose_name="Necessário controle estatístico do processo (CEP)?",
                    ),
                ),
                (
                    "cep_usado_similares",
                    models.BooleanField(
                        default=False, verbose_name="CEP já usado em similares?"
                    ),
                ),
                (
                    "processos_estaveis",
                    models.BooleanField(
                        default=False, verbose_name="Processos estão sob controle?"
                    ),
                ),
                (
                    "capabilidade_ok",
                    models.BooleanField(
                        default=False, verbose_name="Capabilidade atende requisitos?"
                    ),
                ),
                (
                    "atende_requisito_cliente",
                    models.BooleanField(
                        default=False,
                        verbose_name="Atende requisito específico do cliente?",
                    ),
                ),
                (
                    "risco_tecnico",
                    models.BooleanField(
                        default=False, verbose_name="Risco técnico relevante?"
                    ),
                ),
                (
                    "conclusao_tecnica",
                    models.CharField(
                        choices=[
                            ("viavel", "Viável"),
                            ("alteracoes", "Viável com alterações"),
                            ("inviavel", "Inviável"),
                        ],
                        max_length=30,
                        verbose_name="Conclusão Técnica",
                    ),
                ),
                (
                    "consideracoes_tecnicas",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Considerações Técnicas"
                    ),
                ),
                (
                    "responsavel_tecnica",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Responsável Técnico",
                    ),
                ),
                (
                    "departamento_tecnica",
                    models.CharField(
                        default="TÉCNICO", max_length=100, verbose_name="Departamento"
                    ),
                ),
                ("data_tecnica", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comercial.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "precalculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viabilidade_risco",
                        to="comercial.precalculo",
                    ),
                ),
            ],
        ),
    ]
