# Generated by Django 4.2.16 on 2025-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0091_alter_cliente_status_viabilidadeanaliserisco"),
    ]

    operations = [
        migrations.AddField(
            model_name="viabilidadeanaliserisco",
            name="codigo_brasmol",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Código Bras-Mol"
            ),
        ),
        migrations.AddField(
            model_name="viabilidadeanaliserisco",
            name="numero_peca",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nº da Peça"
            ),
        ),
    ]
