# Generated by Django 4.2.16 on 2025-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0092_viabilidadeanaliserisco_codigo_brasmol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viabilidadeanaliserisco",
            name="numero_peca",
        ),
        migrations.AddField(
            model_name="viabilidadeanaliserisco",
            name="produto_definido",
            field=models.BooleanField(
                default=False,
                verbose_name="O produto está devidamente definido (incluindo requisitos de aplicação, etc.) possibilitando a avaliação da viabilidade?",
            ),
        ),
        migrations.AddField(
            model_name="viabilidadeanaliserisco",
            name="risco_comercial",
            field=models.BooleanField(
                default=False,
                verbose_name="Existe algum risco comercial relevante aplicável a este produto e respectivo fornecimento, além do item apresentado acima?",
            ),
        ),
        migrations.AlterField(
            model_name="viabilidadeanaliserisco",
            name="codigo_brasmol",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código Bras-Mol"
            ),
        ),
    ]
