# Generated by Django 4.2.16 on 2025-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0093_remove_viabilidadeanaliserisco_numero_peca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viabilidadeanaliserisco",
            name="assinatura_comercial_departamento",
            field=models.CharField(
                blank=True,
                default="COMERCIAL",
                max_length=50,
                null=True,
                verbose_name="Departamento",
            ),
        ),
    ]
