# Generated by Django 4.2.16 on 2025-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comercial",
            "0094_alter_viabilidadeanaliserisco_assinatura_comercial_departamento",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="viabilidadeanaliserisco",
            name="assinatura_comercial_data",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="viabilidadeanaliserisco",
            name="data_custos",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="viabilidadeanaliserisco",
            name="data_tecnica",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
