# Generated by Django 4.2.16 on 2025-07-28 17:43

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "comercial",
            "0095_alter_viabilidadeanaliserisco_assinatura_comercial_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="precalculo",
            name="observacoes_precofinal",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações sobre o Preço Final"
            ),
        ),
    ]
