# Generated by Django 4.2.16 on 2025-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0096_precalculo_observacoes_precofinal"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="codigo_amostra",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código de Amostra"
            ),
        ),
    ]
