# Generated by Django 4.2.16 on 2025-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0097_item_codigo_amostra"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemdesenvolvimento",
            name="codigo_amostra",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código da Amostra"
            ),
        ),
    ]
