# Generated by Django 4.2.16 on 2025-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0098_ordemdesenvolvimento_codigo_amostra"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicadorComercialRegistroMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        choices=[
                            ("4.1", "Atendimento do Prazo de Cotação"),
                            ("4.2", "Número de Itens Novos Vendidos"),
                            ("4.3", "Número de Cotações por Funcionário"),
                            ("4.4", "Taxa de Orçamentos Aprovados"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField(blank=True, null=True)),
                ("trimestre", models.IntegerField(blank=True, null=True)),
                ("valor", models.FloatField()),
                ("media", models.FloatField()),
                ("meta", models.FloatField()),
                ("total_realizados", models.IntegerField(default=0)),
                ("total_aprovados", models.IntegerField(default=0)),
                ("comentario", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Registro de Indicador Comercial",
                "verbose_name_plural": "Registros de Indicadores Comerciais",
                "unique_together": {("indicador", "ano", "mes", "trimestre")},
            },
        ),
    ]
