# Generated by Django 4.2.16 on 2025-07-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0099_indicadorcomercialregistromensal"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="comprovante_adimplencia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="comprovantes_adimplencia/",
                verbose_name="Comprovante de Adimplência (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="status_adimplencia",
            field=models.CharField(
                choices=[
                    ("Adimplente", "Adimplente"),
                    ("Inadimplente", "Inadimplente"),
                ],
                default="Adimplente",
                max_length=20,
                verbose_name="Status de Adimplência",
            ),
        ),
    ]
