# Generated by Django 4.2.16 on 2025-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0101_alter_ordemdesenvolvimento_familia_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotacao",
            name="data_envio_proposta",
            field=models.DateField(
                blank=True,
                help_text="Data em que a proposta foi efetivamente gerada/enviada.",
                null=True,
                verbose_name="Data de Envio da Proposta",
            ),
        ),
    ]
