# Generated by Django 5.1.2 on 2024-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Alerta"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Alerta")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "destinatarios",
                    models.TextField(
                        verbose_name="Destinatários (e-mails separados por vírgula)"
                    ),
                ),
            ],
        ),
    ]
