# Generated by Django 4.2.16 on 2025-07-04 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("vencida", "Alerta de Calibração Vencida"),
                            ("proxima", "Alerta de Calibração Próxima"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Nome do Alerta",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Alerta")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "destinatarios",
                    models.TextField(
                        verbose_name="Destinatários (e-mails separados por vírgula)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("mensagem", models.TextField()),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                ("referencia_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "url_destino",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lido", models.BooleanField(default=False)),
                ("excluido", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertaConfigurado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("F045_GERADO", "Geração de F045"),
                            ("MANUTENCAO_PROXIMA", "Manutenção Próxima"),
                            ("MANUTENCAO_VENCIDA", "Manutenção Vencida"),
                            ("AVALIACAO_RISCO_PROXIMA", "Avaliação de Risco Próxima"),
                            ("AUDITORIA_PROXIMA", "Auditoria Próxima"),
                            ("CERTIFICACAO_PROXIMA", "Certificação Próxima"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("grupos", models.ManyToManyField(blank=True, to="auth.group")),
                (
                    "usuarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alertas_configurados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
