# Generated by Django 5.1.2 on 2024-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="destinatarios",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
