# Generated by Django 5.1.2 on 2024-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alter_alerta_ativo_alter_alerta_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="descricao",
            field=models.TextField(verbose_name="Descrição do Alerta"),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="destinatarios",
            field=models.TextField(
                verbose_name="Destinatários (e-mails separados por vírgula)"
            ),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="nome",
            field=models.CharField(
                choices=[
                    ("vencida", "Alerta de Calibração Vencida"),
                    ("proxima", "Alerta de Calibração Próxima"),
                ],
                max_length=100,
                unique=True,
                verbose_name="Nome do Alerta",
            ),
        ),
    ]
