# Generated by Django 4.2.16 on 2025-05-09 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("alerts", "0003_alter_alerta_ativo_alter_alerta_descricao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("mensagem", models.TextField()),
                ("lido", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertaConfigurado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("F045_GERADO", "Geração de F045")],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("grupos", models.ManyToManyField(blank=True, to="auth.group")),
                (
                    "usuarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alertas_configurados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
