# Generated by Django 4.2.16 on 2025-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_alertausuario_alertaconfigurado"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertausuario",
            name="referencia_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertausuario",
            name="tipo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="alertausuario",
            name="url_destino",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="alertaconfigurado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("F045_GERADO", "Geração de F045"),
                    ("MANUTENCAO_PROXIMA", "Manutenção Próxima"),
                    ("MANUTENCAO_VENCIDA", "Manutenção Vencida"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
