# Generated by Django 4.2.16 on 2025-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_alertausuario_referencia_id_alertausuario_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertaconfigurado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("F045_GERADO", "Geração de F045"),
                    ("MANUTENCAO_PROXIMA", "Manutenção Próxima"),
                    ("MANUTENCAO_VENCIDA", "Manutenção Vencida"),
                    ("AVALIACAO_RISCO_PROXIMA", "Avaliação de Risco Próxima"),
                    ("AUDITORIA_PROXIMA", "Auditoria Próxima"),
                    ("CERTIFICACAO_PROXIMA", "Certificação Próxima"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
