# Generated by Django 4.2.16 on 2025-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0006_alter_alertaconfigurado_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertausuario",
            name="excluido",
            field=models.BooleanField(default=False),
        ),
    ]
