# Generated by Django 4.2.16 on 2025-08-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0012_alter_alertaconfigurado_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertaconfigurado",
            name="exigir_confirmacao_modal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alertausuario",
            name="confirmado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertausuario",
            name="exige_confirmacao",
            field=models.BooleanField(default=False),
        ),
    ]
