# Generated by Django 4.2.16 on 2025-08-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0013_alertaconfigurado_exigir_confirmacao_modal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertaconfigurado",
            name="observacoes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações/Descrição"
            ),
        ),
    ]
