# Generated by Django 4.2.16 on 2025-09-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0014_alertaconfigurado_observacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertaconfigurado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("F045_GERADO", "Geração de F045"),
                    ("MANUTENCAO_PROXIMA", "Manutenção Próxima"),
                    ("MANUTENCAO_VENCIDA", "Manutenção Vencida"),
                    ("AVALIACAO_RISCO_PROXIMA", "Avaliação de Risco Próxima"),
                    ("AUDITORIA_PROXIMA", "Auditoria Próxima"),
                    ("CERTIFICACAO_PROXIMA", "Certificação Próxima"),
                    ("PRECALCULO_GERADO", "📄 Pré-Cálculo Gerado"),
                    ("AVALIACAO_TECNICA_PENDENTE", "🛠 Avaliação Técnica Pendente"),
                    ("RESPOSTA_COTACAO_MATERIAL", "📦 Resposta de Cotação de Material"),
                    ("RESPOSTA_COTACAO_SERVICO", "🛠 Resposta de Cotação de Serviço"),
                    (
                        "ROTEIRO_ATUALIZADO",
                        "🧵 Roteiro Atualizado — Definir Preço Final",
                    ),
                    (
                        "SOLICITACAO_COTACAO_MATERIAL",
                        "📨 Solicitação de Cotação de Material",
                    ),
                    (
                        "SOLICITACAO_COTACAO_SERVICO",
                        "📨 Solicitação de Cotação de Serviço",
                    ),
                    (
                        "ORDEM_DESENVOLVIMENTO_CRIADA",
                        "🆕 Nova Ordem de Desenvolvimento Criada",
                    ),
                    ("VIABILIDADE_CRIADA", "🆕 Nova Viabilidade Criada"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
