# Generated by Django 5.1.2 on 2024-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_admissao", models.DateField()),
                ("cargo_inicial", models.CharField(max_length=100)),
                ("cargo_atual", models.CharField(max_length=100)),
                ("numero_registro", models.CharField(max_length=20, unique=True)),
                ("local_trabalho", models.CharField(max_length=100)),
                ("data_integracao", models.DateField()),
                ("responsavel", models.CharField(max_length=100)),
                ("cargo_responsavel", models.CharField(max_length=100)),
                ("escolaridade", models.CharField(max_length=100)),
            ],
        ),
    ]
