# Generated by Django 5.1.2 on 2024-10-22 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cbo", models.CharField(max_length=20)),
                (
                    "descricao_arquivo",
                    models.FileField(blank=True, null=True, upload_to="cargos/"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_admissao", models.DateField()),
                ("numero_registro", models.CharField(max_length=20, unique=True)),
                ("local_trabalho", models.CharField(max_length=100)),
                ("data_integracao", models.DateField()),
                ("responsavel", models.CharField(max_length=100)),
                ("escolaridade", models.CharField(max_length=100)),
                (
                    "cargo_atual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_atual_funcionarios",
                        to="Funcionario.cargo",
                    ),
                ),
                (
                    "cargo_inicial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_inicial_funcionarios",
                        to="Funcionario.cargo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_revisao", models.CharField(max_length=20)),
                ("data_revisao", models.DateField(default=django.utils.timezone.now)),
                ("descricao_mudanca", models.TextField()),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisoes",
                        to="Funcionario.cargo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("interno", "Interno"), ("externo", "Externo")],
                        max_length=50,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("capacitacao", "Capacitação"),
                            ("tecnico", "Técnico"),
                            ("graduacao", "Graduação"),
                        ],
                        max_length=100,
                    ),
                ),
                ("nome_curso", models.CharField(max_length=255)),
                (
                    "instituicao_ensino",
                    models.CharField(default="Não Informada", max_length=255),
                ),
                ("concluido", models.BooleanField(default=False)),
                ("cursando", models.BooleanField(default=False)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("carga_horaria", models.CharField(max_length=50)),
                ("anexo", models.FileField(blank=True, null=True, upload_to="anexos/")),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treinamentos",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
