# Generated by Django 5.1.2 on 2024-10-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treinamento",
            name="concluido",
        ),
        migrations.RemoveField(
            model_name="treinamento",
            name="cursando",
        ),
        migrations.AddField(
            model_name="treinamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluido", "Concluído"),
                    ("trancado", "Trancado"),
                    ("cursando", "Cursando"),
                ],
                default="cursando",
                max_length=50,
            ),
        ),
    ]
