# Generated by Django 4.2.16 on 2025-07-04 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Funcionario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portaria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bancohoras",
            name="ocorrencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banco_relacionado",
                to="portaria.atrasosaida",
                verbose_name="Ocorrência (Atraso/Saída)",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_1",
                to="Funcionario.funcionario",
                verbose_name="Responsável 1",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_2",
                to="Funcionario.funcionario",
                verbose_name="Responsável 2",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_3",
                to="Funcionario.funcionario",
                verbose_name="Responsável 3",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="treinamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="Funcionario.treinamento",
                verbose_name="Treinamento",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaoexperiencia",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaoanual",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AddField(
            model_name="atualizacaolida",
            name="atualizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.atualizacaosistema",
                verbose_name="Atualização",
            ),
        ),
        migrations.AddField(
            model_name="atualizacaolida",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="departamentos",
            field=models.ManyToManyField(
                blank=True,
                related_name="atividades_departamentos",
                to="Funcionario.departamentos",
                verbose_name="Departamentos",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="revisaodocleitura",
            unique_together={("revisao", "usuario")},
        ),
        migrations.AlterUniqueTogether(
            name="nota",
            unique_together={("matriz", "funcionario", "atividade")},
        ),
        migrations.AlterUniqueTogether(
            name="atualizacaolida",
            unique_together={("usuario", "atualizacao")},
        ),
    ]
