# Generated by Django 5.1.2 on 2024-10-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargo",
            name="descricao",
        ),
        migrations.AddField(
            model_name="cargo",
            name="cbo",
            field=models.CharField(default="0000-00", max_length=20),
        ),
        migrations.AddField(
            model_name="cargo",
            name="data_ultima_atualizacao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cargo",
            name="descricao_arquivo",
            field=models.FileField(blank=True, null=True, upload_to="descriptions/"),
        ),
        migrations.AddField(
            model_name="cargo",
            name="numero_revisao",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
