# Generated by Django 5.1.2 on 2024-10-21 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0002_remove_cargo_descricao_cargo_cbo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="cbo",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="data_ultima_atualizacao",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.CreateModel(
            name="Revisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_revisao", models.CharField(max_length=10)),
                ("data_revisao", models.DateField(default=django.utils.timezone.now)),
                ("descricao_mudanca", models.TextField()),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisoes",
                        to="Funcionario.cargo",
                    ),
                ),
            ],
        ),
    ]
