# Generated by Django 5.1.2 on 2024-10-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0002_remove_treinamento_concluido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="cargo_responsavel",
            field=models.CharField(default="teste", max_length=100),
            preserve_default=False,
        ),
    ]
