# Generated by Django 5.1.2 on 2024-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0003_funcionario_cargo_responsavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
