# Generated by Django 5.1.2 on 2024-10-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0004_funcionario_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="curriculo",
            field=models.FileField(
                blank=True, null=True, upload_to="curriculos_funcionarios/"
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="fotos_funcionarios/"
            ),
        ),
    ]
