# Generated by Django 5.1.2 on 2024-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0005_funcionario_curriculo_funcionario_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treinamento",
                    models.CharField(
                        choices=[
                            ("Treinamento", "Treinamento"),
                            ("Curso", "Curso"),
                            ("Divulgacao", "Divulgação"),
                        ],
                        max_length=255,
                    ),
                ),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                ("instrutor", models.CharField(max_length=255)),
                ("duracao", models.DecimalField(decimal_places=2, max_digits=5)),
                ("necessita_avaliacao", models.BooleanField(default=False)),
                (
                    "lista_presenca",
                    models.FileField(
                        blank=True, null=True, upload_to="listas_presenca/"
                    ),
                ),
                (
                    "participantes",
                    models.ManyToManyField(
                        related_name="participantes", to="Funcionario.funcionario"
                    ),
                ),
            ],
        ),
    ]
