# Generated by Django 5.1.2 on 2024-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0006_listapresenca"),
    ]

    operations = [
        migrations.AddField(
            model_name="listapresenca",
            name="data_realizacao",
            field=models.DateField(default="2024-01-01"),
            preserve_default=False,
        ),
    ]
