# Generated by Django 5.1.2 on 2024-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0007_listapresenca_data_realizacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listapresenca",
            name="data_realizacao",
            field=models.DateField(default="2024-01-01"),
        ),
    ]
