# Generated by Django 5.1.2 on 2024-10-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0008_alter_listapresenca_data_realizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="listapresenca",
            name="assunto",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="listapresenca",
            name="descricao",
            field=models.TextField(default="Sem assunto"),
            preserve_default=False,
        ),
    ]
