# Generated by Django 5.1.2 on 2024-10-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0009_listapresenca_assunto_listapresenca_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.DecimalField(decimal_places=2, max_digits=5)),
                ("comentarios", models.TextField(blank=True, null=True)),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "treinamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funcionario.treinamento",
                    ),
                ),
            ],
        ),
    ]
