# Generated by Django 5.1.2 on 2024-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0010_avaliacaotreinamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="avaliacao_geral",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="descricao_melhorias",
            field=models.TextField(default="Nenhuma melhoria descrita"),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="pergunta_1",
            field=models.IntegerField(
                choices=[
                    (1, "Opção 1"),
                    (2, "Opção 2"),
                    (3, "Opção 3"),
                    (4, "Opção 4"),
                    (5, "Opção 5"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="pergunta_2",
            field=models.IntegerField(
                choices=[
                    (1, "Opção 1"),
                    (2, "Opção 2"),
                    (3, "Opção 3"),
                    (4, "Opção 4"),
                    (5, "Opção 5"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="pergunta_3",
            field=models.IntegerField(
                choices=[
                    (1, "Opção 1"),
                    (2, "Opção 2"),
                    (3, "Opção 3"),
                    (4, "Opção 4"),
                    (5, "Opção 5"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_1_cargo",
            field=models.CharField(default="Não especificado", max_length=100),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_1_nome",
            field=models.CharField(default="Não especificado", max_length=100),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_2_cargo",
            field=models.CharField(default="Não especificado", max_length=100),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_2_nome",
            field=models.CharField(default="Não especificado", max_length=100),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_3_cargo",
            field=models.CharField(default="Não especificado", max_length=100),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_3_nome",
            field=models.CharField(default="Não especificado", max_length=100),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="data_avaliacao",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="nota",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=3
            ),
        ),
    ]
