# Generated by Django 5.1.2 on 2024-10-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0011_avaliacaotreinamento_avaliacao_geral_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="comentarios",
        ),
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="nota",
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="avaliacao_geral",
            field=models.IntegerField(
                choices=[
                    (1, "Pouco eficaz"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "Muito eficaz"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_1",
            field=models.IntegerField(
                choices=[
                    (
                        1,
                        "Não possui conhecimento mínimo da metodologia para sua aplicação.",
                    ),
                    (
                        2,
                        "Apresenta deficiências nos conceitos, o que compromete a aplicação.",
                    ),
                    (
                        3,
                        "Possui noções básicas, mas necessita de acompanhamento e suporte na aplicação.",
                    ),
                    (
                        4,
                        "Possui domínio necessário da metodologia e a utiliza adequadamente.",
                    ),
                    (
                        5,
                        "Possui completo domínio e utiliza a metodologia com excelência.",
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_2",
            field=models.IntegerField(
                choices=[
                    (1, "Está muito abaixo do esperado."),
                    (2, "Aplicação está abaixo do esperado."),
                    (3, "Aplicação é razoável, mas não dentro do esperado."),
                    (4, "Aplicação está adequada e corresponde às expectativas."),
                    (5, "Aplicação excede as expectativas."),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_3",
            field=models.IntegerField(
                choices=[
                    (1, "Nenhum resultado foi obtido efetivamente até o momento."),
                    (2, "As melhorias obtidas estão muito abaixo do esperado."),
                    (
                        3,
                        "As melhorias obtidas são consideráveis, mas não dentro do esperado.",
                    ),
                    (4, "As melhorias obtidas são boas e estão dentro do esperado."),
                    (5, "As melhorias obtidas excederam as expectativas."),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_1_cargo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_1_nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_2_cargo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_2_nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_3_cargo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_3_nome",
            field=models.CharField(max_length=100),
        ),
    ]
