# Generated by Django 5.1.2 on 2024-10-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0012_remove_avaliacaotreinamento_comentarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="periodo_avaliacao",
            field=models.IntegerField(default=60),
        ),
    ]
