# Generated by Django 5.1.2 on 2024-10-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0013_avaliacaotreinamento_periodo_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="treinamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.listapresenca",
            ),
        ),
    ]
