# Generated by Django 5.1.2 on 2024-10-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0014_alter_avaliacaotreinamento_treinamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="treinamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="Funcionario.listapresenca",
            ),
        ),
        migrations.CreateModel(
            name="AvaliacaoDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("EXPERIENCIA", "Experiência"), ("ANUAL", "Anual")],
                        max_length=20,
                    ),
                ),
                ("data_avaliacao", models.DateField()),
                ("departamento", models.CharField(max_length=100)),
                (
                    "centro_custo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nota_postura_seguranca", models.PositiveIntegerField()),
                ("nota_qualidade_produtividade", models.PositiveIntegerField()),
                ("nota_trabalho_equipe", models.PositiveIntegerField()),
                ("nota_comprometimento", models.PositiveIntegerField()),
                ("nota_disponibilidade_mudancas", models.PositiveIntegerField()),
                ("nota_disciplina", models.PositiveIntegerField()),
                ("nota_rendimento_pressao", models.PositiveIntegerField()),
                ("nota_proatividade", models.PositiveIntegerField()),
                ("nota_comunicacao", models.PositiveIntegerField()),
                ("nota_assiduidade", models.PositiveIntegerField()),
                ("avaliacao_global_avaliador", models.TextField()),
                ("avaliacao_global_avaliado", models.TextField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "avaliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliado",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliador",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funcionario.cargo",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
