# Generated by Django 5.1.2 on 2024-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0015_alter_avaliacaotreinamento_treinamento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="avaliacao_global_avaliado",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="avaliacao_global_avaliador",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="cargo",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_assiduidade",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_comprometimento",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_comunicacao",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_disciplina",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_disponibilidade_mudancas",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_postura_seguranca",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_proatividade",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_qualidade_produtividade",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_rendimento_pressao",
        ),
        migrations.RemoveField(
            model_name="avaliacaodesempenho",
            name="nota_trabalho_equipe",
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="assiduidade",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="comprometimento",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="comunicacao",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="disciplina",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="disponibilidade_para_mudancas",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="gerencia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="orientacao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="postura_seg_trabalho",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="proatividade",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="qualidade_produtividade",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="rendimento_sob_pressao",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="trabalho_em_equipe",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="avaliacaodesempenho",
            name="tipo",
            field=models.CharField(
                choices=[("EXPERIENCIA", "Experiência"), ("ANUAL", "Anual")],
                max_length=15,
            ),
        ),
    ]
