# Generated by Django 5.1.2 on 2024-10-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0018_alter_avaliacaodesempenho_assiduidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="formulario_f146",
            field=models.FileField(
                blank=True, null=True, upload_to="formularios_f146/"
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="status",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=10,
            ),
        ),
    ]
