# Generated by Django 5.1.2 on 2024-10-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0019_funcionario_formulario_f146_funcionario_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cargo",
            old_name="cbo",
            new_name="numero_dc",
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treinamentos",
                to="Funcionario.funcionario",
            ),
        ),
    ]
