# Generated by Django 5.1.2 on 2024-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0020_rename_cbo_cargo_numero_dc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaodesempenho",
            name="avaliacao_geral",
            field=models.IntegerField(
                choices=[
                    (1, "Pouco eficaz"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "Muito eficaz"),
                ],
                default=3,
            ),
        ),
    ]
