# Generated by Django 5.1.2 on 2024-10-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0021_avaliacaodesempenho_avaliacao_geral"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRotationEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_atual", models.CharField(blank=True, max_length=100)),
                ("competencias", models.TextField(blank=True)),
                ("ultima_avaliacao", models.DateField(blank=True, null=True)),
                (
                    "status_avaliacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cursos_realizados", models.JSONField(blank=True, default=list)),
                ("escolaridade", models.CharField(blank=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("data_inicio", models.DateField()),
                ("termino_previsto", models.DateField(editable=False)),
                ("descricao_cargo", models.TextField(blank=True)),
                ("treinamentos_requeridos", models.TextField(blank=True)),
                ("treinamentos_propostos", models.TextField(blank=True)),
                ("avaliacao_gestor", models.TextField(blank=True)),
                ("avaliacao_funcionario", models.TextField(blank=True)),
                (
                    "avaliacao_rh",
                    models.CharField(
                        choices=[
                            ("Apto", "Apto"),
                            ("Inapto", "Inapto"),
                            ("Prorrogar TN", "Prorrogar TN"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dias_prorrogacao",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("disponibilidade_vaga", models.BooleanField(default=False)),
                (
                    "cargo_atual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_rotation_evaluations_cargo",
                        to="Funcionario.cargo",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_rotation_evaluations",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "gestor_responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gestor_responsavel",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "nova_funcao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nova_funcao",
                        to="Funcionario.cargo",
                    ),
                ),
            ],
        ),
    ]
