# Generated by Django 5.1.2 on 2024-10-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0022_jobrotationevaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="nova_funcao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nova_funcao",
                to="Funcionario.cargo",
            ),
        ),
    ]
