# Generated by Django 5.1.2 on 2024-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0023_alter_jobrotationevaluation_nova_funcao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="termino_previsto",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
