# Generated by Django 5.1.2 on 2024-10-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0024_alter_jobrotationevaluation_termino_previsto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="area",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="area_atual",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="cargo_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_rotation_evaluations_cargo",
                to="Funcionario.cargo",
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="competencias",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="cursos_realizados",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="descricao_cargo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="escolaridade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
