# Generated by Django 5.1.2 on 2024-10-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0025_alter_jobrotationevaluation_area_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobrotationevaluation",
            old_name="ultima_avaliacao",
            new_name="data_ultima_avaliacao",
        ),
        migrations.RenameField(
            model_name="jobrotationevaluation",
            old_name="status_avaliacao",
            new_name="status_ultima_avaliacao",
        ),
    ]
