# Generated by Django 5.1.2 on 2024-10-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Funcionario",
            "0026_rename_ultima_avaliacao_jobrotationevaluation_data_ultima_avaliacao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="status_ultima_avaliacao",
            field=models.CharField(
                blank=True,
                help_text="Status da última avaliação de desempenho",
                max_length=50,
                null=True,
            ),
        ),
    ]
