# Generated by Django 5.1.2 on 2024-11-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0027_alter_jobrotationevaluation_status_ultima_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="numero_dc",
            field=models.CharField(max_length=4),
        ),
    ]
