# Generated by Django 5.1.2 on 2024-11-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0028_alter_cargo_numero_dc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treinamento",
            name="instituicao_ensino",
            field=models.CharField(max_length=255),
        ),
    ]
