# Generated by Django 5.1.2 on 2024-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0029_alter_treinamento_instituicao_ensino"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="experiencia_profissional",
            field=models.CharField(
                choices=[
                    (
                        "Sim",
                        "Sim, (Anexar Curriculum ou cópia da Carteira Profissional no prontuário)",
                    ),
                    (
                        "Não",
                        "Não, (Justificar através da Avaliação Prática da Atividade, devidamente assinada)",
                    ),
                ],
                default="Sim",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="escolaridade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
