# Generated by Django 5.1.2 on 2024-11-05 14:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0030_funcionario_experiencia_profissional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listapresenca",
            name="descricao",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
