# Generated by Django 5.1.2 on 2024-11-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0031_alter_listapresenca_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="responsavel_1_cargo",
        ),
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="responsavel_1_nome",
        ),
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="responsavel_2_cargo",
        ),
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="responsavel_2_nome",
        ),
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="responsavel_3_cargo",
        ),
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="responsavel_3_nome",
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_1",
                to="Funcionario.funcionario",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_2",
                to="Funcionario.funcionario",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="responsavel_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_3",
                to="Funcionario.funcionario",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="avaliacao_geral",
            field=models.IntegerField(
                choices=[
                    (1, "Pouco eficaz"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "Muito eficaz"),
                ]
            ),
        ),
    ]
