# Generated by Django 5.1.2 on 2024-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0033_alter_avaliacaotreinamento_avaliacao_geral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treinamento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("capacitacao", "Capacitação"),
                    ("tecnico", "Técnico"),
                    ("graduacao", "Graduação"),
                    ("treinamento", "Treinamento"),
                ],
                max_length=100,
            ),
        ),
    ]
