# Generated by Django 5.1.2 on 2024-11-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0034_alter_treinamento_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaoanual",
            name="avaliacao_geral",
            field=models.IntegerField(
                choices=[
                    (1, "Pouco eficaz"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "Muito eficaz"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="avaliacaoexperiencia",
            name="avaliado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliado_experiencia",
                to="Funcionario.funcionario",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaoexperiencia",
            name="avaliador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes_experiencia",
                to="Funcionario.funcionario",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaoexperiencia",
            name="orientacao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="assiduidade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="avaliador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes_anual",
                to="Funcionario.funcionario",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="comprometimento",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="comunicacao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="disciplina",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="disponibilidade_para_mudancas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="postura_seg_trabalho",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="proatividade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="qualidade_produtividade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="rendimento_sob_pressao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="trabalho_em_equipe",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AvaliacaoDesempenho",
        ),
    ]
