# Generated by Django 5.1.2 on 2024-11-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0035_avaliacaoanual_avaliacao_geral_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacaoanual",
            name="avaliado",
        ),
        migrations.RemoveField(
            model_name="avaliacaoanual",
            name="avaliador",
        ),
        migrations.RemoveField(
            model_name="avaliacaoanual",
            name="gerencia",
        ),
    ]
