# Generated by Django 5.1.2 on 2024-11-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0036_remove_avaliacaoanual_avaliado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avaliacaoanual",
            old_name="observacoes",
            new_name="avaliacao_global_avaliador",
        ),
        migrations.RemoveField(
            model_name="avaliacaoanual",
            name="avaliacao_geral",
        ),
        migrations.AddField(
            model_name="avaliacaoanual",
            name="avaliacao_global_avaliado",
            field=models.TextField(blank=True, null=True),
        ),
    ]
