# Generated by Django 5.1.2 on 2024-11-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Funcionario",
            "0037_rename_observacoes_avaliacaoanual_avaliacao_global_avaliador_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrotationevaluation",
            name="dias_prorrogacao",
        ),
    ]
