# Generated by Django 5.1.2 on 2024-11-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0038_remove_jobrotationevaluation_dias_prorrogacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="avaliacao_rh",
            field=models.CharField(
                choices=[
                    ("Apto", "Apto"),
                    ("Inapto", "Inapto"),
                    ("Em Andamento", "Em Andamento"),
                    ("Prorrogar TN", "Prorrogar TN"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="status_ultima_avaliacao",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
