# Generated by Django 5.1.2 on 2024-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0039_alter_jobrotationevaluation_avaliacao_rh_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobrotationevaluation",
            old_name="area_atual",
            new_name="local_trabalho",
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="avaliacao_rh",
            field=models.CharField(
                choices=[
                    ("Apto", "Apto"),
                    ("Inapto", "Inapto"),
                    ("Prorrogar TN", "Prorrogar TN"),
                    ("EmProgresso", "Em Progresso"),
                ],
                max_length=20,
            ),
        ),
    ]
