# Generated by Django 5.1.2 on 2024-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0041_comunicado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicado",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
