# Generated by Django 5.1.2 on 2024-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0043_alter_comunicado_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtualizacaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("previsao", models.DateField()),
            ],
        ),
    ]
