# Generated by Django 5.1.2 on 2024-11-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0044_atualizacaosistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicado",
            name="lista_assinaturas",
            field=models.FileField(blank=True, null=True, upload_to="assinaturas/"),
        ),
    ]
