# Generated by Django 5.1.2 on 2024-11-13 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0045_comunicado_lista_assinaturas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="cargo_atual",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_atual_funcionarios",
                to="Funcionario.cargo",
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluido", "Concluído"),
                    ("trancado", "Trancado"),
                    ("cursando", "Cursando"),
                    ("requirido", "Requirido"),
                ],
                default="cursando",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="IntegracaoFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo_whatsapp", models.BooleanField(default=False)),
                ("requer_treinamento", models.BooleanField(default=False)),
                ("treinamentos_requeridos", models.TextField(blank=True, null=True)),
                (
                    "data_integracao",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
