# Generated by Django 5.1.2 on 2024-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0046_alter_funcionario_cargo_atual_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_empresa",
                    models.CharField(
                        default="BRAS-MOL MOLAS & ESTAMPADOS LTDA", max_length=100
                    ),
                ),
                ("cep", models.CharField(default="08579000", max_length=20)),
                (
                    "endereco",
                    models.CharField(
                        default="BONSUCESSO, DO, 1961 - RIO ABAIXO - Itaquaquecetuba / SP",
                        max_length=150,
                    ),
                ),
                ("telefone", models.CharField(default="1146482611", max_length=20)),
                (
                    "email",
                    models.EmailField(default="rh@brasmol.com.br", max_length=254),
                ),
                ("cnpj", models.CharField(default="61.296.901/0002-48", max_length=20)),
                (
                    "logo_claro",
                    models.ImageField(blank=True, null=True, upload_to="logos/"),
                ),
                (
                    "logo_escuro",
                    models.ImageField(blank=True, null=True, upload_to="logos/"),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
            },
        ),
    ]
