# Generated by Django 5.1.2 on 2024-11-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0047_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="atualizacaosistema",
            name="versao",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
