# Generated by Django 5.1.2 on 2024-11-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0049_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("avaliacao_desempenho", "Avaliação de Desempenho"),
                    ("feriado", "Feriado"),
                    ("ponte", "Ponte"),
                    ("confraternizacao", "Confraternização"),
                    ("recesso", "Recesso"),
                    ("auditoria_sgs", "Auditoria SGS"),
                    ("auditoria_interna", "Auditoria Interna"),
                    ("sipat", "SIPAT"),
                    ("inventario", "Inventário"),
                ],
                default="avaliacao_desempenho",
                max_length=20,
            ),
        ),
    ]
