# Generated by Django 5.1.2 on 2024-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0050_evento_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="data_fim",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_inicio",
            field=models.DateField(),
        ),
    ]
