# Generated by Django 5.1.2 on 2024-11-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0051_alter_evento_data_fim_alter_evento_data_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="atualizacaosistema",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluido", "Concluído"),
                    ("em_andamento", "Em andamento"),
                    ("cancelado", "Cancelado"),
                ],
                default="em_andamento",
                max_length=15,
            ),
        ),
    ]
