# Generated by Django 5.1.2 on 2024-11-21 14:01

import Funcionario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0052_atualizacaosistema_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="integracaofuncionario",
            name="pdf_integracao",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="integracoes/",
                verbose_name="PDF da Integração Assinada",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="curriculo",
            field=models.FileField(
                blank=True, null=True, upload_to='Funcionario.models.funcionario.renomear_curriculo'
 

            ),
        ),
    ]
