# Generated by Django 5.1.2 on 2024-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0053_integracaofuncionario_pdf_integracao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treinamento",
            name="anexo",
            field=models.FileField(blank=True, null=True, upload_to="certificados/"),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="nome_curso",
            field=models.CharField(max_length=100),
        ),
    ]
