# Generated by Django 5.1.2 on 2024-11-22 15:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0053_integracaofuncionario_pdf_integracao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinamento",
            name="descricao",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="anexo",
            field=models.FileField(blank=True, null=True, upload_to="certificados/"),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="nome_curso",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluido", "Concluído"),
                    ("trancado", "Trancado"),
                    ("cursando", "Cursando"),
                    ("requerido", "Requerido"),
                ],
                default="cursando",
                max_length=50,
            ),
        ),
    ]
