# Generated by Django 5.1.2 on 2024-11-21 14:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0054_alter_treinamento_anexo_alter_treinamento_nome_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinamento",
            name="descricao",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
