# Generated by Django 5.1.2 on 2024-11-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0054_remove_avaliacaoexperiencia_avaliado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrizPolivalencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_trabalho", models.CharField(max_length=255)),
                ("observacoes", models.CharField(max_length=50)),
                ("atividades", models.JSONField()),
                ("atualizado_em", models.DateTimeField()),
                (
                    "colaboradores",
                    models.ManyToManyField(
                        related_name="colaboradores_matriz",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "coordenacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordenacao_matriz",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "elaboracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elaboracao_matriz",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "validacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validacao_matriz",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
