# Generated by Django 5.1.2 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0055_treinamento_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacaoexperiencia",
            name="avaliado",
        ),
        migrations.RemoveField(
            model_name="avaliacaoexperiencia",
            name="avaliador",
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluido", "Concluído"),
                    ("trancado", "Trancado"),
                    ("cursando", "Cursando"),
                    ("requerido", "Requerido"),
                ],
                default="cursando",
                max_length=50,
            ),
        ),
    ]
