# Generated by Django 5.1.2 on 2024-11-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ("Funcionario", "0053_integracaofuncionario_pdf_integracao_and_more"),
]


    operations = [
        migrations.RemoveField(
            model_name="avaliacaoexperiencia",
            name="avaliado",
        ),
        migrations.RemoveField(
            model_name="avaliacaoexperiencia",
            name="avaliador",
        ),
    ]
