# Generated by Django 5.1.2 on 2024-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0056_remove_avaliacaoexperiencia_avaliado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinamento",
            name="situacao",
            field=models.CharField(
                blank=True,
                choices=[("aprovado", "Aprovado"), ("reprovado", "Reprovado")],
                help_text="Campo exibido apenas para treinamentos requeridos.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("capacitacao", "Capacitação"),
                    ("tecnico", "Técnico"),
                    ("graduacao", "Graduação"),
                    ("pos-graduacao", "Pos-graduacao"),
                    ("treinamento", "Treinamento"),
                    ("divulgacao", "Divulgação"),
                ],
                max_length=100,
            ),
        ),
    ]
