# Generated by Django 5.1.2 on 2024-11-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0057_treinamento_situacao_alter_treinamento_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="listapresenca",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("finalizado", "Finalizado"),
                    ("em_andamento", "Em Andamento"),
                ],
                default="em_andamento",
                max_length=20,
            ),
        ),
    ]
