# Generated by Django 5.1.2 on 2024-11-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0058_listapresenca_situacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listapresenca",
            name="data_realizacao",
        ),
        migrations.AddField(
            model_name="listapresenca",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listapresenca",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
