# Generated by Django 4.2.16 on 2024-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0059_remove_listapresenca_data_realizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='instituicao_ensino',
            field=models.CharField(default='Bras-Mol', max_length=255),
        ),
    ]
