# Generated by Django 5.1.2 on 2024-11-25 19:28

import Funcionario.models.funcionario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0060_alter_treinamento_instituicao_ensino"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="curriculo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.funcionario.renomear_curriculo,
            ),
        ),
    ]
