# Generated by Django 5.1.2 on 2024-11-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0054_remove_avaliacaoexperiencia_avaliado_and_more"),
        ("Funcionario", "0061_alter_funcionario_curriculo"),
    ]

    operations = []
