# Generated by Django 5.1.2 on 2024-11-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0062_merge_20241127_0850"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome da Atividade"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da Atividade"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrizPolivalencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "coordenacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordenacao_matriz",
                        to="Funcionario.funcionario",
                        verbose_name="Coordenação",
                    ),
                ),
                (
                    "elaboracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elaboracao_matriz",
                        to="Funcionario.funcionario",
                        verbose_name="Elaboração",
                    ),
                ),
                (
                    "validacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validacao_matriz",
                        to="Funcionario.funcionario",
                        verbose_name="Validação",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pontuacao",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Aprendiz"),
                            (2, "Assistente"),
                            (3, "Autônomo"),
                            (4, "Instrutor"),
                        ],
                        verbose_name="Pontuação",
                    ),
                ),
                (
                    "suplente",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="É Suplente",
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="Funcionario.atividade",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
            options={
                "unique_together": {("funcionario", "atividade")},
            },
        ),
    ]
