# Generated by Django 5.1.2 on 2024-11-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0063_atividade_matrizpolivalencia_nota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atividade",
            name="descricao",
        ),
    ]
