# Generated by Django 5.1.2 on 2024-11-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0065_alter_matrizpolivalencia_coordenacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="suplente",
            field=models.BooleanField(default=False, verbose_name="É Suplente"),
        ),
    ]
