# Generated by Django 5.1.2 on 2024-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0067_alter_nota_pontuacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treinamento",
            name="funcionario",
        ),
        migrations.AddField(
            model_name="treinamento",
            name="funcionarios",
            field=models.ManyToManyField(
                related_name="treinamentos", to="Funcionario.funcionario"
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("capacitacao", "Capacitação"),
                    ("tecnico", "Técnico"),
                    ("graduacao", "Graduação"),
                    ("pos-graduacao", "Pos-graduação"),
                    ("treinamento", "Treinamento"),
                    ("divulgacao", "Divulgação"),
                ],
                max_length=100,
            ),
        ),
    ]
