# Generated by Django 5.1.2 on 2024-11-29 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0068_remove_treinamento_funcionario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicadorDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        default="2.3 - Horas de Treinamento por Funcionário",
                        max_length=200,
                    ),
                ),
                ("objetivo", models.TextField()),
                ("meta", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicadores_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanoAcaoMelhoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.TextField(verbose_name="Ação Corretiva / Melhoria")),
                ("prazo", models.PositiveIntegerField(verbose_name="Prazo em dias")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("Em andamento", "Em andamento"),
                            ("Finalizado", "Finalizado"),
                        ],
                        default="Em andamento",
                        max_length=20,
                    ),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_acao",
                        to="Funcionario.indicadordesempenho",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
