# Generated by Django 5.1.2 on 2024-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0069_indicadordesempenho_planoacaomelhoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planoacaomelhoria",
            name="indicador",
        ),
        migrations.RemoveField(
            model_name="planoacaomelhoria",
            name="responsavel",
        ),
        migrations.AddField(
            model_name="treinamento",
            name="planejado",
            field=models.CharField(
                choices=[("sim", "Sim"), ("nao", "Não")],
                default="nao",
                max_length=3,
                verbose_name="Planejado",
            ),
        ),
        migrations.DeleteModel(
            name="IndicadorDesempenho",
        ),
        migrations.DeleteModel(
            name="PlanoAcaoMelhoria",
        ),
    ]
