# Generated by Django 5.1.2 on 2024-12-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0070_remove_planoacaomelhoria_indicador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="treinamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="Funcionario.treinamento",
            ),
        ),
    ]
