# Generated by Django 5.1.2 on 2024-12-02 18:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0071_alter_avaliacaotreinamento_treinamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="descricao",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
