# Generated by Django 5.1.2 on 2024-12-02 18:28
from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field  # Import correto do CKEditor 5


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0071_alter_avaliacaotreinamento_treinamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="descricao",
            field=CKEditor5Field("default"),
        ),
    ]
