# Generated by Django 5.1.2 on 2024-12-02 18:38

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0072_alter_atualizacaosistema_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="atualizacaosistema",
            name="data_termino",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="descricao",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
