# Generated by Django 5.1.2 on 2024-12-03 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0073_atualizacaosistema_data_termino_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="data_termino",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
