# Generated by Django 5.1.2 on 2024-12-03 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0074_alter_atualizacaosistema_data_termino"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=4)),
                (
                    "arquivo",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=15,
                    ),
                ),
                (
                    "responsavel_recuperacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="Funcionario.cargo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevisaoDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_revisao", models.CharField(max_length=20)),
                ("data_revisao", models.DateField(default=django.utils.timezone.now)),
                ("descricao_mudanca", models.TextField()),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisoes",
                        to="Funcionario.documento",
                    ),
                ),
            ],
        ),
    ]
