# Generated by Django 5.1.2 on 2024-12-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0076_revisaodoc_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="responsavel",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
