# Generated by Django 5.1.2 on 2024-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0078_alter_funcionario_data_integracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="status",
            field=models.CharField(
                choices=[
                    ("aprovado", "Aprovado"),
                    ("em_revisao", "Em Revisão"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="em_revisao",
                max_length=15,
            ),
        ),
    ]
