# Generated by Django 5.1.2 on 2024-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0080_alter_documento_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="status",
            field=models.CharField(
                choices=[
                    ("aprovado", "Aprovado"),
                    ("em_revisao", "Em Revisão"),
                    ("inativos", "Inativos"),
                ],
                default="em_revisao",
                max_length=15,
            ),
        ),
    ]
