# Generated by Django 5.1.2 on 2024-12-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0085_alter_funcionario_cargo_responsavel"),
    ]

    operations = []
