# Generated by Django 5.1.2 on 2024-12-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0086_auto_20241206_1316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="cargo_responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsaveis",
                to="Funcionario.cargo",
            ),
        ),
    ]
