# Generated by Django 5.1.2 on 2024-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0088_alter_funcionario_responsavel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="formulario_f146",
            field=models.FileField(
                blank=True, null=True, upload_to="certificado_ensino/"
            ),
        ),
    ]
