# Generated by Django 5.1.2 on 2024-12-13 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0089_alter_funcionario_formulario_f146"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_atualizacao", models.DateField(auto_now_add=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Funcionario.cargo",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_cargos",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
