# Generated by Django 5.1.2 on 2024-12-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0090_historicocargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicocargo",
            name="cargo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicocargo",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
