# Generated by Django 5.1.2 on 2024-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0092_alter_historicocargo_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicocargo",
            name="data_atualizacao",
            field=models.DateTimeField(),
        ),
    ]
