# Generated by Django 5.1.2 on 2024-12-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0095_cargo_aprovador_data_cargo_aprovador_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargo",
            name="aprovador_nome",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="elaborador_nome",
        ),
        migrations.AddField(
            model_name="cargo",
            name="aprovador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_aprovados",
                to="Funcionario.funcionario",
                verbose_name="Aprovador",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="elaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_elaborados",
                to="Funcionario.funcionario",
                verbose_name="Elaborador",
            ),
        ),
    ]
