# Generated by Django 5.1.2 on 2024-12-13 18:47

import Funcionario.models.funcionario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0096_remove_cargo_aprovador_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="assinatura_eletronica",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.funcionario.renomear_assinatura,
                verbose_name="Assinatura Eletrônica",
            ),
        ),
    ]
