# Generated by Django 4.2.16 on 2025-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0097_funcionario_assinatura_eletronica"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
