# Generated by Django 4.2.16 on 2025-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0098_funcionario_data_nascimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="ivel",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Alta Direção / Conselho"),
                    (2, "Diretoria"),
                    (3, "Gerência Sênior"),
                    (4, "Gerência Média"),
                    (5, "Coordenação"),
                    (6, "Supervisão"),
                    (7, "Liderança Técnica"),
                    (8, "Analista / Técnico"),
                    (9, "Assistente / Auxiliar"),
                    (10, "Operacional"),
                ],
                default=10,
                help_text="1 = Mais alto (Direção), 10 = Mais baixo (Operacional)",
                verbose_name="Nível Hierárquico",
            ),
        ),
    ]
