# Generated by Django 4.2.16 on 2025-05-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0099_cargo_ivel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cargo",
            old_name="ivel",
            new_name="nivel",
        ),
    ]
