# Generated by Django 4.2.16 on 2025-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0101_documento_arquivo_tipo_documento_coleta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinamento",
            name="necessita_avaliacao",
            field=models.BooleanField(default=False),
        ),
    ]
