# Generated by Django 4.2.16 on 2025-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0103_avaliacaotreinamento_anexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="avaliacao_geral",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Pouco eficaz"),
                    (2, "Eficaz"),
                    (3, "Razoável"),
                    (4, "Bom"),
                    (5, "Muito eficaz"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="descricao_melhorias",
            field=models.TextField(blank=True, default="Nenhuma melhoria descrita"),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_1",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Não possui conhecimento mínimo da metodologia para sua aplicação.",
                    ),
                    (
                        2,
                        "Apresenta deficiências nos conceitos, o que compromete a aplicação.",
                    ),
                    (
                        3,
                        "Possui noções básicas, mas necessita de acompanhamento e suporte na aplicação.",
                    ),
                    (
                        4,
                        "Possui domínio necessário da metodologia e a utiliza adequadamente.",
                    ),
                    (
                        5,
                        "Possui completo domínio e utiliza a metodologia com excelência.",
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_2",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Está muito abaixo do esperado."),
                    (2, "Aplicação está abaixo do esperado."),
                    (3, "Aplicação é razoável, mas não dentro do esperado."),
                    (4, "Aplicação está adequada e corresponde às expectativas."),
                    (5, "Aplicação excede as expectativas."),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_3",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Nenhum resultado foi obtido efetivamente até o momento."),
                    (2, "As melhorias obtidas estão muito abaixo do esperado."),
                    (
                        3,
                        "As melhorias obtidas são consideráveis, mas não dentro do esperado.",
                    ),
                    (4, "As melhorias obtidas são boas e estão dentro do esperado."),
                    (5, "As melhorias obtidas excederam as expectativas."),
                ],
                null=True,
            ),
        ),
    ]
