# Generated by Django 4.2.16 on 2025-05-16 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "Funcionario",
            "0105_remove_cargo_aprovador_remove_cargo_aprovador_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="aprovador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_aprovados",
                to="Funcionario.funcionario",
                verbose_name="Aprovador",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="aprovador_data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data de Aprovação"
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="descricao_arquivo",
            field=models.FileField(blank=True, null=True, upload_to="cargos/"),
        ),
        migrations.AddField(
            model_name="cargo",
            name="elaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_elaborados",
                to="Funcionario.funcionario",
                verbose_name="Elaborador",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="elaborador_data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data de Elaboração"
            ),
        ),
        migrations.DeleteModel(
            name="AssinaturaCargo",
        ),
    ]
