# Generated by Django 4.2.16 on 2025-05-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0107_remove_nota_suplente_nota_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="perfil",
            field=models.CharField(
                choices=[
                    ("suplente", "Suplente"),
                    ("treinado", "Treinado"),
                    ("em_treinamento", "Em Treinamento"),
                    ("oficial", "Oficial"),
                ],
                max_length=20,
                verbose_name="Perfil",
            ),
        ),
    ]
