# Generated by Django 4.2.16 on 2025-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0108_alter_nota_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="listapresenca",
            name="planejado",
            field=models.CharField(
                choices=[("sim", "Sim"), ("nao", "Não")],
                default="nao",
                max_length=3,
                verbose_name="Planejado?",
            ),
        ),
    ]
