# Generated by Django 4.2.16 on 2025-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0109_listapresenca_planejado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treinamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("planejado", "Planejado"),
                    ("concluido", "Concluído"),
                    ("trancado", "Trancado"),
                    ("cursando", "Cursando"),
                    ("requerido", "Requerido"),
                ],
                default="cursando",
                max_length=50,
            ),
        ),
    ]
