# Generated by Django 4.2.16 on 2025-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0110_alter_treinamento_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="departamento",
            field=models.CharField(
                choices=[
                    ("RH", "Recursos Humanos"),
                    ("QUALIDADE", "Qualidade"),
                    ("ENGENHARIA", "Engenharia"),
                    ("PRODUCAO", "Produção"),
                    ("COMPRAS", "Compras"),
                ],
                max_length=50,
                verbose_name="Departamento",
            ),
        ),
    ]
