# Generated by Django 4.2.16 on 2025-05-21 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Funcionario", "0116_alter_atividade_departamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funcionario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
