# Generated by Django 4.2.16 on 2025-05-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0116_alter_atividade_departamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaoanual",
            name="anexo",
            field=models.FileField(
                blank=True, null=True, upload_to="avaliacoes/anual/"
            ),
        ),
        migrations.AddField(
            model_name="avaliacaoexperiencia",
            name="anexo",
            field=models.FileField(
                blank=True, null=True, upload_to="avaliacoes/experiencia/"
            ),
        ),
    ]
