# Generated by Django 4.2.16 on 2025-05-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0117_funcionario_user"),
        ("Funcionario", "0119_alter_atividade_departamento_and_more"),
    ]

    operations = []
