# Generated by Django 4.2.16 on 2025-05-26 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0120_merge_20250526_1118"),
    ]

    operations = [
        migrations.CreateModel(
            name="BancoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("hora_entrada", models.TimeField(blank=True, null=True)),
                ("hora_saida", models.TimeField(blank=True, null=True)),
                ("horas_trabalhadas", models.DurationField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banco_horas",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
