# Generated by Django 4.2.16 on 2025-05-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0121_bancohoras"),
    ]

    operations = [
        migrations.AddField(
            model_name="bancohoras",
            name="saldo_inicial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bancohoras",
            name="tipo_registro",
            field=models.CharField(
                choices=[("positivo", "Positivo"), ("negativo", "Negativo")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
