# Generated by Django 4.2.16 on 2025-05-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0122_bancohoras_saldo_inicial_bancohoras_tipo_registro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bancohoras",
            name="hora_entrada",
        ),
        migrations.RemoveField(
            model_name="bancohoras",
            name="hora_saida",
        ),
    ]
