# Generated by Django 4.2.16 on 2025-05-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0123_remove_bancohoras_hora_entrada_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bancohoras",
            name="tipo_registro",
        ),
    ]
