# Generated by Django 4.2.16 on 2025-05-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0124_remove_bancohoras_tipo_registro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bancohoras",
            old_name="saldo_inicial",
            new_name="utilizado_no_banco",
        ),
    ]
