# Generated by Django 4.2.16 on 2025-05-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0125_rename_saldo_inicial_bancohoras_utilizado_no_banco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bancohoras",
            name="utilizado_no_banco",
        ),
    ]
