# Generated by Django 4.2.16 on 2025-05-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0126_remove_bancohoras_utilizado_no_banco"),
    ]

    operations = [
        migrations.AddField(
            model_name="bancohoras",
            name="he_100",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bancohoras",
            name="he_50",
            field=models.BooleanField(default=False),
        ),
    ]
