# Generated by Django 4.2.16 on 2025-05-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0022_alter_atrasosaida_utilizado_no_banco"),
        ("Funcionario", "0127_bancohoras_he_100_bancohoras_he_50"),
    ]

    operations = [
        migrations.AddField(
            model_name="bancohoras",
            name="ocorrencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_banco",
                to="portaria.atrasosaida",
            ),
        ),
    ]
