# Generated by Django 4.2.16 on 2025-05-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0022_alter_atrasosaida_utilizado_no_banco"),
        ("Funcionario", "0128_bancohoras_ocorrencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="bancohoras",
            name="saldo_horas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Horas acumuladas ou devidas neste dia (positivas ou negativas)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="ocorrencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banco_relacionado",
                to="portaria.atrasosaida",
            ),
        ),
    ]
