# Generated by Django 4.2.16 on 2025-05-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0129_bancohoras_saldo_horas_alter_bancohoras_ocorrencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bancohoras",
            name="saldo_horas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Horas positivas ou negativas do dia",
                max_digits=5,
                null=True,
                verbose_name="Saldo (h)",
            ),
        ),
    ]
