# Generated by Django 4.2.16 on 2025-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0130_alter_bancohoras_saldo_horas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("RH", "Recursos Humanos"),
                            ("QUALIDADE", "Gestão da Qualidade"),
                            ("CONTROLE", "Controle de Qualidade"),
                            ("PRODUCAO", "Produção"),
                            ("COMPRAS", "Compras"),
                            ("COMERCIAL", "Comercial"),
                            ("DIRETORIA", "Diretoria"),
                            ("PCP", "Logistica/PCP"),
                            ("LIMPEZA", "Serviços Gerais"),
                            ("TÉCNICO", "Técnico"),
                            ("TI", "Técnologia da Informação"),
                            ("ALMOXARIFADO", "Almoxarifado"),
                            ("EXPEDICAO", "Expedição"),
                            ("MANUTENÇÃO", "Manutenção"),
                            ("COMPRESSAO", "Compressão"),
                            ("RETIFICA", "Retífica"),
                            ("TORÇÃO", "Torção"),
                            ("ESTAMPARIA_BIHLER", "Estamparia Bihler"),
                            ("ACABAMENTO", "Acabamento"),
                            ("PRENSA", "Prensa"),
                            ("DOBRADEIRA_CNC", "Dobradeira CNC"),
                            ("ALIVIO_TENSAO", "Alívio de Tensão"),
                            ("FERRAMENTARIA", "Ferramentaria"),
                            ("PORTARIA", "Portaria"),
                            ("FINANCEIRO", "Financeiro"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documento",
            name="departamentos",
            field=models.ManyToManyField(blank=True, to="Funcionario.departamento"),
        ),
    ]
