# Generated by Django 4.2.16 on 2025-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0133_departamentos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="departamentos",
            field=models.ManyToManyField(blank=True, to="Funcionario.departamentos"),
        ),
    ]
