# Generated by Django 4.2.16 on 2025-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0134_alter_documento_departamentos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamentos",
            name="sigla",
            field=models.CharField(
                default=1, max_length=30, unique=True, verbose_name="Sigla"
            ),
            preserve_default=False,
        ),
    ]
