# Generated by Django 4.2.16 on 2025-05-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0135_alter_departamentos_sigla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="local_trabalho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funcionarios",
                to="Funcionario.departamentos",
                verbose_name="Local de Trabalho",
            ),
        ),
    ]
