# Generated by Django 4.2.16 on 2025-05-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0140_alter_cargo_departamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades_departamento",
                to="Funcionario.departamentos",
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="matrizpolivalencia",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matrizes_polivalencia",
                to="Funcionario.departamentos",
                verbose_name="Departamento",
            ),
        ),
    ]
