# Generated by Django 4.2.16 on 2025-05-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0141_alter_atividade_departamento_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Departamento",
        ),
    ]
