# Generated by Django 4.2.16 on 2025-05-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0142_delete_departamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atividade",
            name="departamento",
        ),
        migrations.AddField(
            model_name="atividade",
            name="departamentos",
            field=models.ManyToManyField(
                blank=True,
                related_name="atividades_departamentos",
                to="Funcionario.departamentos",
                verbose_name="Departamentos",
            ),
        ),
    ]
