# Generated by Django 4.2.16 on 2025-05-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0143_remove_atividade_departamento_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nota",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="nota",
            name="matriz",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas",
                to="Funcionario.matrizpolivalencia",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="nota",
            unique_together={("matriz", "funcionario", "atividade")},
        ),
    ]
