# Generated by Django 4.2.16 on 2025-05-30 13:27

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0144_alter_nota_unique_together_nota_matriz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atualizacaosistema",
            name="previa_versao",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Prévia da Versão"
            ),
        ),
    ]
