# Generated by Django 4.2.16 on 2025-05-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0145_atualizacaosistema_previa_versao"),
    ]

    operations = [
        migrations.AddField(
            model_name="atualizacaosistema",
            name="arquivo_pdf",
            field=models.FileField(blank=True, null=True, upload_to="atualizacoes/"),
        ),
    ]
