# Generated by Django 4.2.16 on 2025-05-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0147_atualizacaolida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="versao",
            field=models.CharField(
                help_text="Informe no formato MAJOR.MINOR.PATCH (ex: 1.6.5)",
                max_length=20,
                verbose_name="Versão (ex: 1.6.5)",
            ),
        ),
    ]
