# Generated by Django 4.2.16 on 2025-06-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0148_alter_atualizacaosistema_versao"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="calcado",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Número do Calçado"
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="camisa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PP", "PP"),
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("XG", "XG"),
                    ("XXG", "XXG"),
                ],
                max_length=3,
                null=True,
                verbose_name="Tamanho da Camisa",
            ),
        ),
    ]
