# Generated by Django 4.2.16 on 2025-06-04 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Funcionario", "0149_funcionario_calcado_funcionario_camisa"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisaoDocLeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_leitura", models.DateTimeField(auto_now_add=True)),
                (
                    "revisao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to="Funcionario.revisaodoc",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("revisao", "usuario")},
            },
        ),
    ]
