# Generated by Django 4.2.16 on 2025-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0150_revisaodocleitura"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="data_desligamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="genero",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Feminino", "Feminino"),
                    ("Outro", "Outro"),
                    ("Não Informado", "Não Informado"),
                ],
                default="Não Informado",
                max_length=20,
            ),
        ),
    ]
