# Generated by Django 4.2.16 on 2025-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0151_funcionario_data_desligamento_funcionario_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="genero",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Feminino", "Feminino"),
                    ("Outro", "Outro"),
                    ("Não Informado", "Não Informado"),
                ],
                default="Não Informado",
                max_length=20,
                verbose_name="Gênero",
            ),
        ),
    ]
