# Generated by Django 4.2.16 on 2025-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0152_alter_funcionario_genero"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="representante_brigada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="representante_cipa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="tipo_cipa",
            field=models.CharField(
                blank=True,
                choices=[("Titular", "Titular"), ("Suplente", "Suplente")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="tipo_representacao_cipa",
            field=models.CharField(
                blank=True,
                choices=[("Empregados", "Empregados"), ("Empregador", "Empregador")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="vigencia_brigada",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="vigencia_cipa",
            field=models.DateField(blank=True, null=True),
        ),
    ]
