# Generated by Django 4.2.16 on 2025-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0153_funcionario_representante_brigada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="ordem_cipa",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1º"), (2, "2º"), (3, "3º"), (4, "4º")],
                null=True,
                verbose_name="Ordem na CIPA",
            ),
        ),
    ]
