# Generated by Django 4.2.16 on 2025-06-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0154_funcionario_ordem_cipa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listapresenca",
            name="horario_fim",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="horario_inicio",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
