# Generated by Django 4.2.16 on 2025-06-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0155_alter_listapresenca_horario_fim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("operacional", "Operacional"),
                    ("administrativo", "Administrativo"),
                ],
                default="operacional",
                max_length=20,
                verbose_name="Tipo do Colaborador",
            ),
        ),
    ]
