# Generated by Django 4.2.16 on 2025-06-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0156_funcionario_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReciboPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_colaborador", models.CharField(max_length=150)),
                ("mes_referencia", models.DateField(verbose_name="Mês de Referência")),
                ("arquivo_pdf", models.FileField(upload_to="recibos_pagamento/")),
                ("data_importacao", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos_pagamento",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
        ),
    ]
