# Generated by Django 4.2.16 on 2025-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0157_recibopagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="numero_registro_recibo",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Número do Registro para Recibo",
            ),
        ),
    ]
