# Generated by Django 4.2.16 on 2025-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0158_funcionario_numero_registro_recibo"),
    ]

    operations = [
        migrations.AddField(
            model_name="recibopagamento",
            name="valor_descontos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="recibopagamento",
            name="valor_liquido",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="recibopagamento",
            name="valor_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
