# Generated by Django 4.2.16 on 2025-06-30 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0022_alter_atrasosaida_utilizado_no_banco"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Funcionario", "0159_recibopagamento_valor_descontos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atualizacaolida",
            options={"verbose_name_plural": "Atualizações Lidas"},
        ),
        migrations.AlterModelOptions(
            name="atualizacaosistema",
            options={
                "ordering": ["-previsao"],
                "verbose_name_plural": "Atualizações do Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="avaliacaoanual",
            options={
                "ordering": ["-data_avaliacao"],
                "verbose_name_plural": "Avaliações Anuais",
            },
        ),
        migrations.AlterModelOptions(
            name="avaliacaoexperiencia",
            options={
                "ordering": ["-data_avaliacao"],
                "verbose_name_plural": "Avaliações de Experiência",
            },
        ),
        migrations.AlterModelOptions(
            name="avaliacaotreinamento",
            options={
                "ordering": ["-data_avaliacao"],
                "verbose_name_plural": "Avaliações de Treinamento",
            },
        ),
        migrations.AlterModelOptions(
            name="bancohoras",
            options={"ordering": ["-data"], "verbose_name_plural": "Banco de Horas"},
        ),
        migrations.AlterField(
            model_name="atualizacaolida",
            name="atualizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.atualizacaosistema",
                verbose_name="Atualização",
            ),
        ),
        migrations.AlterField(
            model_name="atualizacaolida",
            name="data_leitura",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data da Leitura"
            ),
        ),
        migrations.AlterField(
            model_name="atualizacaolida",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="arquivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="atualizacoes/",
                verbose_name="Arquivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="data_termino",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Data de Término",
            ),
        ),
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="descricao",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="previsao",
            field=models.DateField(verbose_name="Data de Previsão"),
        ),
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluido", "Concluído"),
                    ("em_andamento", "Em andamento"),
                    ("cancelado", "Cancelado"),
                ],
                default="em_andamento",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="atualizacaosistema",
            name="titulo",
            field=models.CharField(max_length=100, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="avaliacoes/anual/",
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="assiduidade",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Assiduidade"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="avaliacao_global_avaliado",
            field=models.TextField(
                blank=True, null=True, verbose_name="Autoavaliação do Avaliado"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="avaliacao_global_avaliador",
            field=models.TextField(
                blank=True, null=True, verbose_name="Avaliação Global do Avaliador"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="centro_custo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Centro de Custo"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="comprometimento",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Comprometimento"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="comunicacao",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Comunicação"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="data_avaliacao",
            field=models.DateField(verbose_name="Data da Avaliação"),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="disciplina",
            field=models.IntegerField(blank=True, null=True, verbose_name="Disciplina"),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="disponibilidade_para_mudancas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Disponibilidade para Mudanças"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="postura_seg_trabalho",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Postura em Segurança do Trabalho"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="proatividade",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Proatividade"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="qualidade_produtividade",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qualidade e Produtividade"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="rendimento_sob_pressao",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Rendimento sob Pressão"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="trabalho_em_equipe",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Trabalho em Equipe"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="adaptacao_trabalho",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Adaptação ao Trabalho"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="avaliacoes/experiencia/",
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="capacidade_aprendizagem",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Capacidade de Aprendizagem"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="data_avaliacao",
            field=models.DateField(verbose_name="Data da Avaliação"),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="gerencia",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Gerência"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="interesse",
            field=models.IntegerField(blank=True, null=True, verbose_name="Interesse"),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="orientacao",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Orientação"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="relacionamento_social",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Relacionamento Social"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="avaliacao_geral",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Pouco eficaz"),
                    (2, "Eficaz"),
                    (3, "Razoável"),
                    (4, "Bom"),
                    (5, "Muito eficaz"),
                ],
                null=True,
                verbose_name="Avaliação Geral",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="data_avaliacao",
            field=models.DateField(verbose_name="Data da Avaliação"),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="descricao_melhorias",
            field=models.TextField(
                blank=True,
                default="Nenhuma melhoria descrita",
                verbose_name="Descrição das Melhorias",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_1",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Não possui conhecimento mínimo da metodologia para sua aplicação.",
                    ),
                    (
                        2,
                        "Apresenta deficiências nos conceitos, o que compromete a aplicação.",
                    ),
                    (
                        3,
                        "Possui noções básicas, mas necessita de acompanhamento e suporte na aplicação.",
                    ),
                    (
                        4,
                        "Possui domínio necessário da metodologia e a utiliza adequadamente.",
                    ),
                    (
                        5,
                        "Possui completo domínio e utiliza a metodologia com excelência.",
                    ),
                ],
                null=True,
                verbose_name="Conhecimento da Metodologia",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_2",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Está muito abaixo do esperado."),
                    (2, "Aplicação está abaixo do esperado."),
                    (3, "Aplicação é razoável, mas não dentro do esperado."),
                    (4, "Aplicação está adequada e corresponde às expectativas."),
                    (5, "Aplicação excede as expectativas."),
                ],
                null=True,
                verbose_name="Aplicação na Prática",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="pergunta_3",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Nenhum resultado foi obtido efetivamente até o momento."),
                    (2, "As melhorias obtidas estão muito abaixo do esperado."),
                    (
                        3,
                        "As melhorias obtidas são consideráveis, mas não dentro do esperado.",
                    ),
                    (4, "As melhorias obtidas são boas e estão dentro do esperado."),
                    (5, "As melhorias obtidas excederam as expectativas."),
                ],
                null=True,
                verbose_name="Resultados Obtidos",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="periodo_avaliacao",
            field=models.IntegerField(
                default=60, verbose_name="Período da Avaliação (dias)"
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_1",
                to="Funcionario.funcionario",
                verbose_name="Responsável 1",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_2",
                to="Funcionario.funcionario",
                verbose_name="Responsável 2",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="responsavel_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_responsavel_3",
                to="Funcionario.funcionario",
                verbose_name="Responsável 3",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="treinamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="Funcionario.treinamento",
                verbose_name="Treinamento",
            ),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banco_horas",
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="he_100",
            field=models.BooleanField(default=False, verbose_name="Hora Extra 100%"),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="he_50",
            field=models.BooleanField(default=False, verbose_name="Hora Extra 50%"),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="horas_trabalhadas",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Horas Trabalhadas"
            ),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="bancohoras",
            name="ocorrencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banco_relacionado",
                to="portaria.atrasosaida",
                verbose_name="Ocorrência (Atraso/Saída)",
            ),
        ),
    ]
