# Generated by Django 4.2.16 on 2025-06-30 13:57

import Funcionario.models.funcionario
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Funcionario", "0160_alter_atualizacaolida_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atividade",
            options={
                "ordering": ["nome"],
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
            },
        ),
        migrations.AlterModelOptions(
            name="cargo",
            options={"ordering": ["nivel", "nome"], "verbose_name_plural": "Cargos"},
        ),
        migrations.AlterModelOptions(
            name="comunicado",
            options={"ordering": ["-data"], "verbose_name_plural": "Comunicados"},
        ),
        migrations.AlterModelOptions(
            name="documento",
            options={"ordering": ["nome"], "verbose_name_plural": "Documentos"},
        ),
        migrations.AlterModelOptions(
            name="evento",
            options={"ordering": ["data_inicio"], "verbose_name_plural": "Eventos"},
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={"ordering": ["nome"], "verbose_name_plural": "Funcionários"},
        ),
        migrations.AlterModelOptions(
            name="historicocargo",
            options={
                "ordering": ["-data_atualizacao"],
                "verbose_name_plural": "Histórico de Cargos",
            },
        ),
        migrations.AlterModelOptions(
            name="integracaofuncionario",
            options={
                "ordering": ["-data_integracao"],
                "verbose_name_plural": "Integrações de Funcionários",
            },
        ),
        migrations.AlterModelOptions(
            name="jobrotationevaluation",
            options={
                "ordering": ["-data_inicio"],
                "verbose_name_plural": "Avaliações de Job Rotation",
            },
        ),
        migrations.AlterModelOptions(
            name="listapresenca",
            options={
                "ordering": ["-data_inicio"],
                "verbose_name_plural": "Listas de Presença",
            },
        ),
        migrations.AlterModelOptions(
            name="matrizpolivalencia",
            options={
                "ordering": ["departamento"],
                "verbose_name": "Matriz de Polivalência",
                "verbose_name_plural": "Matrizes de Polivalência",
            },
        ),
        migrations.AlterModelOptions(
            name="nota",
            options={
                "ordering": ["funcionario", "atividade"],
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
            },
        ),
        migrations.AlterModelOptions(
            name="recibopagamento",
            options={
                "ordering": ["-mes_referencia", "nome_colaborador"],
                "verbose_name": "Recibo de Pagamento",
                "verbose_name_plural": "Recibos de Pagamento",
            },
        ),
        migrations.AlterModelOptions(
            name="revisao",
            options={
                "ordering": ["-data_revisao"],
                "verbose_name_plural": "Revisões de Cargo",
            },
        ),
        migrations.AlterModelOptions(
            name="revisaodoc",
            options={
                "ordering": ["-data_revisao"],
                "verbose_name_plural": "Revisões de Documento",
            },
        ),
        migrations.AlterModelOptions(
            name="revisaodocleitura",
            options={
                "ordering": ["-data_leitura"],
                "verbose_name": "Leitura de Revisão de Documento",
                "verbose_name_plural": "Leituras de Revisões de Documentos",
            },
        ),
        migrations.AlterModelOptions(
            name="treinamento",
            options={
                "ordering": ["-data_inicio"],
                "verbose_name": "Treinamento",
                "verbose_name_plural": "Treinamentos",
            },
        ),
        migrations.AlterField(
            model_name="cargo",
            name="descricao_arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cargos/",
                verbose_name="Arquivo Descritivo",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome do Cargo"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="numero_dc",
            field=models.CharField(max_length=4, verbose_name="Número DC"),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="assunto",
            field=models.CharField(max_length=100, verbose_name="Assunto"),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data do Comunicado"
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="departamento_responsavel",
            field=models.CharField(
                max_length=100, verbose_name="Departamento Responsável"
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="lista_assinaturas",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assinaturas/",
                verbose_name="Lista de Assinaturas",
            ),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Auditoria", "Auditoria"),
                    ("Conscientizacao", "Conscientização"),
                    ("Melhoria", "Melhoria"),
                    ("Organizacao/Processos", "Organização / Processos"),
                    ("Recursos Humanos", "Recursos Humanos"),
                    ("Visita de Cliente", "Visita de Cliente"),
                ],
                max_length=50,
                verbose_name="Tipo do Comunicado",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(
                blank=True, null=True, upload_to="documentos/", verbose_name="Arquivo"
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="arquivo_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("copia_fisica", "Cópia Física"),
                    ("copia_eletronica", "Cópia Eletrônica"),
                    ("copia_digitalizada", "Cópia Física / Cópia Digitalizada"),
                    ("pasta_az", "Cópia Física / Pasta A-Z"),
                    ("pasta_suspensa", "Cópia Física / Pasta Suspensa"),
                    (
                        "copia_eletronica_servidor",
                        "Cópia Eletrônica (Servidor / Sistema)",
                    ),
                    ("planilha_eletronica", "Planilha Eletrônica"),
                    ("numero", "Cópia Eletrônica / Número"),
                    ("copia_dupla", "Cópia Física / Cópia Eletrônica"),
                    ("copia_servidor", "Cópia Eletrônica / Servidor"),
                    (
                        "copia_az_fisica_eletronica",
                        "Cópia Eletrônica / Física / Pasta A-Z",
                    ),
                    ("papel", "Papel"),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo de Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="codigo",
            field=models.CharField(max_length=4, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="documento",
            name="coleta",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Método de Coleta"
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="departamentos",
            field=models.ManyToManyField(
                blank=True,
                to="Funcionario.departamentos",
                verbose_name="Departamentos Relacionados",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="descarte",
            field=models.CharField(
                blank=True,
                choices=[
                    ("destruido", "Destruído"),
                    ("deletar", "Deletar"),
                    ("obsoleto", "Obsoleto"),
                    ("destruido_deletar", "Destruído / Deletar"),
                    ("apagar", "Deletar / Apagar"),
                    ("destruir", "Destruir"),
                ],
                max_length=30,
                null=True,
                verbose_name="Forma de Descarte",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="local_armazenamento",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Local de Armazenamento",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome do Documento"),
        ),
        migrations.AlterField(
            model_name="documento",
            name="recuperacao",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Método de Recuperação",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="responsavel_recuperacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargos",
                to="Funcionario.cargo",
                verbose_name="Responsável pela Recuperação",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="status",
            field=models.CharField(
                choices=[
                    ("aprovado", "Aprovado"),
                    ("em_revisao", "Em Revisão"),
                    ("inativo", "Inativo"),
                ],
                default="em_revisao",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="tempo_retencao",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tempo de Retenção"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="cor",
            field=models.CharField(
                default="#3788d8", max_length=7, verbose_name="Cor (hexadecimal)"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_fim",
            field=models.DateField(verbose_name="Data de Fim"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_inicio",
            field=models.DateField(verbose_name="Data de Início"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("avaliacao_desempenho", "Avaliação de Desempenho"),
                    ("feriado", "Feriado"),
                    ("ponte", "Ponte"),
                    ("confraternizacao", "Confraternização"),
                    ("recesso", "Recesso"),
                    ("auditoria_sgs", "Auditoria SGS"),
                    ("auditoria_interna", "Auditoria Interna"),
                    ("sipat", "SIPAT"),
                    ("inventario", "Inventário"),
                ],
                default="avaliacao_desempenho",
                max_length=20,
                verbose_name="Tipo de Evento",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="titulo",
            field=models.CharField(max_length=200, verbose_name="Título do Evento"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo_atual",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_atual_funcionarios",
                to="Funcionario.cargo",
                verbose_name="Cargo Atual",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo_inicial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_inicial_funcionarios",
                to="Funcionario.cargo",
                verbose_name="Cargo Inicial",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo_responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsaveis",
                to="Funcionario.cargo",
                verbose_name="Cargo do Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="curriculo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.funcionario.renomear_curriculo,
                verbose_name="Currículo",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="data_admissao",
            field=models.DateField(verbose_name="Data de Admissão"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="data_desligamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Desligamento"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="data_integracao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Integração"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="escolaridade",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Escolaridade"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="experiencia_profissional",
            field=models.CharField(
                choices=[
                    (
                        "Sim",
                        "Sim, (Anexar Curriculum ou cópia da Carteira Profissional no prontuário)",
                    ),
                    (
                        "Não",
                        "Não, (Justificar através da Avaliação Prática da Atividade, devidamente assinada)",
                    ),
                ],
                default="Sim",
                max_length=3,
                verbose_name="Experiência Profissional",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="formulario_f146",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificado_ensino/",
                verbose_name="Formulário F146",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fotos_funcionarios/",
                verbose_name="Foto",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome Completo"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="numero_registro",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Número de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="representante_brigada",
            field=models.BooleanField(
                default=False, verbose_name="Representante Brigada"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="representante_cipa",
            field=models.BooleanField(default=False, verbose_name="Representante CIPA"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funcionarios_gerenciados",
                to="Funcionario.funcionario",
                verbose_name="Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="status",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="tipo_cipa",
            field=models.CharField(
                blank=True,
                choices=[("Titular", "Titular"), ("Suplente", "Suplente")],
                max_length=20,
                null=True,
                verbose_name="Tipo CIPA",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="tipo_representacao_cipa",
            field=models.CharField(
                blank=True,
                choices=[("Empregados", "Empregados"), ("Empregador", "Empregador")],
                max_length=20,
                null=True,
                verbose_name="Representação CIPA",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="vigencia_brigada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vigência Brigada"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="vigencia_cipa",
            field=models.DateField(blank=True, null=True, verbose_name="Vigência CIPA"),
        ),
        migrations.AlterField(
            model_name="historicocargo",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_cargos",
                to="Funcionario.cargo",
                verbose_name="Cargo",
            ),
        ),
        migrations.AlterField(
            model_name="historicocargo",
            name="data_atualizacao",
            field=models.DateTimeField(verbose_name="Data de Atualização"),
        ),
        migrations.AlterField(
            model_name="historicocargo",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_cargos",
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="integracaofuncionario",
            name="data_integracao",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data da Integração"
            ),
        ),
        migrations.AlterField(
            model_name="integracaofuncionario",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="integracaofuncionario",
            name="grupo_whatsapp",
            field=models.BooleanField(
                default=False, verbose_name="Adicionado ao grupo de WhatsApp"
            ),
        ),
        migrations.AlterField(
            model_name="integracaofuncionario",
            name="requer_treinamento",
            field=models.BooleanField(default=False, verbose_name="Requer Treinamento"),
        ),
        migrations.AlterField(
            model_name="integracaofuncionario",
            name="treinamentos_requeridos",
            field=models.TextField(
                blank=True, null=True, verbose_name="Treinamentos Requeridos"
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="area",
            field=models.CharField(max_length=100, verbose_name="Área"),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="avaliacao_funcionario",
            field=models.TextField(blank=True, verbose_name="Avaliação do Funcionário"),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="avaliacao_gestor",
            field=models.TextField(blank=True, verbose_name="Avaliação do Gestor"),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="avaliacao_rh",
            field=models.CharField(
                choices=[
                    ("Apto", "Apto"),
                    ("Inapto", "Inapto"),
                    ("Prorrogar TN", "Prorrogar TN"),
                    ("EmProgresso", "Em Progresso"),
                ],
                max_length=20,
                verbose_name="Avaliação RH",
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="cargo_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_rotation_evaluations_cargo",
                to="Funcionario.cargo",
                verbose_name="Cargo Atual",
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="competencias",
            field=models.TextField(blank=True, null=True, verbose_name="Competências"),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="cursos_realizados",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Cursos Realizados"
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="data_inicio",
            field=models.DateField(verbose_name="Data de Início"),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="data_ultima_avaliacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Última Avaliação"
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="descricao_cargo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição do Cargo"
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="disponibilidade_vaga",
            field=models.BooleanField(
                default=False, verbose_name="Disponibilidade de Vaga"
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="escolaridade",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Escolaridade"
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_rotation_evaluations",
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="gestor_responsavel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gestor_responsavel",
                to="Funcionario.funcionario",
                verbose_name="Gestor Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="local_trabalho",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Local de Trabalho"
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="nova_funcao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nova_funcao",
                to="Funcionario.cargo",
                verbose_name="Nova Função",
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="status_ultima_avaliacao",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Status da Última Avaliação",
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="termino_previsto",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Término Previsto"
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="treinamentos_propostos",
            field=models.TextField(blank=True, verbose_name="Treinamentos Propostos"),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="treinamentos_requeridos",
            field=models.TextField(blank=True, verbose_name="Treinamentos Requeridos"),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="assunto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Assunto"
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="data_fim",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Término"
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="data_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Início"
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="descricao",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="duracao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Duração (horas)",
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="horario_fim",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horário de Término"
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="horario_inicio",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horário de Início"
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="instrutor",
            field=models.CharField(max_length=255, verbose_name="Instrutor"),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="lista_presenca",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="listas_presenca/",
                verbose_name="Arquivo da Lista de Presença",
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="necessita_avaliacao",
            field=models.BooleanField(
                default=False, verbose_name="Necessita Avaliação?"
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="participantes",
            field=models.ManyToManyField(
                related_name="participantes",
                to="Funcionario.funcionario",
                verbose_name="Participantes",
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("finalizado", "Finalizado"),
                    ("em_andamento", "Em Andamento"),
                ],
                default="em_andamento",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="treinamento",
            field=models.CharField(
                choices=[
                    ("Treinamento", "Treinamento"),
                    ("Curso", "Curso"),
                    ("Divulgacao", "Divulgação"),
                    ("Conscientização", "Conscientização"),
                ],
                max_length=255,
                verbose_name="Tipo de Evento",
            ),
        ),
        migrations.AlterField(
            model_name="recibopagamento",
            name="arquivo_pdf",
            field=models.FileField(
                upload_to="recibos_pagamento/", verbose_name="Arquivo PDF"
            ),
        ),
        migrations.AlterField(
            model_name="recibopagamento",
            name="data_importacao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Importação"
            ),
        ),
        migrations.AlterField(
            model_name="recibopagamento",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recibos_pagamento",
                to="Funcionario.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="recibopagamento",
            name="nome_colaborador",
            field=models.CharField(max_length=150, verbose_name="Nome do Colaborador"),
        ),
        migrations.AlterField(
            model_name="recibopagamento",
            name="valor_descontos",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor dos Descontos",
            ),
        ),
        migrations.AlterField(
            model_name="recibopagamento",
            name="valor_liquido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Líquido",
            ),
        ),
        migrations.AlterField(
            model_name="recibopagamento",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Total",
            ),
        ),
        migrations.AlterField(
            model_name="revisao",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisoes",
                to="Funcionario.cargo",
                verbose_name="Cargo",
            ),
        ),
        migrations.AlterField(
            model_name="revisao",
            name="data_revisao",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data da Revisão"
            ),
        ),
        migrations.AlterField(
            model_name="revisao",
            name="descricao_mudanca",
            field=models.TextField(verbose_name="Descrição da Mudança"),
        ),
        migrations.AlterField(
            model_name="revisao",
            name="numero_revisao",
            field=models.CharField(max_length=20, verbose_name="Número da Revisão"),
        ),
        migrations.AlterField(
            model_name="revisaodoc",
            name="data_revisao",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data da Revisão"
            ),
        ),
        migrations.AlterField(
            model_name="revisaodoc",
            name="descricao_mudanca",
            field=models.TextField(verbose_name="Descrição da Mudança"),
        ),
        migrations.AlterField(
            model_name="revisaodoc",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisoes",
                to="Funcionario.documento",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="revisaodoc",
            name="numero_revisao",
            field=models.CharField(max_length=20, verbose_name="Número da Revisão"),
        ),
        migrations.AlterField(
            model_name="revisaodoc",
            name="status",
            field=models.CharField(
                choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                default="ativo",
                max_length=10,
                verbose_name="Status da Revisão",
            ),
        ),
        migrations.AlterField(
            model_name="revisaodocleitura",
            name="data_leitura",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data da Leitura"
            ),
        ),
        migrations.AlterField(
            model_name="revisaodocleitura",
            name="revisao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leituras",
                to="Funcionario.revisaodoc",
                verbose_name="Revisão do Documento",
            ),
        ),
        migrations.AlterField(
            model_name="revisaodocleitura",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="cep",
            field=models.CharField(
                default="08579000", max_length=20, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="cnpj",
            field=models.CharField(
                default="61.296.901/0002-48", max_length=20, verbose_name="CNPJ"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="email",
            field=models.EmailField(
                default="rh@brasmol.com.br", max_length=254, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="endereco",
            field=models.CharField(
                default="BONSUCESSO, DO, 1961 - RIO ABAIXO - Itaquaquecetuba / SP",
                max_length=150,
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="logo_claro",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Logo (Claro)"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="logo_escuro",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Logo (Escuro)"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="nome_empresa",
            field=models.CharField(
                default="BRAS-MOL MOLAS & ESTAMPADOS LTDA",
                max_length=100,
                verbose_name="Nome da Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="telefone",
            field=models.CharField(
                default="1146482611", max_length=20, verbose_name="Telefone"
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="anexo",
            field=models.FileField(
                blank=True, null=True, upload_to="certificados/", verbose_name="Anexo"
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="carga_horaria",
            field=models.CharField(max_length=50, verbose_name="Carga Horária"),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("capacitacao", "Capacitação"),
                    ("tecnico", "Técnico"),
                    ("graduacao", "Graduação"),
                    ("pos-graduacao", "Pos-graduação"),
                    ("treinamento", "Treinamento"),
                    ("divulgacao", "Divulgação"),
                ],
                max_length=100,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="data_fim",
            field=models.DateField(verbose_name="Data de Término"),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="data_inicio",
            field=models.DateField(verbose_name="Data de Início"),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="descricao",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="funcionarios",
            field=models.ManyToManyField(
                related_name="treinamentos",
                to="Funcionario.funcionario",
                verbose_name="Funcionários",
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="instituicao_ensino",
            field=models.CharField(
                default="Bras-Mol", max_length=255, verbose_name="Instituição de Ensino"
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="necessita_avaliacao",
            field=models.BooleanField(
                default=False, verbose_name="Necessita Avaliação"
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="nome_curso",
            field=models.CharField(max_length=100, verbose_name="Nome do Curso"),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="situacao",
            field=models.CharField(
                blank=True,
                choices=[("aprovado", "Aprovado"), ("reprovado", "Reprovado")],
                help_text="Campo exibido apenas para treinamentos requeridos.",
                max_length=50,
                null=True,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("planejado", "Planejado"),
                    ("concluido", "Concluído"),
                    ("trancado", "Trancado"),
                    ("cursando", "Cursando"),
                    ("requerido", "Requerido"),
                ],
                default="cursando",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="tipo",
            field=models.CharField(
                choices=[("interno", "Interno"), ("externo", "Externo")],
                max_length=50,
                verbose_name="Tipo de Treinamento",
            ),
        ),
    ]
