# Generated by Django 4.2.16 on 2025-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0161_alter_atividade_options_alter_cargo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FechamentoIndicadorTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("trimestre", models.IntegerField()),
                ("valor_t1", models.FloatField(blank=True, null=True)),
                ("valor_t2", models.FloatField(blank=True, null=True)),
                ("valor_t3", models.FloatField(blank=True, null=True)),
                ("valor_t4", models.FloatField(blank=True, null=True)),
                ("media", models.FloatField(blank=True, null=True)),
                ("data_fechamento", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("ano", "trimestre")},
            },
        ),
    ]
