# Generated by Django 4.2.16 on 2025-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0163_jobrotationevaluation_anexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaotreinamento",
            name="data_conclusao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Conclusão da Avaliação"
            ),
        ),
    ]
