# Generated by Django 4.2.16 on 2025-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0164_avaliacaotreinamento_data_conclusao"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="email_comprador",
            field=models.EmailField(
                default="compras@brasmol.com.br",
                max_length=254,
                verbose_name="E-mail Comprador",
            ),
        ),
    ]
