# Generated by Django 4.2.16 on 2025-08-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0165_settings_email_comprador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacaotreinamento",
            name="data_conclusao",
        ),
    ]
