# Generated by Django 4.2.16 on 2025-08-11 16:34

import Funcionario.models.funcionario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0166_remove_avaliacaotreinamento_data_conclusao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="curriculo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.funcionario.renomear_curriculo,
                validators=[Funcionario.models.funcionario.MaxFileSizeValidator(5)],
                verbose_name="Currículo",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="formulario_f146",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.funcionario.renomear_certificado_ensino_medio,
                validators=[Funcionario.models.funcionario.MaxFileSizeValidator(5)],
                verbose_name="Certificado de Conclusão do Ensino Médio",
            ),
        ),
    ]
