# Generated by Django 4.2.16 on 2025-08-11 16:56

import Funcionario.models.funcionario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0167_alter_funcionario_curriculo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.funcionario.renomear_foto,
                validators=[Funcionario.models.funcionario.MaxFileSizeValidator(5)],
                verbose_name="Foto",
            ),
        ),
    ]
