# Generated by Django 4.2.16 on 2025-08-11 17:08

import Funcionario.models.integracao_funcionario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0168_alter_funcionario_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integracaofuncionario",
            name="pdf_integracao",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.integracao_funcionario.renomear_pdf_integracao,
                validators=[
                    Funcionario.models.integracao_funcionario.MaxFileSizeValidator(5)
                ],
                verbose_name="PDF da Integração Assinada",
            ),
        ),
    ]
