# Generated by Django 4.2.16 on 2025-08-11 17:17

import Funcionario.models.comunicado
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0169_alter_integracaofuncionario_pdf_integracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicado",
            name="lista_assinaturas",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.comunicado.renomear_lista_assinaturas,
                validators=[Funcionario.models.comunicado.MaxFileSizeValidator(5)],
                verbose_name="Lista de Assinaturas",
            ),
        ),
    ]
