# Generated by Django 4.2.16 on 2025-08-11 18:15

import Funcionario.models.avaliacao_treinamento
import Funcionario.models.cargo
import Funcionario.models.lista_presenca
import Funcionario.models.treinamento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0170_alter_comunicado_lista_assinaturas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaotreinamento",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.avaliacao_treinamento.renomear_anexo_avaliacao,
                validators=[
                    Funcionario.models.avaliacao_treinamento.MaxFileSizeValidator(5)
                ],
                verbose_name="Comprovante/Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="descricao_arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.cargo.renomear_descricao_cargo,
                validators=[Funcionario.models.cargo.MaxFileSizeValidator(5)],
                verbose_name="Arquivo Descritivo",
            ),
        ),
        migrations.AlterField(
            model_name="listapresenca",
            name="lista_presenca",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.lista_presenca.renomear_anexo_lista_presenca,
                validators=[Funcionario.models.lista_presenca.MaxFileSizeValidator(5)],
                verbose_name="Arquivo da Lista de Presença",
            ),
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.treinamento.renomear_anexo_treinamento,
                validators=[Funcionario.models.treinamento.MaxFileSizeValidator(5)],
                verbose_name="Anexo",
            ),
        ),
    ]
