# Generated by Django 4.2.16 on 2025-08-13 10:42

import Funcionario.models.avaliacao_anual
import Funcionario.models.avaliacao_experiencia
import Funcionario.models.job_rotation_evaluation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0171_alter_avaliacaotreinamento_anexo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaoanual",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.avaliacao_anual.renomear_anexo_avaliacao_anual,
                validators=[Funcionario.models.avaliacao_anual.MaxFileSizeValidator(5)],
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaoexperiencia",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.avaliacao_experiencia.renomear_anexo_avaliacao_experiencia,
                validators=[
                    Funcionario.models.avaliacao_experiencia.MaxFileSizeValidator(5)
                ],
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="jobrotationevaluation",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Funcionario.models.job_rotation_evaluation.renomear_anexo_jobrotation,
                validators=[
                    Funcionario.models.job_rotation_evaluation.MaxFileSizeValidator(5)
                ],
                verbose_name="Anexo (arquivo)",
            ),
        ),
    ]
