# Generated by Django 4.2.16 on 2025-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0172_alter_avaliacaoanual_anexo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="codigo",
            field=models.CharField(max_length=6, verbose_name="Código"),
        ),
    ]
