# Generated by Django 4.2.16 on 2025-09-03 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0173_alter_documento_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRotationAvaliacaoGestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assinante_nome",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "assinante_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("assinado_em", models.DateTimeField(blank=True, null=True)),
                ("assinado_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "assinado_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("assinado", models.BooleanField(default=False)),
                (
                    "token_publico",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "gestor_nome",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "gestor_cargo",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "gestor_setor",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("colaborador_treinado", models.BooleanField(default=False)),
                ("g1_func_tinha_info", models.BooleanField(default=False)),
                ("g1_de_quem", models.TextField(blank=True, null=True)),
                (
                    "g1_infos_foram",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("suficientes", "suficientes"),
                            ("insuficientes", "insuficientes"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("g1_faltaram", models.CharField(blank=True, max_length=40, null=True)),
                ("g1_detalhar", models.TextField(blank=True, null=True)),
                ("g2_dificuldades", models.BooleanField(default=False)),
                ("g2_detalhar", models.TextField(blank=True, null=True)),
                (
                    "g2_adaptacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rápida", "rápida"),
                            ("lenta", "lenta"),
                            ("regular", "regular"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "g3_desempenho",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ótimo", "ótimo"),
                            ("bom", "bom"),
                            ("regular", "regular"),
                            ("ruim", "ruim"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "g4_atitude_duvida",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolve sozinho", "resolve sozinho"),
                            ("solicita ajuda ao colega", "solicita ajuda ao colega"),
                            (
                                "dirige-se ao chefe imediato",
                                "dirige-se ao chefe imediato",
                            ),
                            ("nunca pede ajuda", "nunca pede ajuda"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("g4_como_e_atendido", models.TextField(blank=True, null=True)),
                (
                    "g5_cooperacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cooperação espontânea", "cooperação espontânea"),
                            ("não existe cooperação", "não existe cooperação"),
                            (
                                "cooperação quando solicitado",
                                "cooperação quando solicitado",
                            ),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("g5_justifique", models.TextField(blank=True, null=True)),
                ("g6_treinamento_dialogo", models.BooleanField(default=True)),
                ("g6_detalhar", models.TextField(blank=True, null=True)),
                ("g7_adaptou_facil", models.TextField(blank=True, null=True)),
                ("g7_adaptou_dificil", models.TextField(blank=True, null=True)),
                ("g8_satisfeito", models.BooleanField(default=True)),
                ("g8_motivo_insatisfacao", models.TextField(blank=True, null=True)),
                ("g9_como_adm_pessoal_ajuda", models.TextField(blank=True, null=True)),
                ("g10_critica_sugestao", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "jobrotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_gestor",
                        to="Funcionario.jobrotationevaluation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobRotationAvaliacaoColaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assinante_nome",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "assinante_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("assinado_em", models.DateTimeField(blank=True, null=True)),
                ("assinado_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "assinado_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("assinado", models.BooleanField(default=False)),
                (
                    "token_publico",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "colaborador_nome",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "cargo_anterior",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "cargo_atual",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "setor_anterior",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "setor_atual",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("p1_recebeu_infos", models.BooleanField(default=False)),
                (
                    "p1_infos_foram",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("suficientes", "suficientes"),
                            ("insuficientes", "insuficientes"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("p1_faltaram", models.CharField(blank=True, max_length=40, null=True)),
                ("p1_favor_detalhar", models.TextField(blank=True, null=True)),
                ("p2_teve_dificuldade", models.BooleanField(default=False)),
                ("p2_detalhes", models.TextField(blank=True, null=True)),
                (
                    "p2_adaptacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rápida", "rápida"),
                            ("lenta", "lenta"),
                            ("regular", "regular"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "p3_desempenho",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ótimo", "ótimo"),
                            ("bom", "bom"),
                            ("regular", "regular"),
                            ("ruim", "ruim"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "p4_atitude_duvida",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolve sozinho", "resolve sozinho"),
                            ("solicita ajuda ao colega", "solicita ajuda ao colega"),
                            (
                                "dirige-se ao chefe imediato",
                                "dirige-se ao chefe imediato",
                            ),
                            ("nunca pede ajuda", "nunca pede ajuda"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("p4_como_e_atendido", models.TextField(blank=True, null=True)),
                (
                    "p5_metodo_empresa_ou_proprio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("método da empresa", "método da empresa"),
                            ("próprio método", "próprio método"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("p5_justifique", models.TextField(blank=True, null=True)),
                ("p5_houve_maior_rendimento", models.BooleanField(default=False)),
                ("p6_dialogo_com_chefe", models.BooleanField(default=True)),
                ("p6_detalhar", models.TextField(blank=True, null=True)),
                ("p7_adaptou_facil", models.TextField(blank=True, null=True)),
                ("p7_adaptou_dificil", models.TextField(blank=True, null=True)),
                ("p8_satisfeito", models.BooleanField(default=True)),
                ("p8_motivo_insatisfacao", models.TextField(blank=True, null=True)),
                ("p9_como_adm_pessoal_ajuda", models.TextField(blank=True, null=True)),
                ("p10_critica_sugestao", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "jobrotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_colaborador",
                        to="Funcionario.jobrotationevaluation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
