# Generated by Django 4.2.16 on 2025-09-09 15:25

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0174_jobrotationavaliacaogestor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrotationavaliacaocolaborador",
            name="p1_favor_detalhar",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações"
            ),
        ),
    ]
