# Generated by Django 4.2.16 on 2025-07-31 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qualidade_fornecimento", "0099_alter_fornecedorqualificado_data_homologacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapaRoteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.PositiveIntegerField(verbose_name="Etapa Nº")),
                (
                    "pph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Peças por Hora",
                    ),
                ),
                (
                    "setup_minutos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tempo de Setup (min)",
                    ),
                ),
            ],
            options={
                "ordering": ["etapa"],
            },
        ),
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=100)),
                (
                    "grupo_de_maquinas",
                    models.CharField(
                        choices=[
                            ("MCGC", "Mola de Compressão Grupo C"),
                            ("MCGD", "Mola de Compressão Grupo D"),
                            ("MTRAGC", "Mola de Tração Grupo C"),
                            ("MTRAGX", "Mola de Tração Grupo X"),
                            ("MTRAGD", "Mola de Tração Grupo D"),
                            ("MTORGC", "Mola de Torção Grupo C"),
                            ("MTORGX", "Mola de Torção Grupo X"),
                            ("MTORGD", "Mola de Torção Grupo D"),
                            ("PEGE", "Peças Estampadas Grupo E"),
                            ("PEGP", "Peças Estampadas Grupo P"),
                            ("HGD", "Hastes Grupo D"),
                            ("HGM", "Hastes Grupo M"),
                            ("HGE", "Hastes Grupo E"),
                            ("HGC", "Hastes Grupo C"),
                            ("AGC", "Anel Grupo C"),
                            ("AGD", "Anel Grupo D"),
                            ("AGE", "Anel Grupo E"),
                            ("PGC", "Pino Grupo C"),
                            ("PGE", "Pino Grupo E"),
                        ],
                        max_length=6,
                        verbose_name="Grupo de Máquinas",
                    ),
                ),
                (
                    "velocidade",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unidade do produto por hora",
                        max_digits=10,
                    ),
                ),
                ("valor_hora", models.DecimalField(decimal_places=2, max_digits=10)),
                ("consumo_kwh", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ServicoRealizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Serviço"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoteiroProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tipo_roteiro",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        default="A",
                        max_length=1,
                        verbose_name="Tipo do Roteiro",
                    ),
                ),
                (
                    "revisao",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Revisão do Roteiro"
                    ),
                ),
                (
                    "peso_unitario_gramas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Peso Unitário (g)",
                    ),
                ),
                (
                    "observacoes_gerais",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Observações Gerais"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aprovado",
                    models.BooleanField(default=False, verbose_name="Aprovado?"),
                ),
                (
                    "aprovado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de aprovação"
                    ),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roteiros_aprovados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteiros",
                        to="comercial.item",
                        verbose_name="Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roteiro de Produção",
                "verbose_name_plural": "Roteiros de Produção",
            },
        ),
        migrations.CreateModel(
            name="PropriedadesEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_acao",
                    models.CharField(max_length=100, verbose_name="Nome da Ação"),
                ),
                (
                    "descricao_detalhada",
                    models.TextField(verbose_name="Descrição Detalhada"),
                ),
                ("seguranca_mp", models.BooleanField(default=False, verbose_name="MP")),
                ("seguranca_ts", models.BooleanField(default=False, verbose_name="TS")),
                ("seguranca_m1", models.BooleanField(default=False, verbose_name="M1")),
                ("seguranca_l1", models.BooleanField(default=False, verbose_name="L1")),
                ("seguranca_l2", models.BooleanField(default=False, verbose_name="L2")),
                (
                    "etapa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propriedades",
                        to="tecnico.etaparoteiro",
                    ),
                ),
                (
                    "ferramenta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comercial.ferramenta",
                        verbose_name="Ferramenta",
                    ),
                ),
                (
                    "maquinas",
                    models.ManyToManyField(
                        blank=True,
                        to="tecnico.maquina",
                        verbose_name="Máquinas Permitidas",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="maquina",
            name="servicos_realizados",
            field=models.ManyToManyField(
                blank=True,
                to="tecnico.servicorealizado",
                verbose_name="Serviços Realizados",
            ),
        ),
        migrations.CreateModel(
            name="InsumoEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "tipo_insumo",
                    models.CharField(
                        choices=[
                            ("matéria_prima", "Matéria-Prima"),
                            ("componente", "Componente"),
                            ("insumos", "Insumos"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("obrigatorio", models.BooleanField(default=False)),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insumos",
                        to="tecnico.etaparoteiro",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="qualidade_fornecimento.materiaprimacatalogo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadorTecnicoRegistroMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        choices=[("5.1", "Cumprimento de Prazo de Desenvolvimento")],
                        max_length=10,
                    ),
                ),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField(blank=True, null=True)),
                ("trimestre", models.IntegerField(blank=True, null=True)),
                ("valor", models.FloatField()),
                ("media", models.FloatField()),
                ("meta", models.FloatField()),
                ("total_realizados", models.IntegerField(default=0)),
                ("total_aprovados", models.IntegerField(default=0)),
                ("comentario", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Registro de Indicador Técnico",
                "verbose_name_plural": "Registros de Indicadores Técnicos",
                "unique_together": {("indicador", "ano", "mes", "trimestre")},
            },
        ),
        migrations.AddField(
            model_name="etaparoteiro",
            name="roteiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etapas",
                to="tecnico.roteiroproducao",
            ),
        ),
        migrations.AddField(
            model_name="etaparoteiro",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="comercial.centrodecusto",
            ),
        ),
    ]
