# Generated by Django 4.2.16 on 2025-07-04 14:41

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
        ("qualidade_fornecimento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapaRoteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.PositiveIntegerField(verbose_name="Etapa Nº")),
                (
                    "pph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Peças por Hora",
                    ),
                ),
                (
                    "setup_minutos",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tempo de Setup (min)"
                    ),
                ),
            ],
            options={
                "ordering": ["etapa"],
            },
        ),
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("servico_realizado", models.CharField(max_length=200)),
                (
                    "velocidade",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unidade do produto por hora",
                        max_digits=10,
                    ),
                ),
                ("valor_hora", models.DecimalField(decimal_places=2, max_digits=10)),
                ("consumo_kwh", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="RoteiroProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "massa_mil_pecas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Massa por 1.000 peças (kg)",
                    ),
                ),
                (
                    "observacoes_gerais",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Observações Gerais"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteiro",
                        to="comercial.item",
                        verbose_name="Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roteiro de Produção",
                "verbose_name_plural": "Roteiros de Produção",
            },
        ),
        migrations.CreateModel(
            name="PropriedadesEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_acao",
                    models.CharField(max_length=100, verbose_name="Nome da Ação"),
                ),
                (
                    "descricao_detalhada",
                    models.TextField(verbose_name="Descrição Detalhada"),
                ),
                (
                    "etapa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propriedades",
                        to="tecnico.etaparoteiro",
                    ),
                ),
                (
                    "ferramenta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comercial.ferramenta",
                        verbose_name="Ferramenta",
                    ),
                ),
                (
                    "maquinas",
                    models.ManyToManyField(
                        blank=True,
                        to="tecnico.maquina",
                        verbose_name="Máquinas Permitidas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsumoEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "tipo_insumo",
                    models.CharField(
                        choices=[
                            ("matéria_prima", "Matéria-Prima"),
                            ("componente", "Componente"),
                            ("insumos", "Insumos"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("obrigatorio", models.BooleanField(default=False)),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insumos",
                        to="tecnico.etaparoteiro",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="qualidade_fornecimento.materiaprimacatalogo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="etaparoteiro",
            name="roteiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etapas",
                to="tecnico.roteiroproducao",
            ),
        ),
        migrations.AddField(
            model_name="etaparoteiro",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="comercial.centrodecusto",
            ),
        ),
    ]
