# Generated by Django 4.2.16 on 2025-06-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("servico_realizado", models.CharField(max_length=200)),
                (
                    "velocidade",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unidade do produto por hora",
                        max_digits=10,
                    ),
                ),
                ("valor_hora", models.DecimalField(decimal_places=2, max_digits=10)),
                ("consumo_kwh", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "permissions": [
                    ("view_maquina", "Visualizar Máquinas"),
                    ("add_maquina", "Cadastrar Máquinas"),
                    ("change_maquina", "Editar Máquinas"),
                    ("delete_maquina", "Excluir Máquinas"),
                ],
            },
        ),
    ]