# Generated by Django 4.2.16 on 2025-06-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maquina",
            options={},
        ),
    ]