# Generated by Django 4.2.16 on 2025-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0002_remove_insumoetapa_quantidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roteiroproducao",
            name="peso_unitario_gramas",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Peso Unitário (g)",
            ),
        ),
    ]
