# Generated by Django 4.2.16 on 2025-06-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0020_cotacao"),
        (
            "qualidade_fornecimento",
            "0085_inspecaoservicoexterno_assinatura_data_and_more",
        ),
        ("tecnico", "0002_alter_maquina_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapaRoteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.PositiveIntegerField(verbose_name="Etapa Nº")),
                (
                    "pph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Peças por Hora",
                    ),
                ),
                (
                    "setup_minutos",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tempo de Setup (min)"
                    ),
                ),
            ],
            options={
                "ordering": ["etapa"],
            },
        ),
        migrations.CreateModel(
            name="RoteiroProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteiros",
                        to="comercial.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropriedadesEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_acao",
                    models.CharField(max_length=100, verbose_name="Nome da Ação"),
                ),
                (
                    "descricao_detalhada",
                    models.TextField(verbose_name="Descrição Detalhada"),
                ),
                (
                    "etapa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propriedades",
                        to="tecnico.etaparoteiro",
                    ),
                ),
                (
                    "maquinas",
                    models.ManyToManyField(
                        blank=True,
                        to="tecnico.maquina",
                        verbose_name="Máquinas Permitidas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsumoEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_por_1000",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        verbose_name="Qtd para 1000 peças",
                    ),
                ),
                ("obrigatorio", models.BooleanField(default=False)),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insumos",
                        to="tecnico.etaparoteiro",
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="qualidade_fornecimento.materiaprimacatalogo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="etaparoteiro",
            name="roteiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etapas",
                to="tecnico.roteiroproducao",
            ),
        ),
        migrations.AddField(
            model_name="etaparoteiro",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="comercial.centrodecusto",
            ),
        ),
    ]