# Generated by Django 4.2.16 on 2025-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade_fornecimento", "0100_inspecao10_setor"),
        ("tecnico", "0003_alter_roteiroproducao_peso_unitario_gramas"),
    ]

    operations = [
        migrations.AddField(
            model_name="roteiroproducao",
            name="fontes_homologadas",
            field=models.ManyToManyField(
                blank=True,
                to="qualidade_fornecimento.fornecedorqualificado",
                verbose_name="Fontes Homologadas",
            ),
        ),
    ]
