# Generated by Django 4.2.16 on 2025-06-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0003_etaparoteiro_roteiroproducao_propriedadesetapa_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insumoetapa",
            old_name="insumo",
            new_name="materia_prima",
        ),
        migrations.RemoveField(
            model_name="insumoetapa",
            name="quantidade_por_1000",
        ),
        migrations.AddField(
            model_name="insumoetapa",
            name="quantidade",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insumoetapa",
            name="tipo_insumo",
            field=models.CharField(
                choices=[
                    ("matéria_prima", "Matéria-Prima"),
                    ("componente", "Componente"),
                    ("outros", "Outros"),
                ],
                default=2,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]