# Generated by Django 4.2.16 on 2025-06-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0020_cotacao"),
        ("tecnico", "0004_rename_insumo_insumoetapa_materia_prima_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roteiroproducao",
            options={
                "verbose_name": "Roteiro de Produção",
                "verbose_name_plural": "Roteiros de Produção",
            },
        ),
        migrations.AlterField(
            model_name="roteiroproducao",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roteiro",
                to="comercial.item",
                verbose_name="Item",
            ),
        ),
    ]