# Generated by Django 4.2.16 on 2025-08-22 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tecnico", "0004_roteiroproducao_fontes_homologadas"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoteiroRevisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_revisao",
                    models.CharField(max_length=20, verbose_name="Número da Revisão"),
                ),
                (
                    "data_revisao",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Revisão",
                    ),
                ),
                (
                    "descricao_mudanca",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da Mudança"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=10,
                        verbose_name="Status da Revisão",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roteiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisoes",
                        to="tecnico.roteiroproducao",
                        verbose_name="Roteiro",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_revisao", "-id"],
            },
        ),
    ]
