# Generated by Django 4.2.16 on 2025-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0005_roteirorevisao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roteiroproducao",
            name="revisao",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Revisão do Roteiro"
            ),
        ),
    ]
