# Generated by Django 4.2.16 on 2025-06-18 17:58

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0005_alter_roteiroproducao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roteiroproducao",
            name="massa_mil_pecas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Massa por 1.000 peças (kg)",
            ),
        ),
        migrations.AddField(
            model_name="roteiroproducao",
            name="observacoes_gerais",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Observações Gerais"
            ),
        ),
        migrations.AlterField(
            model_name="insumoetapa",
            name="tipo_insumo",
            field=models.CharField(
                choices=[
                    ("matéria_prima", "Matéria-Prima"),
                    ("componente", "Componente"),
                    ("insumos", "Insumos"),
                    ("outros", "Outros"),
                ],
                max_length=20,
            ),
        ),
    ]