# Generated by Django 4.2.16 on 2025-06-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0021_item_codigo_desenho"),
        ("tecnico", "0006_roteiroproducao_massa_mil_pecas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propriedadesetapa",
            name="ferramenta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="comercial.ferramenta",
                verbose_name="Ferramenta",
            ),
        ),
    ]