# Generated by Django 4.2.16 on 2025-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0006_alter_roteiroproducao_revisao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumoetapa",
            name="desenvolvido",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=15,
                null=True,
                verbose_name="Desenvolvido em (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="roteiroproducao",
            name="revisao",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Revisão do Roteiro"
            ),
        ),
    ]
