# Generated by Django 4.2.16 on 2025-07-21 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tecnico", "0007_propriedadesetapa_ferramenta"),
    ]

    operations = [
        migrations.AddField(
            model_name="roteiroproducao",
            name="aprovado",
            field=models.BooleanField(default=False, verbose_name="Aprovado?"),
        ),
        migrations.AddField(
            model_name="roteiroproducao",
            name="aprovado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de aprovação"
            ),
        ),
        migrations.AddField(
            model_name="roteiroproducao",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roteiros_aprovados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovado por",
            ),
        ),
    ]
