# Generated by Django 4.2.16 on 2025-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0007_alter_insumoetapa_desenvolvido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumoetapa",
            name="desenvolvido",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Desenvolvido em (mm)",
            ),
        ),
    ]
