# Generated by Django 4.2.16 on 2025-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tecnico",
            "0008_roteiroproducao_aprovado_roteiroproducao_aprovado_em_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roteiroproducao",
            name="revisao",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Revisão do Roteiro"
            ),
        ),
    ]
