# Generated by Django 4.2.16 on 2025-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0008_alter_insumoetapa_desenvolvido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumoetapa",
            name="peso_bruto",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Peso Bruto (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="insumoetapa",
            name="peso_liquido",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Peso Líquido (kg)",
            ),
        ),
    ]
