# Generated by Django 4.2.16 on 2025-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0009_roteiroproducao_revisao"),
    ]

    operations = [
        migrations.AddField(
            model_name="propriedadesetapa",
            name="seguranca_l1",
            field=models.BooleanField(default=False, verbose_name="L1"),
        ),
        migrations.AddField(
            model_name="propriedadesetapa",
            name="seguranca_l2",
            field=models.BooleanField(default=False, verbose_name="L2"),
        ),
        migrations.AddField(
            model_name="propriedadesetapa",
            name="seguranca_m1",
            field=models.BooleanField(default=False, verbose_name="M1"),
        ),
        migrations.AddField(
            model_name="propriedadesetapa",
            name="seguranca_mp",
            field=models.BooleanField(default=False, verbose_name="MP"),
        ),
        migrations.AddField(
            model_name="propriedadesetapa",
            name="seguranca_ts",
            field=models.BooleanField(default=False, verbose_name="TS"),
        ),
    ]
