# Generated by Django 4.2.16 on 2025-07-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0010_propriedadesetapa_seguranca_l1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicoRealizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Serviço"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="maquina",
            name="servico_realizado",
        ),
        migrations.AddField(
            model_name="maquina",
            name="servicos_realizados",
            field=models.ManyToManyField(
                blank=True,
                to="tecnico.servicorealizado",
                verbose_name="Serviços Realizados",
            ),
        ),
    ]
