# Generated by Django 4.2.16 on 2025-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0011_servicorealizado_remove_maquina_servico_realizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etaparoteiro",
            name="setup_minutos",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Tempo de Setup (min)",
            ),
        ),
    ]
