# Generated by Django 4.2.16 on 2025-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0012_alter_etaparoteiro_setup_minutos"),
    ]

    operations = [
        migrations.AddField(
            model_name="roteiroproducao",
            name="tipo_roteiro",
            field=models.CharField(
                choices=[
                    ("A", "Tipo A"),
                    ("B", "Tipo B"),
                    ("C", "Tipo C"),
                    ("D", "Tipo D"),
                ],
                default="A",
                max_length=1,
                verbose_name="Tipo do Roteiro",
            ),
        ),
    ]
