# Generated by Django 4.2.16 on 2025-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0013_roteiroproducao_tipo_roteiro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roteiroproducao",
            name="massa_mil_pecas",
        ),
        migrations.AddField(
            model_name="roteiroproducao",
            name="peso_unitario_gramas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Peso Unitário (g)",
            ),
        ),
    ]
