# Generated by Django 4.2.16 on 2025-07-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0087_ordemdesenvolvimento_usuario_comercial_and_more"),
        ("tecnico", "0014_remove_roteiroproducao_massa_mil_pecas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roteiroproducao",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roteiros",
                to="comercial.item",
                verbose_name="Item",
            ),
        ),
    ]
