# Generated by Django 4.2.16 on 2025-07-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0015_alter_roteiroproducao_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roteiroproducao",
            name="tipo_roteiro",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="A",
                max_length=1,
                verbose_name="Tipo do Roteiro",
            ),
        ),
    ]
