# Generated by Django 4.2.16 on 2025-07-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0016_alter_roteiroproducao_tipo_roteiro"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicadorTecnicoRegistroMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        choices=[("5.1", "Cumprimento de Prazo de Desenvolvimento")],
                        max_length=10,
                    ),
                ),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField(blank=True, null=True)),
                ("trimestre", models.IntegerField(blank=True, null=True)),
                ("valor", models.FloatField()),
                ("media", models.FloatField()),
                ("meta", models.FloatField()),
                ("total_realizados", models.IntegerField(default=0)),
                ("total_aprovados", models.IntegerField(default=0)),
                ("comentario", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Registro de Indicador Técnico",
                "verbose_name_plural": "Registros de Indicadores Técnicos",
                "unique_together": {("indicador", "ano", "mes", "trimestre")},
            },
        ),
    ]
