# Generated by Django 4.2.16 on 2025-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0017_indicadortecnicoregistromensal"),
    ]

    operations = [
        migrations.AddField(
            model_name="maquina",
            name="grupo_de_maquinas",
            field=models.CharField(
                choices=[
                    ("MCGC", "Mola de Compressão Grupo C"),
                    ("MCGD", "Mola de Compressão Grupo D"),
                    ("MTRAGC", "Mola de Tração Grupo C"),
                    ("MTRAGX", "Mola de Tração Grupo X"),
                    ("MTRAGD", "Mola de Tração Grupo D"),
                    ("MTORGC", "Mola de Torção Grupo C"),
                    ("MTORGX", "Mola de Torção Grupo X"),
                    ("MTORGD", "Mola de Torção Grupo D"),
                    ("PEGE", "Peças Estampadas Grupo E"),
                    ("PEGP", "Peças Estampadas Grupo P"),
                    ("HGD", "Hastes Grupo D"),
                    ("HGM", "Hastes Grupo M"),
                    ("HGE", "Hastes Grupo E"),
                    ("HGC", "Hastes Grupo C"),
                    ("AGC", "Anel Grupo C"),
                    ("AGD", "Anel Grupo D"),
                    ("AGE", "Anel Grupo E"),
                    ("PGC", "Pino Grupo C"),
                    ("PGE", "Pino Grupo E"),
                ],
                default=1,
                max_length=6,
                verbose_name="Grupo de Máquinas",
            ),
            preserve_default=False,
        ),
    ]
