# Generated by Django 4.2.16 on 2025-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnico", "0018_maquina_grupo_de_maquinas"),
    ]

    operations = [
        migrations.AddField(
            model_name="roteiroproducao",
            name="status",
            field=models.CharField(
                choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                default="ativo",
                max_length=8,
                verbose_name="Status",
            ),
        ),
    ]
