# Generated by Django 4.2.16 on 2025-07-04 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Funcionario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PessoaPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("visitante", "Visitante"),
                            ("entregador", "Entregador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RG"
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Empresa/Origem",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_portaria/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroConsumoAgua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "leitura_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Leitura Inicial (m³)",
                    ),
                ),
                (
                    "leitura_final",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Leitura Final (m³)",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
            ],
            options={
                "verbose_name": "Registro de Consumo de Água",
                "verbose_name_plural": "Registros de Consumo de Água",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="VeiculoPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, unique=True, verbose_name="Placa"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("carro", "Carro"),
                            ("moto", "Moto"),
                            ("bicicleta", "Bicicleta"),
                            ("caminhao", "Caminhão"),
                            ("carreta", "Carreta"),
                            ("bau", "Baú"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Veículo",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculos_individuais",
                        to="portaria.pessoaportaria",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pessoaportaria",
            name="veiculos_vinculados",
            field=models.ManyToManyField(
                blank=True,
                related_name="pessoas_vinculadas",
                to="portaria.veiculoportaria",
            ),
        ),
        migrations.CreateModel(
            name="OcorrenciaPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ocorrencia",
                    models.CharField(
                        choices=[
                            ("alarme", "Alarme"),
                            ("acesso_indevido", "Acesso Indevido"),
                            ("confusao", "Confusão"),
                            ("reclamacao", "Reclamação"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                ("local", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("hora_fim", models.TimeField(blank=True, null=True)),
                ("descricao", models.TextField()),
                ("foi_registrado_boletim", models.BooleanField(default=False)),
                (
                    "arquivo_anexo",
                    models.FileField(blank=True, null=True, upload_to="ocorrencias/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("analise", "Em Análise"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="aberta",
                        max_length=20,
                    ),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "numero_boletim",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pessoas_envolvidas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ocorrencias",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "responsavel_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigacaoPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Quem ligou")),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de telefone"
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Empresa / Origem"
                    ),
                ),
                ("horario", models.TimeField(verbose_name="Horário da ligação")),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "recado_enviado",
                    models.BooleanField(default=False, verbose_name="Recado enviado"),
                ),
                ("recado", models.TextField(verbose_name="Recado")),
                (
                    "falar_com",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Funcionario.funcionario",
                        verbose_name="Falar com",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntradaVisitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("hora_entrada", models.TimeField(default=django.utils.timezone.now)),
                ("hora_saida", models.TimeField(blank=True, null=True)),
                ("falar_com", models.CharField(max_length=100)),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("coleta", "Coleta de Mercadorias"),
                            ("entrega", "Entrega de Mercadorias"),
                            ("servico", "Prestador de Serviço"),
                            ("entrevista", "Entrevista"),
                            ("reuniao", "Reunião"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "outro_motivo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portaria.pessoaportaria",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portaria.veiculoportaria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtrasoSaida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField(blank=True, null=True)),
                ("hora_fim", models.TimeField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("atraso", "Atraso"),
                            ("saida", "Saída Antecipada"),
                            ("hora_extra", "Hora Extra"),
                        ],
                        max_length=10,
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                ("utilizado_no_banco", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias_portaria",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atraso ou Saída Antecipada",
                "verbose_name_plural": "Atrasos e Saídas Antecipadas",
                "ordering": ["-data", "-horario"],
            },
        ),
    ]
