# Generated by Django 4.2.16 on 2025-05-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pessoaportaria",
            name="colaborador",
        ),
    ]
