# Generated by Django 4.2.16 on 2025-05-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0002_remove_pessoaportaria_colaborador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoaportaria",
            name="tipo",
            field=models.CharField(
                choices=[("visitante", "Visitante"), ("entregador", "Entregador")],
                max_length=20,
            ),
        ),
    ]
