# Generated by Django 4.2.16 on 2025-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0004_pessoaportaria_foto_alter_pessoaportaria_documento"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeiculoPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, unique=True, verbose_name="Placa"),
                ),
                (
                    "marca",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Marca"
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Modelo"
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Cor"
                    ),
                ),
                (
                    "ano",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "chassi",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Chassi"
                    ),
                ),
            ],
        ),
    ]
