# Generated by Django 4.2.16 on 2025-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0005_veiculoportaria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculoportaria",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="veiculoportaria",
            name="chassi",
        ),
        migrations.RemoveField(
            model_name="veiculoportaria",
            name="cor",
        ),
        migrations.RemoveField(
            model_name="veiculoportaria",
            name="marca",
        ),
        migrations.RemoveField(
            model_name="veiculoportaria",
            name="modelo",
        ),
        migrations.AddField(
            model_name="veiculoportaria",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("carro", "Carro"),
                    ("moto", "Moto"),
                    ("bicicleta", "Bicicleta"),
                    ("caminhao", "Caminhão"),
                    ("carreta", "Carreta"),
                    ("bau", "Baú"),
                    ("outros", "Outros"),
                ],
                default=1,
                max_length=20,
                verbose_name="Tipo de Veículo",
            ),
            preserve_default=False,
        ),
    ]
