# Generated by Django 4.2.16 on 2025-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0006_remove_veiculoportaria_ano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoaportaria",
            name="veiculos_vinculados",
            field=models.ManyToManyField(
                blank=True, related_name="pessoas", to="portaria.veiculoportaria"
            ),
        ),
    ]
