# Generated by Django 4.2.16 on 2025-05-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0007_pessoaportaria_veiculos_vinculados"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculoportaria",
            name="pessoa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="veiculos_individuais",
                to="portaria.pessoaportaria",
                verbose_name="Pessoa Vinculada",
            ),
        ),
    ]
