# Generated by Django 4.2.16 on 2025-05-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0008_veiculoportaria_pessoa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoaportaria",
            name="veiculos_vinculados",
            field=models.ManyToManyField(
                blank=True,
                related_name="pessoas_vinculadas",
                to="portaria.veiculoportaria",
            ),
        ),
        migrations.AlterField(
            model_name="veiculoportaria",
            name="pessoa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="veiculos_individuais",
                to="portaria.pessoaportaria",
            ),
        ),
    ]
