# Generated by Django 4.2.16 on 2025-05-20 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0009_alter_pessoaportaria_veiculos_vinculados_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaVisitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("hora_entrada", models.TimeField(default=django.utils.timezone.now)),
                ("hora_saida", models.TimeField(blank=True, null=True)),
                ("falar_com", models.CharField(max_length=100)),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("coleta", "Coleta de Mercadorias"),
                            ("entrega", "Entrega de Mercadorias"),
                            ("servico", "Prestador de Serviço"),
                            ("entrevista", "Entrevista"),
                            ("reuniao", "Reunião"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "outro_motivo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portaria.pessoaportaria",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portaria.veiculoportaria",
                    ),
                ),
            ],
        ),
    ]
