# Generated by Django 4.2.16 on 2025-05-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0117_funcionario_user"),
        ("portaria", "0010_entradavisitante"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtrasoSaida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("atraso", "Atraso"), ("saida", "Saída Antecipada")],
                        max_length=10,
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias_portaria",
                        to="Funcionario.funcionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atraso ou Saída Antecipada",
                "verbose_name_plural": "Atrasos e Saídas Antecipadas",
                "ordering": ["-data", "-horario"],
            },
        ),
    ]
