# Generated by Django 4.2.16 on 2025-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0011_atrasosaida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atrasosaida",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("atraso", "Atraso"),
                    ("saida", "Saída Antecipada"),
                    ("hora_extra", "Hora Extra"),
                ],
                max_length=10,
            ),
        ),
    ]
