# Generated by Django 4.2.16 on 2025-05-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0117_funcionario_user"),
        ("portaria", "0012_alter_atrasosaida_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LigacaoPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Quem ligou")),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de telefone"
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Empresa / Origem"
                    ),
                ),
                ("horario", models.TimeField(verbose_name="Horário da ligação")),
                (
                    "data",
                    models.DateField(auto_now_add=True, verbose_name="Data da ligação"),
                ),
                ("recado", models.TextField(verbose_name="Recado")),
                (
                    "falar_com",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Funcionario.funcionario",
                        verbose_name="Falar com",
                    ),
                ),
            ],
        ),
    ]
