# Generated by Django 4.2.16 on 2025-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0014_alter_ligacaoportaria_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="ligacaoportaria",
            name="recado_enviado",
            field=models.BooleanField(default=False, verbose_name="Recado enviado"),
        ),
    ]
