# Generated by Django 4.2.16 on 2025-05-21 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Funcionario", "0117_funcionario_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portaria", "0015_ligacaoportaria_recado_enviado"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcorrenciaPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ocorrencia",
                    models.CharField(
                        choices=[
                            ("alarme", "Alarme"),
                            ("acesso_indevido", "Acesso Indevido"),
                            ("confusao", "Confusão"),
                            ("reclamacao", "Reclamação"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                ("local", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("hora_fim", models.TimeField(blank=True, null=True)),
                ("descricao", models.TextField()),
                ("foi_registrado_boletim", models.BooleanField(default=False)),
                (
                    "arquivo_anexo",
                    models.FileField(blank=True, null=True, upload_to="ocorrencias/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("analise", "Em Análise"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="aberta",
                        max_length=20,
                    ),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoas_envolvidas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ocorrencias",
                        to="Funcionario.funcionario",
                    ),
                ),
                (
                    "responsavel_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
