# Generated by Django 4.2.16 on 2025-05-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0016_ocorrenciaportaria"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrenciaportaria",
            name="numero_boletim",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
