# Generated by Django 4.2.16 on 2025-05-21 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0017_ocorrenciaportaria_numero_boletim"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroConsumoAgua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "leitura_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Leitura Inicial (m³)",
                    ),
                ),
                (
                    "leitura_final",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Leitura Final (m³)",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
            ],
            options={
                "verbose_name": "Registro de Consumo de Água",
                "verbose_name_plural": "Registros de Consumo de Água",
                "ordering": ["-data"],
            },
        ),
    ]
