# Generated by Django 4.2.16 on 2025-05-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0018_registroconsumoagua"),
    ]

    operations = [
        migrations.AddField(
            model_name="atrasosaida",
            name="hora_fim",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
