# Generated by Django 4.2.16 on 2025-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0019_atrasosaida_hora_fim"),
    ]

    operations = [
        migrations.AddField(
            model_name="atrasosaida",
            name="utilizado_no_banco",
            field=models.BooleanField(default=False),
        ),
    ]
