# Generated by Django 4.2.16 on 2025-05-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaria", "0021_alter_atrasosaida_utilizado_no_banco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atrasosaida",
            name="utilizado_no_banco",
            field=models.BooleanField(default=False),
        ),
    ]
